### ISSUE TITLE
Hello Gordon, document.querySelector brings null and later it works fine without making anychange, what actually happens??

### ISSUE THREAD

**Issue by pkileka** [gordonmzhu/questions#10]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Each section of the form is required. Once you fill it out completely, re-open this issue and I'll take a look.
