### ISSUE TITLE
'My todos' in the console.log has an error message

### ISSUE THREAD

**Issue by greatbyte** [gordonmzhu/questions#104]
### What is the associated Watch and Code lesson?  2.42

Write your response here (required).
I did the steps in the video to create a 'My todos' but get an error in the console log like this "Uncaught SyntaxError: missing ) after argument list"
### Include a live demo link so that I can run your code. 
![todos](https://user-images.githubusercontent.com/13262746/48256396-b2310700-e40f-11e8-998d-9eadb8a56bfb.jpg)

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by greatbyte** [comment]
https://watchandcode.com/courses/60264/lectures/900206    at 2.38

I wanted to replicate what you did on the screen but found an error due to a syntax problem on my part. After I paid close attention, I was able to solve it. Thanks!

**Comment by greatbyte** [comment]
I am still learning but I like your radical honesty about asking questions. Thank you!

**Comment by gordonmzhu** [comment]
Awesome. Thanks for updating the issue and glad you were able to sort things out @greatbyte!
