### ISSUE TITLE
Is ES6 syntax part of the tutorial?

### ISSUE THREAD

**Issue by DaveEveritt** [gordonmzhu/questions#106]
### What is the associated Watch and Code lesson? 

I'd like to recommend this tutorial to my students, but we're asking them to use the following ES6 sytnax:  arrow functions, template literals and `const`/`let` over `var` - does the tutorial cover these?

### Include a live demo link so that I can run your code. 

My question is above (required).

### Explain the exact steps I need to take to replicate the problem. 

I'm 14% through... (required).

### What did you expect to happen? 

...but can't easily see... (required).

### What actually happened? 

...whether you cover... (required).

### Describe what you've done so far to troubleshoot the problem. 

... ES6 syntax! (required).

**Comment by gordonmzhu** [comment]
No. My philosophy is to teach a minimal subset of the language. 

Once they understand that core extremely well, they very easily pick up optional additions to the language (like the ones you've mentioned), on their own.

Students taught using this approach also very clearly understand the marginal benefits of new language features, so counterintuitively, they learn the new language features more deeply that students that are taught the new features from the very beginning.

**Comment by DaveEveritt** [comment]
thanks, understood.
