### ISSUE TITLE
Question about ".completed"

### ISSUE THREAD

**Issue by JacksonCohen** [gordonmzhu/questions#108]
I just want to start off by saying thank you for all your hard work putting this course together! It has been an incredible help for me and many others.

https://watchandcode.com/courses/60264/lectures/936343

I'm working on V6 and at the 2:30 mark you're writing a for loop and then use (this.todos[i].completed).  It's not the first time you used .completed and I am having a hard time understand how the code can understand what .completed means.  I thought it was perhaps a JS keyword but my Google search tells me it's not.  I've also looked through the code to find a spot where it is defined but to the best of my knowledge I don't see that either.  Perhaps you can shed some light on how this phrase is defined/understood in the code we wrote? Thanks!

**Comment by gordonmzhu** [comment]
I suggest going back and restarting from Version 4. Pay very careful attention to every single detail and you'll find your answer as you do this.
