### ISSUE TITLE
Issues displaying PLunker Preview Target

### ISSUE THREAD

**Issue by mjheredia89** [gordonmzhu/questions#116]
### What is the associated Watch and Code lesson? 

Hello! I am currently on 'It should store the todos array on an object' video in V3 -Objects and I do not see 'plunkerPreviewTarget' listed under the dropdown menu after inspecting my console (displayed at time: 2:48-2:52 in your video). 

https://watchandcode.com/courses/60264/lectures/900211

Down below is a screenshot of what you see in your video: 

![plnkr inspect 1](https://user-images.githubusercontent.com/43975487/48962450-03bfb280-ef35-11e8-948c-ec057bb796d2.JPG)

Down below is what I see when I click the dropdown menu:

![inspecting plnkr](https://user-images.githubusercontent.com/43975487/48962378-138ac700-ef34-11e8-96fc-da83fc9fe29a.JPG)

Do you know why this might be the case? I ran the function correctly as displayed in your video. I am also using google chrome (not sure if this information is helpful).  Please let me know if you need me to provide you additional context to the situation. Thank you for your time!

**Comment by gordonmzhu** [comment]
Make sure the area in the red circle is the same as mine.

![48962450-03bfb280-ef35-11e8-948c-ec057bb796d2](https://user-images.githubusercontent.com/734575/49131568-b631a580-f2a6-11e8-9e0f-f750a98a5729.JPG)

![48962378-138ac700-ef34-11e8-96fc-da83fc9fe29a](https://user-images.githubusercontent.com/734575/49131577-bcc01d00-f2a6-11e8-83f0-d63f8ea04658.JPG)

**Comment by Newlifedirection** [comment]
I have the same issue as above. plunkerPreviewTarget is not an option in my dropdown and the area you have circled in red looks the same.

**Comment by gordonmzhu** [comment]
You have to hit run as well.

**Comment by Newlifedirection** [comment]
Got it. Thanks

**Comment by PixelParasite101** [comment]
How do you do this in the new plunker?

**Comment by babycatatonia** [comment]
Bravo zhu majstore

**Comment by JuliusWilliams8944** [comment]
![D87HY8PmRM20BvamQXYhrA](https://user-images.githubusercontent.com/51384449/60218940-73cd4880-9836-11e9-89cd-636f39cb73a6.jpg)
![xE%6bsrGRlqUtXrC3aypNA](https://user-images.githubusercontent.com/51384449/60218954-834c9180-9836-11e9-8102-efe8069959f4.jpg)
No matter what I do I am unable to run the, because it states my todoList is undefined when, I believe, its the same as the tutorial. Help please!

**Comment by NeroOkwa** [comment]
I have the same issue,even after I have ran the code, saved and clicked inspect.

![pluncker](https://user-images.githubusercontent.com/50266242/60805288-85ff8e80-a134-11e9-8411-37b5bc281324.png)

**Comment by bethstimpson4** [comment]
Same issue as above, the plunkerPreviewTarget is highlighted in red and it keeps giving me an error message that my todolist is not defined.

**Comment by PixelParasite101** [comment]
Gordon Zhu switch to glitch later in the course.
See Version 10 - Click to delete ind the class curriculum.

**Comment by PixelParasite101** [comment]
> Same issue as above, the plunkerPreviewTarget is highlighted in red and it keeps giving me an error message that my todolist is not defined.

Gordon Zhu switch to glitch later in the course.
See Version 10 - Click to delete ind the class curriculum.

**Comment by prashantkn94** [comment]
This is what I am getting when I press the red circled button
![image](https://user-images.githubusercontent.com/22418796/64353804-fbe08300-d01b-11e9-8e8b-953d75d3f262.png)
I am unable to obtain this plunkerPreviewTarget thing, can you please help?

**Comment by richardcmckinney** [comment]
Believe I've found the solution to this issue in the new release of Plunker. See screenshots below:

- Screenshot of Plunker console **not open**, with JS pending execution: ![Plunker_Console_Unopened](https://user-images.githubusercontent.com/12281467/68967526-5b35de80-0795-11ea-86e1-613b5c0f339c.png)**

- Screenshot of Plunker console **open**, with JS executed: ![Plunker_Console](https://user-images.githubusercontent.com/12281467/68967396-04c8a000-0795-11ea-80aa-d08a815ed572.png)

**Comment by jonodapanda** [comment]
Just hit run

**Comment by anthonysim** [comment]
I'm literally having the same issues, I tried pressing run, then opening the console, but get the same error as @JuliusWilliams8944
