### ISSUE TITLE
Version 5 - toggleCompleted makes the change only once 

### ISSUE THREAD

**Issue by ogloz** [gordonmzhu/questions#118]
Hi Gordon,

### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/946811

### Include a live demo link so that I can run your code. 

[plunk-EkPQCJ63QhRyYu0mNzva.zip](https://github.com/gordonmzhu/questions/files/2621914/plunk-EkPQCJ63QhRyYu0mNzva.zip)

### Explain the exact steps I need to take to replicate the problem. 

run the following in the console:

todolist.addTodo('first')
todolist.toggleCompleted(0);
todolist.toggleCompleted(0);

### What did you expect to happen? 

After the first time running toggleCompleted(0), 'completed' should be fliped from false to true
After the second time running toggleCompleted(0), 'completed' should be fliped from true to false

### What actually happened? 

After the second time of running toggleCompleted(0), 'completed' remains 'true' and is not flipped to 'false'.

![image](https://user-images.githubusercontent.com/37119554/49113046-75b03880-f262-11e8-9a1e-2b0a96d633d6.png)

### Describe what you've done so far to troubleshoot the problem. 

- Added the prints in bold:
  toggleCompleted: function(position){
    var todo = this.todos[position];
    **console.log("todo ", todo);**
    todo.completed = !todo.compaleted;
    **console.log("todo.completed ", todo.completed);**
    this.displayTodos();
  }
looks like todo.completed remains as "true" after the second run of toggleCompleted

- Created fresh variables in the console, it works as expected 
![image](https://user-images.githubusercontent.com/37119554/49113093-98dae800-f262-11e8-8549-69a5dca2bb8a.png)

- I have rewritten the method as following using an additional variable and it works 

  toggleCompleted: function(position){
    var todo = this.todos[position];
    console.log("todo ", todo);
   var opposite= !(todo.completed);
   console.log(" opposite ",  opposite);
    todo.completed = opposite;
    this.displayTodos();
  }

![image](https://user-images.githubusercontent.com/37119554/49113073-8791db80-f262-11e8-9137-025d9e199182.png)

Can you please explain why I'm not able to make it work using the method you showed in the lesson? 

Thank you, 
Olga

**Comment by gordonmzhu** [comment]
Hey Olga. Please provide a URL to your Plunker project. It should have the form `http://plnkr.co/edit/<project-id>`.

**Comment by ogloz** [comment]
Hey Gordon,
Sorry about that - http://plnkr.co/edit/EkPQCJ63QhRyYu0mNzva?p=preview

**Comment by gordonmzhu** [comment]
You have a typo in your `toggleCompleted` method. Go through each line character-by-character to spot the issue, returning to the videos as-needed.

**Comment by ogloz** [comment]
oh no! my apologies, I'm really sorry I've wasted your time on this.
