### ISSUE TITLE
Plunkr 

### ISSUE THREAD

**Issue by questro** [gordonmzhu/questions#119]
https://watchandcode.com/courses/60264/lectures/936348

I just can't modify the object in the console screen while on plunkr.  Similar to other people who have posted on this issue, I get the following error message: 

**Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) @ VM7961:1**

I have also attached a screenshot. 

https://plnkr.co/edit/mFBFDA0h0pMXtMTP?p=info

I have Chrome and opened the Plunk to edit, then Inspect, console loads, then select Console view, then plunkrPreviewTarget (run.plnkr.co). From there, I try to modify the object with some code, or simply display todos with todoList.displayTodos() but I get the same error. 

![plunkr error](https://user-images.githubusercontent.com/45472283/49334969-ee333400-f597-11e8-8cce-067c38f81b0d.png)

This is the basic step to run and update the code, and I expected it to work, since in the Chrome console it works fine (meaning modifying the code when the object is already added to the console - before moving things over to plunkr). 

I also noticed that in the top pane, some resources were not loading properly: When I reload the page, I get this error in the console>top: 

**runtime.34ff8150983c47b66c38.js:1 GET https://run.plnkr.co/1e0yfSL6a3OQwFKa/jsconfig.json 404  **

I tried to run this in JSFiddle with the same error messages. 

I feel like the Plunkr application/resource is just not working, being blocked or failing to load.  I have the Disconnect extension and DuckDuckGo extensions installed on my Chrome browser, but I tried turning them off with no change in the error messages. 

Safari: my version of Safari and Firefox is too old to use either JS Fiddle or Plnkr/Github without updating the OS, which I don't want to do on this older machine.  JS Fiddle does not load properly to begin with - the run command button is missing!  I am currently using ElCapitan.

Hoping to use plunkr and resolve this issue. 

**Update**: as an experiment, I downloaded Sublime Text for Mac OSX (after googling JS editors), created a index.html and script.js files in a local folder, opened the index.html and inspected the page in Chrome console, and tried modifying the object with success. (I used to todoList.changeTodo(1, 'questro');  to change the second item in the array without any error messages).   So it works locally, but just not on JSFiddle or Plunkr.

**Comment by gordonmzhu** [comment]
If you try out this link it should work: https://plnkr.co/edit/mFBFDA0h0pMXtMTP.

I simplified the file paths, cleaned up your HTML file, and removed the package.json file.

**Comment by questro** [comment]
Thanks, but I don't really follow how you cleaned up the HTML file (looks unchanged to me - it was super simple already). Also, when I load that page from the link you provided, I still see the package.json file.   File paths are still /lib/script.js etc. Not sure how you can simplify them further?

And I still get the same errors on Plnkr. 

Again, this is weird because the original version (and I've since progress ahead to version 6 of your tutorial) works fine on my mac.

**Comment by gordonmzhu** [comment]
Oh my mistake. I forgot to save the changes. The updated Plunk is here. Let me know if this one works. 

https://plnkr.co/edit/TmPdmA2qw63ZAPFcGqEn?p=preview
