### ISSUE TITLE
Showing a reference error

### ISSUE THREAD

**Issue by christophersulayao** [gordonmzhu/questions#121]
### What is the associated Watch and Code lesson? https://watchandcode.com/courses/60264/lectures/946809 @ 4:20

**Write your response here (required).
todoList.addTodo('this is an object'); When I get to this part is shows this when I hit enter in the console. 
VM3148:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
var todoList = {
  todos: [],
  displayTodos: function() {
    console.log('My Todos', this.todos);
  },
  addTodo: function(todoText) {
    this.todos.push({
      todoText: todoText,
      completed: false
    });
    this.displayTodos();
  },
  changeTodo: function(position, newValue) {
      this.todos[position] = newValue;
      this.displayTodos();
  },
  deleteTodo: function(position) {
    this.todos.splice(position) {
    this.displayTodos();
  }
};

Here's the code i ran.** 

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You left 5/6 steps blank. Please open a new issue and fill out all the required fields.
