### ISSUE TITLE
Version 4: Booleans in the lesson titled " todoList.addTodo should add objects".

### ISSUE THREAD

**Issue by Akin80** [gordonmzhu/questions#122]
Hi,
I am currently at  Version 4: Booleans in the lesson titled " todoList.addTodo should add objects". The URL is:https://watchandcode.com/courses/practical-javascript/lectures/946809

I am attempting to add an item in my toDoList as shown on the video from timestamp 2.00 
When running the programme, I do not get an array of objects that can be inspected from a click down arrow. as seen from the video timestamp 4:05

What I have done so far is:
1- clear out the default items in the (todos array)
2 - add an object that is to be pushed into the list via the "addTodo function" within the "todoList object".
3- run : todoList.addTodo("Item 1");  on the console. What I get is: My todos: [object Object]

What am I missing? I've checked through for syntax errors etc and not seeing anything.

My code can be found here: https://plnkr.co/edit/TIuiXOkWiP8mONNXTrss?p=info

**Comment by gordonmzhu** [comment]
The two techniques handle strings differently. You will be better prepared to understand this later on in Premium. In the mean time, I recommend sticking with the code in the course if you want your application to work similarly.

**Comment by Akin80** [comment]
Thank you Gordon. I am extremely impressed and awed by how you are able to simplify coding. You are a God sent. I will definitely be enrolling on the Premium once done with the basic course. Thank you!!!
