### ISSUE TITLE
Version 9 about the precedence of the handlers and the view object

### ISSUE THREAD

**Issue by shawnipgithub** [gordonmzhu/questions#123]
### What is the associated Watch and Code lesson? Version 9 Escape from the console->escaping the console TimeStamp=>01:03

You created the view object after the handler section. You then put the view.displayTodos() function at the end of every handler. The question is how would each handler know what object view is as it comes after the handler section?

**Comment by gordonmzhu** [comment]
Think about the timing of when `view.displayTodos()` is run. When you research that you'll find your answer.
