### ISSUE TITLE
A question regarding loops in practical javascript course

### ISSUE THREAD

**Issue by xenophanes90** [gordonmzhu/questions#124]
Version 5 - Loops of logic - displayTodos should show .todoText 

Here is the code, I've been following it carefully (or so I thought!) 

var todoList = {

todos: [],
displayTodos: function(){

console.log("My todos:");

for (i = 0; i<this.todos.length; i++ ){
  
  console.log(todos[i].todoText);
  
}

},

addTodo: function(todoText){
  
  this.todos.push({
    
    todoText: todoText,
    completed: false
    
  });
  this.displayTodos();
  
},

changeTodo: function(position, todoText){
  
  this.todos[position].todoText;
  this.displayTodos();
  
},

deleteTodo: function(position){
  
  this.todos.splice(position, 1)
  this.display.Todos();
},

toggleCompleted: function(position){
  
  var todo = this.todos[position];
  todo.completed = !todo.completed;
  this.display.Todos();
   
}
};

But whenever I try to add a todo by going todoList.addTodo("item 1")
 I get - My todos: debugger eval code:7:1
ReferenceError: todos is not defined[Learn More]

Could you tell me what I've done wrong please? 

Thank you, and love the course!

Mel

**Comment by pragun1993** [comment]
I checked your code. The problem lies in the `displayTodod()` function. Have a look at the the following line:
`console.log(todos[i].todoText);`
You have missed **`this`** . It should be:
`console.log(this.todos[i].todoText);`
