### ISSUE TITLE
Recovering functions in Console

### ISSUE THREAD

**Issue by Asmi131** [gordonmzhu/questions#125]
### What is the associated Watch and Code lesson? 

Write your response here (required). https://watchandcode.com/courses/60264/lectures/928391

### Include a live demo link so that I can run your code. 

Write your response here (required). Don't need it

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required). Just have the Google Chrome console open

### What did you expect to happen?  

Write your response here (required). I expected that after closing the browser, when I came back my functions etc. would remain 'active' (is that the right word?) and I wouldn't need to enter them again.

### What actually happened? 

Write your response here (required). When I closed the browser and reopened it, I had to recreate my various functions (e.g. addTodo, changeTodo etc.)

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required). I'd just like to know if and how you can make Chrome console remember your functions so I don't have to completely recreate our Todo app every time I come back!

Thanks :)

**Comment by gordonmzhu** [comment]
You can't save things in the console, but you will learn a different way to save your code later on in the course.
