### ISSUE TITLE
Square Bracket vs Paranthesis

### ISSUE THREAD

**Issue by jpmiller6** [gordonmzhu/questions#126]
Why is square brackets used in one instance of code and parenthesis in another?

Parenthesis are used in the function addTodo
   addTodo: function(todo) {
       this.todos.**push(todo)**;
       this.displayTodos();

Square brackets are used in the function changeTodo
    changeTodo: function(position, newValue) {
       this.todos[position] = newValue;
       this.displayTodos();

Parenthesis are used in the function deleteTodo
  deleteTodo: function(position) {
      this.todos.**splice(position, 1)**;
      this.displayTodos();

**Comment by hydroweaver** [comment]
square brackets are for arrays and referring to their indices, while parentheses are used by function to take arguments

**Comment by gordonmzhu** [comment]
Thanks for helping out @hydroweaver! Appreciate it.
