### ISSUE TITLE
Help deploying todo list on personal website

### ISSUE THREAD

**Issue by meghanduprey** [gordonmzhu/questions#128]
### What is the associated Watch and Code lesson? 

I completed the entire series, and am attempting to take the code we wrote and put it on my website on my projects page. It works perfectly in the glitch setup, I copied and pasted everything directly into my projects page, linked the javascript file using a <script src=""> tag to the correct file which I copied and pasted into my scripts folder. But when I click "add" nothing shows up.  

### Include a live demo link so that I can run your code. 

Write your response here (required).
https://github.com/meghanduprey/meghanduprey.github.io/blob/master/projects.html
https://www.meghanduprey.com/projects

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
It is not working in Chrome or FIrefox. Nothing shows up when you add a new todo.

### What did you expect to happen? 

Write your response here (required).
I expected it to work as it did in Glitch, but nothing is happening. 
### What actually happened? 

Write your response here (required).
Nothing happens. 
### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I tried adding a debugger to the addTodo handler, but it's not working - nothing is showing up in the console. I'm not sure where else I should put the debugger, it seems like the Javascript is not being seen, but I'm not sure why.

**Comment by gordonmzhu** [comment]
Hey Meghan I suggest linking to the live demo provided by Glitch. Because of limited time, I only on issues directly related to course material. Helping with personal websites is outside of that focus.

**Comment by meghanduprey** [comment]
I totally understand! I figured out that I could embed the Glitch project
and it works perfectly, thanks for getting back to me!
Meghan
