### ISSUE TITLE
var todo = this.todos[position];

### ISSUE THREAD

**Issue by bulatmansurov** [gordonmzhu/questions#132]
Hello Gordon!
Thank you for very nice course!
Please excuse my bad english, I am not a native speaker. 

Practical JavaScript
Version 4 - Booleans
todoList.toggleCompleted should flip the completed property
https://watchandcode.com/courses/60264/lectures/946811.
time: 2:50

    toggleCompleted: function(position){
        //this.todos[position].completed = !false;
        var todo = this.todos[position];
        todo.completed = !todo.completed;
        this.displayTodos();
    },

You have created a new variable 'todo' inside this function and you refer it to an object in the array 'todos'.
Could you please explain how the variable 'todo' can pass the value back to the object?
I don't understand the logic of this manipulation.

**Comment by bulatmansurov** [comment]
Got my question answered. 
Answer is in your lecture.
Interlude - Data types and comparisons ->  Code example 4

**Comment by gordonmzhu** [comment]
@bulatmansurov That's great. Thanks for updating and Happy New Year!
