### ISSUE TITLE
Toggle todo function isn't working

### ISSUE THREAD

**Issue by rookdev91** [gordonmzhu/questions#139]
Here's my code: 

```
var todoList = {
  todos : [],
  displayTodos: function(){
  if (this.todos.length === 0){
    console.log('Todos list is empty');
    }
  else{
    console.log('My todos');
    for (var i = 0; i<= this.todos.length; i++){
      if (this.todos.completed === true){
        console.log('( )', this.todos[i].todoText);
      }
      else{
        console.log('(x)', this.todos[i].todoText);
      }
      }
    }
  },
  addTodos: function(todoText){
    this.todos.push({
      todoText: todoText,
      completed: false
    });
    this.displayTodos();
  },
  changeTodo: function(position, todoText){
    this.todos[position].todoText = todoText,
    this.displayTodos();
  },
  toggleTodo: function(position){
    var todo = this.todos[position];
    todo.completed = !todo.completed;
    this.displayTodos();
  },
  deleteTodo: function(position){
    this.todos.splice(position, 1);
    this.displayTodos(); 
  }
}

```
Write your response here (required).

todoList.addTodos('first');
script.js:30                 My todos
script.js:36                 (x) first
**script.js:36 Uncaught TypeError: Cannot read property 'todoText' of undefined
    at Object.displayTodos (VM2526 script.js:36)
    at Object.addTodos (VM2526 script.js:46)
    at <anonymous>:1:10**
displayTodos @ script.js:36
addTodos @ script.js:46
(anonymous) @ VM2689:1
todoList.toggleTodo(0);
script.js:30             My todos
script.js:36              (x) first
script.js:36 Uncaught TypeError: Cannot read property 'todoText' of undefined
    at Object.displayTodos (VM2526 script.js:36)
    at Object.toggleTodo (VM2526 script.js:55)
    at <anonymous>:1:10

Ideally it should toggle from boolean 'false' to 'true', but it doesn't.
But toggleTodo is giving back me the same boolean.

**Comment by hydroweaver** [comment]
Your line here 

      if (this.todos.completed === true){


has 2 errors:

1. it should be todos[i]
2. it should be === false

Can you try now?

**Comment by rookdev91** [comment]
@hydroweaver  Thanks!
