### ISSUE TITLE
Debugger does not preview value for i without hovering over

### ISSUE THREAD

**Issue by calebbf** [gordonmzhu/questions#141]
From [todoList.addTodo](https://watchandcode.com/courses/60264/lectures/997382) ~2:30 onwards

The video shows a preview to the right of the code where the highlighted box of text "i = undefined" appears. This preview then dynamically shows the value of i as you step through with the debugger, so you can see when it changes to 1, etc. 

However, when I run the debugger, I do not see that preview text at all. I am able to see the value of i if I hover over the text, but this is slower than just seeing it instantly. 

This is likely a settings issue and not a code issue, but here is an [example Plunk](http://plnkr.co/edit/N02XkMONOSoCX42pNKRN) where I do not see the debugger as shown in the video. 

I follow the steps, debugging the addTodo, following to displayTodos - at this point, my screen does not show the information as shown in the video. 

I am missing the preview text, and instead have to hover over i to see its value as it changes. 
![plunker debugger with no i preview](https://user-images.githubusercontent.com/27244919/50715474-684d5180-104b-11e9-8073-a84b0322cecd.png)

Some initial Googling lead me to believe it may be that I had to enable the "Display variable values inline while debugging" setting, but when I looked, it was already checked - so that wasn't it. 

I also checked to see if I'm using the latest version of Chrome, which I am. 

Not sure what else to look for, and am hoping this is just one of those quick settings questions... thanks for your help!

**Comment by gordonmzhu** [comment]
Chrome may have changed recently. You can find the values instead by looking in the "Scope" section in the right side of the debugger. It's right below the "Call Stack" section.
