### ISSUE TITLE
V11 - Destroy all for loops - displayTodos

### ISSUE THREAD

**Issue by logictom** [gordonmzhu/questions#142]
So for eliminating the for loop in displayTodos I thought I would give it a go before you revealed how to do it.
I came up with the following forEach:
```
    todoList.todos.forEach(function(todo) {
      var todoLi = document.createElement("li");
      var todoTextWithCompletion = "";

      if (todo.completed === true) {
        todoTextWithCompletion = "(X) " + todo.todoText;
      } else {
        todoTextWithCompletion = "( ) " + todo.todoText;
      }

      todoLi.id = todo.position;                        //<<< This one
      todoLi.innerText = todoTextWithCompletion;
      todoLi.appendChild(view.createDeleteButton());    //<<< And this one
      todosUl.appendChild(todoLi);
    });
```
I've put a comment to the two lines that differ.
This worked but is different to your solution and I would like to understand what the implications are of one vs the other, if any.

First; I found that the array element had a position through the debugger, why does the forEach provide a way to specify the position if the data is already available from the array itself? Are there any draw backs of either method?

Second; I replaced this.createDeleteButton with view.createDeleteButton.
I see the downside of this being that if I rename the view object I have to rename this (but with modern tools and the fact you would have to rename it anywhere else it was used) but are there any other reasons not to call it this way or is it just considered best practice to use this. instead?

**Comment by gordonmzhu** [comment]
@logictom Please provide a live demo of your app as described in the issue template.

**Comment by logictom** [comment]
@gordonmzhu I've coped code into plunker: http://plnkr.co/edit/NgrE91

**Comment by gordonmzhu** [comment]
Your code isn't working.

If you add three items and click delete on the middle one. 

- First 
- Second
- Third

You should get

- First
- Third

But in your app, you get 

- second
- third

I would go back to make sure your code works. You have a built-in assumption that your code is the same but it is clearly not.

**Comment by logictom** [comment]
Thanks Gordon, yeah my testing failed to show that issue.
My second question still stands, are you able to address that?
Thanks.

**Comment by gordonmzhu** [comment]
What do you mean by "why does the forEach provide a way to specify the position if the data is already available from the array itself?" Can you elaborate?

`this.createDeleteButton` and `view.createDeleteButton` are technically equivalent. So it doesn't matter which you use. It could be argued the using `view` is clearer to humans, but to the computer it's all the same.

**Comment by logictom** [comment]
The first question, that was where my error crept in, I thought that I could access the array position but I cannot, I have to use it as a parameter to the forEach.

Thanks, I'll mark as closed now.
