### ISSUE TITLE
Plnkr problem

### ISSUE THREAD

**Issue by jvgonzalez** [gordonmzhu/questions#143]
https://watchandcode.com/courses/60264/lectures/936334 Minute 2:20

I am not able to see plunkerpreviewtarget, it worked for me the first time around but the second time this is the only thing I see (attached screenshot)

### Explain the exact steps I need to take to replicate the problem. 

I did exactly as explained on the video, cleared the console, and the screenshot is what I see when I click the dropdown arrow.

### What did you expect to happen? 
I expected to see plunkerpreviewtarget

### What actually happened? 
No plunkerpreview target

### Describe what you've done so far to troubleshoot the problem. 
I tried a different browser, and tried closing and opening plnkr again.
<img width="1253" alt="screen shot 2019-01-05 at 12 54 14 pm" src="https://user-images.githubusercontent.com/45739395/50727449-10fdbe80-10e9-11e9-9fa4-5bbb70f8891e.png">
<img width="1253" alt="screen shot 2019-01-05 at 12 54 14 pm" src="https://user-images.githubusercontent.com/45739395/50727453-1e1aad80-10e9-11e9-88f4-16f601f2fb01.png">

**Comment by gordonmzhu** [comment]
You have to hit play. If you watch the videos carefully you will see this.
