### ISSUE TITLE
It Should Store The Todos Array On An Object

### ISSUE THREAD

**Issue by gajano** [gordonmzhu/questions#145]
Hi Gordon,

I'm on Version 3 of the Practical Javascript free version"It Should Store The Todos Array On An Object" video.  

At 3:07 you press enter and the Object on the console file shows up, but every time  I do it, it comes out as {todos: Array[3]} without the word "Object" in front.  I copied everything you did step by step I thought, and I've tried 5 times with the same outcome.  

Also, when I go to the inspect view, it takes up the whole screen, so I cannot view my code at the top like your lesson shows, I'm not sure why.

Here is my link: https://plnkr.co/edit/KkBXfCD6qNPG7cU69ygj?p=preview  

I hope this is helpful describing my issue.

Thanks,
Alberto

**Comment by gordonmzhu** [comment]
Please provide screenshots that illustrate the behavior you're seeing.

**Comment by gajano** [comment]
I figured it out sorry about that, thanks.

**Comment by gordonmzhu** [comment]
Cool, thanks for letting me know and glad you were able to figure it out.
