### ISSUE TITLE
Cannot focus() the input.edit within the Todo list.

### ISSUE THREAD

**Issue by raphael-peters** [gordonmzhu/questions#149]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/77710/lectures/3024569

Digestion techniques. Changing jQuery to JS.

### Include a live demo link so that I can run your code. 

https://telling-lasagna.glitch.me/#/all

### Explain the exact steps I need to take to replicate the problem. 

Double click to edit the todo to run the debugger, works fine until the debugger gets to the .focus() method. Then it throws an error telling me that .focus() is not a function. I checked online, and it seems it is in fact a HTML DOM method that can be used.

### What did you expect to happen? 

Expected the cursor to focus into the todo like in the original jQuery TodoMVC.

### What actually happened? 

Uncaught TypeError: todoInputElement.focus is not a function
    at Object.edit (app.js:166)
    at HTMLUListElement.dispatch (jquery-2.2.4.js:4737)
    at HTMLUListElement.elemData.handle (jquery-2.2.4.js:4549)

### Describe what you've done so far to troubleshoot the problem. 

Used the debugger extensively. Asked for help in the slack #questions channel. Searched the MDN web docs & w3schools information. Tried setTimeout as some people said maybe the DOM hasn’t loaded for the input to be focused.
Changed how the code is retrieving the ‘.edit’ class. Rewatched how you described the ‘.edit’ method to ensure I am asking the code to do something similar.

**Comment by raphael-peters** [comment]
In the debugger it appears as a NodeList. Upon research, it seems like that is considered an array-like list. So it is not a DOM element.
I've had some help in the #questions channel and I've been told I need to add [0] to access the input.edit element. Not sure why. I thought that accessed the index...
After typing this (gonna leave that in there) debugged and saw that the NodeList has 0: input.edit... So I guess that is why putting [0] after edit is letting me access the input.edit

Feel really stupid now. Guess this should have been easier than I found it..

**Comment by gordonmzhu** [comment]
👍
