### ISSUE TITLE
Hey Gordon! Function undefined help.

### ISSUE THREAD

**Issue by extrashrimp** [gordonmzhu/questions#150]
### this is in regards to watch and code lesson  displayTodos should show .todoText
https://watchandcode.com/courses/60264/lectures/956106

I have been trying to figure out why, when i un comment the rest of my functions(like addTodo). The todoList var becomes undefined.  

 this is my plunker project http://plnkr.co/edit/lQR4L6CHFicMvlSMoxJf?p=preview
code starts at line 27

I've tried everything that i could think of but not sure why it keeps coming up as undefined.
when i run the code with only lines 27 - 34 it works. but when i start to uncomment the addTodo or anything else the todoList becomes undefined

if you have a second to take a look i would greatly appreciate any help.
THANK YOU GORDON!!!!!!!!!

**Comment by gordonmzhu** [comment]
I need to be able to replicate the issue in order to help. Please share a Plunker link that has the code uncommented in the way you are describing.

**Comment by extrashrimp** [comment]
Thank you for your patience ,, im a super noob.
this is me uncommenting the addTodo Function. which gives me the error todoList undefined.
i get the same result no matter if i change line 41 to semicolon or comma or just brackets 
http://plnkr.co/edit/lQR4L6CHFicMvlSMoxJf?p=preview
Thank you Gordon!

**Comment by extrashrimp** [comment]
kallekall ,thank you ! I will take another look. I greatly appreciate your help!

**Comment by gordonmzhu** [comment]
Thanks for helping out @kallekall. Yep there are definitely typos there. 

@extrashrimp Please carefully go through your code with character-by-character precision and you should find all the issues. If not, feel free to open another issue.

Thanks! @kallekall @extrashrimp!
