### ISSUE TITLE
Version 4 Booleans Help

### ISSUE THREAD

**Issue by gajano** [gordonmzhu/questions#151]
Hey Gordon,

I'm on "Version 4 Booleans in the todoList.toggleCompleted should flip the completed property" video.  I followed everything and tried todoList.addTodo('boolean testing') like you did at 4:25 in the video, but it comes back as saying todoList is not defined.  I thought I had the same code as you did in the video, but I cannot find exactly where I messed it up for it to give me that error.  I'm not sure what "at <anonymous>:1:1" means.

<img width="889" alt="screen shot 2019-01-08 at 9 26 09 pm" src="https://user-images.githubusercontent.com/42163124/50872393-825d9b80-138d-11e9-97af-1d94cf3f5832.png">
<img width="339" alt="screen shot 2019-01-08 at 9 26 45 pm" src="https://user-images.githubusercontent.com/42163124/50872399-8d183080-138d-11e9-9e4a-deae701ab54f.png">

Thanks!
Alberto

**Comment by gajano** [comment]
<anonymous>1:1** idk how that got changed hah sorry

**Comment by gajano** [comment]
<ano nym ous >:1:1...  Third time's a charm hopefully.  It's not letting me write it but hopefully you know what I mean.

**Comment by kallekall** [comment]
https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603

Check headline 7. You have typos.

**Comment by gordonmzhu** [comment]
Hey @gajano. In order for me to help, please open a new issue and fill out all the required fields in the issue. For example, I can't reproduce the problem without a link to your Plunker. That's the whole reason we have the template.

**Comment by gordonmzhu** [comment]
@gajano Here's a direct link to the issue form. Fill out all the fields and I'll be happy to take a look after. https://github.com/gordonmzhu/questions/issues/new?template=Custom.md

**Comment by gordonmzhu** [comment]
It's explained in https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603.

**Comment by gajano** [comment]
Thanks
