### ISSUE TITLE
Version 8 Setting Text Box to empty string

### ISSUE THREAD

**Issue by kallekall** [gordonmzhu/questions#152]
Hi Gordon, I have a short theoretical question I hope you could answer for me.

Six minutes into the lecture of [Version 8 Getting Data from Input: There should be a button for adding todos (7:51)](https://watchandcode.com/courses/60264/lectures/1027554) you say that you want to clear the input box after the input has been done. You then go ahead and write:
`addTodoTextInput.value = "";`

My question is, why did you not set the value to `null` instead?
`addTodoTextInput.value = null;`

I tried and did not accounter any errors that I could notice.

[Here is a link to my code](http://plnkr.co/edit/a61sXUE4fMrGzc3L2Ci8?p=preview). The code can be found at row 65.

**Comment by gordonmzhu** [comment]
Input values are strings so resetting to a blank string `''` makes more sense. Perhaps other things like `null` work too, but it seems less logically consistent.
