### ISSUE TITLE
Missing subtitles

### ISSUE THREAD

**Issue by kallekall** [gordonmzhu/questions#154]
Hi Gordon!

I have really appreciated the English subtitles since it makes the videos very easy to follow. Especially for non-native English speakers and viewers who are hearing impaired or for other reasons can not hear the sound.  I found a video without subtitles. (I have no sound but I assume that you speak during the video.) I was able to follow what the function `setTimeout` do anyway, but I feel I miss your good explanations.

### What is the associated Watch and Code lesson? 

Interlude - Functions inside of functions:  setTimeout
https://watchandcode.com/courses/60264/lectures/1125976

### Include a live demo link so that I can run your code. 

Not a coding problem. -> No code to supply.

### Explain the exact steps I need to take to replicate the problem. 

Pressed the subtitle icon on the video player.

![missingsubtitle](https://user-images.githubusercontent.com/328229/50948280-41789a80-14e5-11e9-955a-f8024125b2a5.png)

### What did you expect to happen? 

Expected to be able to select English subtitles.

![englishsubtitle](https://user-images.githubusercontent.com/328229/50948424-ca8fd180-14e5-11e9-9c88-91d8c60eb54c.png)

### What actually happened? 

There are no subtitles to select.

I have checked all other lessons, but this is the only lesson/video without subtitles.

### Describe what you've done so far to troubleshoot the problem. 

Tried to select subtitles after starting the video, but there are no differences.

**Comment by gordonmzhu** [comment]
@kallekall Weird! Thanks for pointing that out. Should be fixed now!
