### ISSUE TITLE
First Refactoring?

### ISSUE THREAD

**Issue by ivangrozni14** [gordonmzhu/questions#155]
In first refactoring lesson (https://watchandcode.com/courses/60264/lectures/1027547), you create new object called handlers and in that object you put methods displayTodos and toggleAll. And then you call that object and those methods in HTML. I understand all of that, but why we create new methods and new object when we allready have those methods in object todoList. Why we do not use that?

 <button onclick="todoList.displayTodos()">Display Todos</button>
 <button onclick="todoList.toggleAll()">Toggle All</button>

Can we use this above? If not, why not? Isn't this even more refactoring code? Sorry, maybe I do not see point of making new object handlers and give to him same methods that we allready have in another object?

Thanks in advance

**Comment by gordonmzhu** [comment]
Hey thanks for you question @ivangrozni14. I answered this exact question in a separate issue. See https://github.com/gordonmzhu/questions/issues/97.
