### ISSUE TITLE
Big picture

### ISSUE THREAD

**Issue by mhawad** [gordonmzhu/questions#156]
### What is the associated Watch and Code lesson?  

 It should have a function to display todos
Write your response here (required).

I feel like I'm just following directions, but I don't get the big picture. I don't understand what this steps are gonna lead to?. Help please

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
The picture will start to emerge as you keep going. Stick with it and reflect at regular intervals and the details will start to fill in.
