### ISSUE TITLE
Plnkr doesn't work (and I have clicked run/play)

### ISSUE THREAD

**Issue by leong56** [gordonmzhu/questions#157]
### What is the associated Watch and Code lesson? 

Lesson name: "It should store the todos array on an object". Around 2:42 where you use inspect element. https://watchandcode.com/courses/60264/lectures/900211 

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/F2X9a28VkKtHIcWw?p=preview

### Explain the exact steps I need to take to replicate the problem. 

1. I press the black play/run button.
2. In the pane with the code, I right-clicked and then clicked inspect element. I'm on Chrome.
3. Under Console, I change the "top" to "plunkerPreviewTarget (run.plnkr.co/)" as stated in the video.
4. I type "todoList" and hit enter in the console.

### What did you expect to happen? 

I expected todoList to return the object todoList because it's what happened in your video.

### What actually happened? 

I get "Uncaught ReferenceError: todoList is not defined at <anonymous>:1:1".

### Describe what you've done so far to troubleshoot the problem. 

I used Safari. Still doesn't work. I've also searched other questions similar problem, but everyone else seems to have forgotten to click "run/play" which I didn't forget so I'm not sure what's happening.

**Comment by kallekall** [comment]
I had a similar problem. I think Plunker is having problems right now.

You could try to use Glitch instead. Gordon introduces it in version10.

https://watchandcode.com/courses/60264/lectures/1099227

**Comment by gordonmzhu** [comment]
If you use the exact same file structure that I do in the videos, and delete the .json file, it'll work. For example, instead of `lib/script.js`, name the file `script.js`. You'll have to change the `script` tag in your index.html to match as well. I did this for you in this Plunk: https://plnkr.co/edit/OgbyU8G11NLVlZyML3vT?p=info.
