### ISSUE TITLE
Question regarding adding a onkeypress event.

### ISSUE THREAD

**Issue by kolsen86** [gordonmzhu/questions#158]
Hi Gordon,
I am not having any issues with any of your lessons, and it has definitely been a great course thus far.
My question is about adding an "onkeypress" event to the addTodos function.  I was just trying to add some extra stuff on my own and I can't figure out how to add the code to the existing code.  I have attempted to add another similar function to the addTodos function while adding in an if statement and I have not been able to figure it out.  Any help would be greatly appreciated.  

Also, Keep up the great work!  The way you structured your course has made it much easier for me to understand and retain the lessons you are teaching better than most other lessons, so Thank You!

**Comment by gordonmzhu** [comment]
Hey @kolsen86. This type of question is a bit more expansive and would be better answered in office hours, where we can discuss in real-time. Today's session is coming up at 6PM PST and the schedule is posted on the Facebook group. Hope to see you there if you can make it.
