### ISSUE TITLE
no preview dropdown

### ISSUE THREAD

**Issue by Moonshine6475** [gordonmzhu/questions#159]
### What is the associated Watch and Code lesson? https://watchandcode.com/courses/60264/lectures/936334 

   It should have a displayTodos method
at 2:04,

### Include a live demo link so that I can run your code. https://next.plnkr.co/edit/1aRnW46TXBrBcKuB?preview

you can't use inspect console because the dropdown doesn't work. 

### Explain the exact steps I need to take to replicate the problem. 

inspect, and go to the dropdown
click preview
then run the code
it doesnt work

### What did you expect to happen? 

I expected there to be a plunkerpreview target

### What actually happened? 

[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
c07b4fa731e3f57785e2.js:42 [Violation] 'setTimeout' handler took 457ms
c07b4fa731e3f57785e2.js:42 [Violation] 'setTimeout' handler took 55ms
todolist
VM4324:1 Uncaught ReferenceError: todolist is not defined
    at <anonymous>:1:1
(anonymous) @ VM4324:1
todoList
VM4357:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) @ VM4357:1
c07b4fa731e3f57785e2.js:42 [Violation] 'setTimeout' handler took 80ms
[Violation] Forced reflow while executing JavaScript took 42ms
todolist
VM6745:1 Uncaught ReferenceError: todolist is not defined
    at <anonymous>:1:1

### Describe what you've done so far to troubleshoot the problem. 

tried to use full size
didn't work

**Comment by gordonmzhu** [comment]
Hey @Moonshine6475. Use the stable version of Plunker (the one that looks exactly like my screen. next.plnkr.co doesn't quite work. If that doesn't work, you can move to something else as detailed here: https://github.com/gordonmzhu/questions/issues/1.

Thanks and good luck!
