### ISSUE TITLE
change todo list

### ISSUE THREAD

**Issue by SMAmmar** [gordonmzhu/questions#16]
https://watchandcode.com/courses/60264/lectures/942296### 

Write your response here (required).
Actually, I wanted to ask where would the updated array from todosList.addtodo went when we called the changed todo method shouldn't the array in change todo be updated to 4 values instead of 3

**Comment by gordonmzhu** [comment]
Can you provide more context? I don't follow. Is there a specific timestamp in the video you're referring to?

Please include all the fields from https://github.com/gordonmzhu/questions/issues/new?template=Custom.md if you'd like help. See https://github.com/gordonmzhu/questions/issues/1 for an example of a well-formed question.

Once you update this issue with the additional information, re-open it and I'll take a look. Thanks!
