### ISSUE TITLE
It should have a function to add new todos

### ISSUE THREAD

**Issue by mhawad** [gordonmzhu/questions#160]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
What is the URL for the associated lesson?

**Comment by gordonmzhu** [comment]
Closing issue since there hasn't been a reply for 7 days.
