### ISSUE TITLE
Debugger doesn't work in Glitch, unable to debug issue with test function

### ISSUE THREAD

**Issue by CharlesStreamMe** [gordonmzhu/questions#165]
### What is the associated Watch and Code lesson?  

Practical JS (https://watchandcode.com/courses/60264/lectures/1099227)

### Include a live demo link so that I can run your code.  

https://calico-bathtub.glitch.me/

### Explain the exact steps I need to take to replicate the problem. 

1) Click -> Add Test Data
2) Click -> Remove Test Data

### What did you expect to happen? 

I expected all test data to be removed when the button is clicked.

### What actually happened? 

A seemingly random number of items from the todoList.todo array is removed, instead of all of them.

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
Here is my function:

```javascript
  removeStuff: function() {
    debugger; // This does not trigger the debugger.
    todoList.todo.forEach(function(name, index) {
      debugger; // This does not trigger the debugger.
      //console.log(index); // Correctly returns the index of all items in the array.
      //todoList.todo.splice(0, 1); // Results = A few random index entries are removed.
      todoList.todo.splice(index, 1); // Results = A few random index entries are removed.
      //todoList.todo.splice(index, 100); // Results = This works, but it is not the solution I am looking for.
    })
    view.displayTodos();
  },
```

So, I tried to use the debugger. But in glitch, the debugger never fires. No matter where I put it in the script file, the debugger does not trigger. This is part of the problem I've had in figuring out what is wrong.

Without the debugger, I've tried console logging the index, which worked just fine.
I tried changing the values I send to todoList.todo.splice, by always sending it 0, 1, or sending it the index from the array.

The only thing that I've done that actually made this work, was to just set the values for splice to (0, 100) and not try and use any looping at all.

I wanted to try and use the forEach loop to try and practice. but I can't figure out why this doesn't work.

EDIT: Stupidly enough, the debugger WILL trigger, but only if my method is empty. /sigh
Meaning if I comment out all of the code inside the function, the debugger will trigger. If I add any functional code at all to the function, the debugger will no longer run.

**Comment by CharlesStreamMe** [comment]
P.S. code formatting in this is awful. lol

**Comment by gordonmzhu** [comment]
Thanks for the well structured question @CharlesStreamMe. 

I wasn't able to replicate the issue. I added three items and then clicked "Remove test data" and the debugger fired as expected. See screenshot.

<img width="1280" alt="screen shot 2019-01-17 at 10 46 27 am" src="https://user-images.githubusercontent.com/734575/51309693-45f10600-1a45-11e9-9552-aeb287ba3d31.png">

Can you try this again in a clean extension-free incognito Chrome window? I wonder if one your extensions is causing issues. Let me know if that resolves things and if not, please comment and I'll reopen the issue.

**Comment by CharlesStreamMe** [comment]
I was able to get the debugger to start. The problem was that unless I have the developer console already open, the debugger does not trigger. This explains why it seemed to trigger sometimes, but not others.

In any case, after watching the debugger, I am still confused as to what is happening. It is my understanding that forEach will cycle through each index of the array, 0 -> whatever until it reaches the end, and then it will break out of the loop.

This is not what is occurring in my code:

```javascript
  removeItems: function() {
    todoList.todo.forEach(function() {
      debugger;
      todoList.todo.splice(0, 1);
    })
    view.displayTodos();
  },
```

When run, it runs through index 0 -> 4, then breaks out, even though my array has 10 values stored.
I watch the index start at 0, then go to 1, 2, 3, then 4, then it breaks out of the forEach function.

What makes this even more confusing for me, is that when I simply console.log(index), it will loop correctly and log out all 10 values stored in the array.

**Comment by CharlesStreamMe** [comment]
After sitting with this for a while. I've determined what is going on.
forEach is re-evaluating the length of the array on each run of the loop.
So eventually, the index for the loop is at 4, and the new length of the array at that point is also 4, so it bails out, instead of continuing all the way through the original total length of indexes.

I suppose forEach is not the correct way to go about splicing items, but I'm sure there is a clever way to go about it.
