### ISSUE TITLE
Version 6: defining i in for loops in toggleAll function causes error symbols 

### ISSUE THREAD

**Issue by butrfly7624** [gordonmzhu/questions#169]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/936343

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/iMczxj

### Explain the exact steps I need to take to replicate the problem. 

I followed the video steps exactly as you did them. I even rechecked my code against yours and it looks the same.

### What did you expect to happen? 

I expected that the code would allow the completed symbol (x) to appear for all the uncompleted todos if they weren't labeled as completed yet and to remove all of the completed symbols if all of the todos were already labeled as completed.

### What actually happened? 

The code worked fine and did what was expected (as above). 
The issue is that there are 2 yellow triangle error symbols to the left of lines 47 and 51 in my plunk that state that i is already defined. I just want to understand why it finds this to be an error. For loops generally have var i = 0 as part of the process of going through the loop so they should be there. 

### Describe what you've done so far to troubleshoot the problem. 

The debugger doesn't pay attention to these triangles and as I said the code works as it should. It doesn't see them as errors. I checked your video but it doesn't show these error triangles either.

**Comment by gordonmzhu** [comment]
You can safely ignore the triangles. They are not errors. Errors will prevent your code from running. Rather, these triangles are warnings. If you'd like to get rid of them, choose a different variable for the loop in line 51 (e.g. use `j` instead of `i`) and the warning will go away. It will make no difference to the computer though.
