### ISSUE TITLE
no text next to the bullets

### ISSUE THREAD

**Issue by Cheery-Boga** [gordonmzhu/questions#17]
### What is the associated Watch and Code lesson?    

Write your response here (required).   https://watchandcode.com/courses/60264/lectures/1056226

### Include a live demo link so that I can run your code. 

Write your response here (required).   https://plnkr.co/04wAyW

### Explain the exact steps I need to take to replicate the problem. 

I followed your lesson plan and  I'm still unable to show the todoList.Text next to the bullet point. 

### What did you expect to happen? 

Write your response here (required). I expected to see the todoText of each object from the todo's array.

### What actually happened? 

Write your response here (required).  Nothing happened. The bullet shows up for li, but without text.

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required). I checked for spelling errors.

**Comment by gordonmzhu** [comment]
Closing this issue since we talked about it in office hours today.

**Comment by watchandcode** [comment]
Test
