### ISSUE TITLE
plunkerPreviewTarget Problem

### ISSUE THREAD

**Issue by JohnnyJongYi** [gordonmzhu/questions#171]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/900211. Time: 3.05. I got stuck at the point where inspecting my Plunker codes then clicking on plunkerPreviewTarget, but the object is not defined. I was using the same code as the video.

### Include a live demo link so that I can run your code. 

This is the URL to the code:
http://plnkr.co/edit/AkPs5NT1JsWvA3GQvpK6?p=info

### Explain the exact steps I need to take to replicate the problem. 

So I tried to write my own code from the requirements, which did not work. I then created a new version with the exact same code from the video mentioned above, which still did not work. I did everything from clicking run, then selecting plunkerPreviewTarget from the dropdown menu in Console.
The object simply was not defined yet, with the Error Message:
Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) 

### What did you expect to happen? 

I expected the object to be defined, as I already worked with it in Console in a simple Chrome window, and it works by inspecting Chrome and pasting the code in the console. It simply doesn't work with Plunker.

### What actually happened? 

As mentioned, the error message is Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) 

### Describe what you've done so far to troubleshoot the problem. 

I tried to put in the code into a simple Chrome tab console and the code works fine. I still am unsure how Plunker works, or was it updated.

**Comment by gordonmzhu** [comment]
Your index.html is blank. It needs to have content like mine does in the videos.
