### ISSUE TITLE
console unable to access plunker codes

### ISSUE THREAD

**Issue by shellhatcher** [gordonmzhu/questions#172]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/1027547

Write your response here (required).
Version 8, our first refactoring

Actually I already had the problem of unable to access plunkr from web console from the earliest lesson however, I kept on going by writing the code directly on console, until it came the period when I need to connect html codes and js codes, here I have no longer ability to write both html and js codes in the console. So I tried multiple times with no avail to use plunker and access it through console. It gave :
todoList undefined all the times I tried to call the method using: todoList.displayTodos();

### Include a live demo link so that I can run your code. 

Write your response here (required).
https://plnkr.co/edit/FAkV8XUoaCqdUD6WdY2P?p=info
### Explain the exact steps I need to take to replicate the problem. 
Not working in both chrome and firefox

1. After I wrote new lines of codes in plunkr I ensure to hit the save button
2. I hit Run button
3. I opened the console and chose for plunker preview target
4. I wrote todoList.displayTodos(); and got the following message
VM406:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
But if I just pasted the codes on the console, I got everything working just fine-using firefox, but doesn't work in chrome since the console.log function somehow doesn't work on my pc 
5.Tried to click the buttons and nothing seen on the console
6. I tried using firefox and it gave the same result, nothing happened at the console when I clicked the buttons
7. I tried to write the codes on a sublime text editor, and executed them, it gave me the same result-nothing happened on the console when I clicked the button....
8. I gave up...

### What did you expect to happen? 

The console should throw the message : "You have no to do in your list " when I hit the buttons

### What actually happened? 

I wrote on the console
 todoList.displayTodos(); 

and got the following message
VM406:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1

And when I clicked "source" panel on the console, nothing there.

### Describe what you've done so far to troubleshoot the problem. 

1. After I wrote new lines of codes I ensure to hit the save button
2. I hit Run button
3. I opened the console and chose for plunker preview target
4. I wrote todoList.displayTodos(); and got the following message
VM406:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
But if I just pasted the codes on the console, I got everything working just fine-using firefox, but doesn't work in chrome since the console.log function somehow doesn't work on my pc 
5.Tried to click the buttons and nothing seen on the console
6. I tried using firefox and it gave the same result, nothing happened at the console when I clicked the buttons
7. I tried to write the codes on a sublime text editor, and executed them, it gave me the same result-nothing happened on the console when I clicked the button....
8. I gave up...

**Comment by BRValentine** [comment]
How do you "connect the javascript file and the html file"?

**Comment by cikatomo** [comment]
yes, how do you connect?

**Comment by anthonysim** [comment]
How do you "connect the javascript file and the html file"?
