### ISSUE TITLE
Objects and Memory Addresses - Data Types and Comparisons - code example 5

### ISSUE THREAD

**Issue by ayunas** [gordonmzhu/questions#175]
### What is the associated Watch and Code lesson?  . 
https://watchandcode.com/courses/60264/lectures/3954983

Write your response here (required).
Theory question:  When I did the diagram for this question, I thought each object gets its own specific memory address, even though it's equal to the same object value.  So in my diagram, I had 
myhouse1 = memaddress1 
and 
myhouse2 = memaddress2 
and both of those unique objects were pointing to the same single content, that is:  {color : blue}.  Please shed some light on why my understanding is incorrect.

**Comment by shellhatcher** [comment]
Hi,Ayunas

First of all let's look back at on when comparing two objects can result in true. Which is actually comparing an object to itself.

var A = {};
A === A
true

Based on this let's see the problem

var myHouse1 = { color : blue };
var myHouse2 = myHouse1;
myHouse2.color = red;

at the second line we know that actually myHouse2 is set to be myHouse1, hence whatever myHouse1 has myHouse2 will also have it ( it includes memory address, property, and value) all will be exactly the same. **We can think or make an analogy that myHouse2 is the clone of myHose1 which lives inside the same body (or in other words, myHouse2 is actually myHouse1 itself)**

And at line three, it asks to change the color property of the myHouse2 into red, it implies that it also change the color property of myHouse2, for they both actually two same objects which shares the same property, value, and address.

**Comment by gordonmzhu** [comment]
Is there a part of the video that doesn't make sense to you? If so can you specify what exactly?

**Comment by gordonmzhu** [comment]
Ping.

**Comment by ayunas** [comment]
No.  I think everything is fine.  I enjoyed your course, until maybe Version 9.  That was when you started losing me.  But I learned alot up until Version 9.  Thanks alot!

Amir Yunas

**Comment by gordonmzhu** [comment]
@ayunas Wondering how I can help. Where exactly in version 9 did you start getting lost?

**Comment by ayunas** [comment]
I followed along and built the app as you were doing, but the concepts stopped making sense to me in V9.  When you started going into the DOM manipulation, the concepts just weren't sinking in very well.  That was my first experience into the DOM, so I guess more time or examples to practice the DOM may have been helpful to me.  By the end of version 9, I was just copying what you were doing without actually getting it.  The part where we were trying to display the todo list elements on the actual html page is where I started losing you.  That is where I felt like I wasn't getting much value anymore in my learning so I stopped at version 9.  But up until version 8, everything was great. I was following along very well.  

Amir Yunas

**Comment by gordonmzhu** [comment]
Sounds good. If you have a more specific question, feel free to open a new issue. Thanks.
