### ISSUE TITLE
runWithDebugger for function with multiple arguments.

### ISSUE THREAD

**Issue by hydroweaver** [gordonmzhu/questions#18]
### What is the associated Watch and Code lesson? ]

(https://watchandcode.com/courses/60264/lectures/1125982)

I'm trying to call the runWithDebugger on a foreach function with arguments in it, however runWithDebugger is not accepting it, although it runs the function.

### Include a live demo link so that I can run your code. 

(https://repl.it/@hydroweaver/runWithDebugger-Watch-and-Code)

### Explain the exact steps I need to take to replicate the problem. 

You just need to run the code in repl.it to check the error with runWithDebugger

### What did you expect to happen? 

I expected runWithDebugger to run the debugger without referring to myfunc() not existing.

### What actually happened? 

**TypeError: myfunc is not a function**

Even though runWithDebugger runs without an issue on a single function.

### Describe what you've done so far to troubleshoot the problem. 

I have looked back into the video, in essence, if I run:

`runWithDebugger(counter);` 

it runs without any problem, however if I run the following, which is a nested function, it's a problem:

`runWithDebugger(foreach(students, counter));`

**Comment by gordonmzhu** [comment]
In this example, `runWithDebugger(foreach(students, counter));`, if `myFunc` isn't a function, then what is it?.

Hint 1: You can find this out by using the debugger and looking at the values.
Hint 2: Calling a function is not the same as just referencing the function. For example, observe the difference between `runWithDebugger(counter)` versus `runWithDebugger(counter())`.

**Comment by hydroweaver** [comment]
Hi Gordon,

I now understand that counter() is a call and counter is a reference.
But then how can I reference a function with runWithDebugger which requires a parameter for it to run?

counter() can't work since there is no argument and it's a function call.
counter('this') doesn't work either since it's also a function call.

**Comment by gordonmzhu** [comment]
At this point in the course, you don't know enough to get this to work.

For students in Premium, getting this to work is one of the suggested exercises. After you go through the material there, you should be well-prepared to tackle this. 

See https://github.com/gordonmzhu/beasts/issues/2 for context.

**Comment by hydroweaver** [comment]
Thanks Gordon!
