### ISSUE TITLE
Variable defined twice

### ISSUE THREAD

**Issue by butrfly7624** [gordonmzhu/questions#181]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1102313

### Include a live demo link so that I can run your code. 

https://glitch.com/edit/#!/grateful-whippet?path=public/client.js:103:47

### Explain the exact steps I need to take to replicate the problem. 

I followed all of the steps of the lesson as shown. Everything works fine. 
I just have a question about why the same todosUl variable is defined the same way twice:
var todosUl = document.querySelector('ul');
once in line 77 under the displayTodos method and then again in line 103 under the setUpEventListeners method.

### What did you expect to happen? 

I understand that the setUpEventListeners function shouldn't be able to access this variable from the displayTodos function because of differences in scope, but wouldn't the code also work if the variable is defined in a shared scope so the code doesn't need to be repeated?

### What actually happened? 

Everything works the way it is supposed to. I am just wondering about the repetitive code and if there is a better way to do it.

### Describe what you've done so far to troubleshoot the problem. 

Again, there is no problem. The code does what it is supposed to do as is.

**Comment by gordonmzhu** [comment]
"wouldn't the code also work if the variable is defined in a shared scope so the code doesn't need to be repeated?"

Seems reasonable. Why not just try out this approach and see if it works?

**Comment by butrfly7624** [comment]
I tried it. 
I moved the var todoUl assignment code to the top of the var view array but it gave me an uncaught syntax error due to an unexpected identifier (in this case var). 
However, if I put the var todoUl assignment code in the line before the var view array starts then it does work as it should.
Can you please explain why it causes an error in the first instance?
Thanks,
Rebecca
![code with var todoul at top of view](https://user-images.githubusercontent.com/46636891/52631332-3c817f00-2ec7-11e9-82dd-3494e13ee982.JPG)
![syntax error in build 11](https://user-images.githubusercontent.com/46636891/52631333-3c817f00-2ec7-11e9-80c5-115ede403b4c.JPG)

**Comment by shellhatcher** [comment]
Hi, btrfly7624

I think it is because the syntax.  Inside an object property and value should be separate using colons and ends with coma to separate between properties inside the object.
var view = {} is an object, hence everything inside it must be written using the syntax I have mentioned above.

In your case you wrote:

var view = {
var todosUl **=** document.querySelector('ul')**;** }
And keyword var can't be used as a property name inside an object.

Correct me if I am wrong.

**Comment by gordonmzhu** [comment]
@shellhatcher is spot on. Thanks for helping out!
