### ISSUE TITLE
General Query ?

### ISSUE THREAD

**Issue by amjad21khan** [gordonmzhu/questions#182]
changeTodos : function(position,todoText){
//this.todos[position]=newValue;
this.todos[position].todoText = todoText;
this.displayTodos();
 
},
deleteTodos : function(position){
this.todos.splice(position,1).todoText;
this.displayTodos();
*************************************************************************************************************
In above mentioned methods, why we use brackets [position ] in ' changeTodos' and parenthesis (position,1 ) in deleteTodos. We are accessing same thing in both the codes that is position. What I have understood is, we use brackets just to change one of the properties of the objects, whereas in deleteTodo we are deleting entire object by using parenthesis ( ). Please correct me if I am wrong.

**Comment by shellhatcher** [comment]
Hi, Amjad21khan.

Hints: array[position ] is used to access the value inside an array at certain position.

While : array.splice(position, argument ) is a method or in easier way it is a function or if we want to think about it as in mathematics or physics,  it is a formula to get a desirable result, in this case it is a formula to delete specific value of an array. Inside( ) can be filled with anything, but in this case, the .splice( ) method asking for starting position and how many item we want to delete to be passed or filled inside ( ). For more detail you may read the MDN  documentation on this.

The way I remember this is, mostly something that has ( ) is a function or you may call it method, while [ ] related with accessing certain value of an array at a certain Position.

**Comment by gordonmzhu** [comment]
Thanks @shellhatcher for answering.

I recommend going back to review previous videos where I mention the difference. They have nothing to do with each other at all. `[]` is for array access. `()` is for calling a function.
