### ISSUE TITLE
There Should be a Button for Changing Todos (ERROR!)

### ISSUE THREAD

**Issue by RyanBlum** [gordonmzhu/questions#183]
### What is the associated Watch and Code lesson? 

There should be a button for adding Todos
https://watchandcode.com/courses/60264/lectures/1027557

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/6MYRsBI2t8DWYlaExvFN?p=info 

### Explain the exact steps I need to take to replicate the problem. 

I am trying to change a todo with the button but I get a series of errros in the console. I have copied your code line for line, and im not sure what to do :(

### What did you expect to happen? 

I expected it to work lol

### What actually happened? 

it didnt haha

### Describe what you've done so far to troubleshoot the problem. 

Ive tried using the debugger and google. but Im lost!

**Comment by hydroweaver** [comment]
Looks like you have an error here: 

`todoList.changeTodo(changeTodoTextInput.valueAsNumber, changeTodoTextInput.value);`

Can you spot it?

**Comment by RyanBlum** [comment]
Yes!!! Thank you so much.

**Comment by gordonmzhu** [comment]
Thanks for helping out @hydroweaver!

@RyanBlum Good lesson here. "line-by-line" is not accurate enough. You need "character-by-character" precision.
