### ISSUE TITLE
Help me with version 7 " clicking toogle all should run todolist.toggle all"

### ISSUE THREAD

**Issue by tommydoan** [gordonmzhu/questions#185]
### What is the associated Watch and Code lesson?  https://watchandcode.com/courses/60264/lectures/987944
 
Write your response here (required).
I tried out to fix some mistake but couldn't link the button with the code in javascript.
### Include a live demo link so that I can run your code. http://plnkr.co/edit/L9tW4sC8hFtzwQL8Rikv?p=preview

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 
Run
Write your response here (required).

### What actually happened? 
No error message. It was so weird cause didn't run. Maybe I forgot to link something with 2 type.

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 
Yep, I did but It totally didn't run at all. Plz help me out for next lesson. Thanks so much
Write your response here (required).

**Comment by hydroweaver** [comment]
Several errors in your code:

1.  Your JS code has error such as addEVENlistener....check this
2. name the functions same as the program, it'll make it a lot easier for everyone to debug
3. It's id= not id:

**Comment by gordonmzhu** [comment]
As @hydroweaver mentioned, you have multiple typos throughout your program.

You should also format the code the way I do in the videos.
