### ISSUE TITLE
Bad Practice - separation of concerns

### ISSUE THREAD

**Issue by Cory-Thomas** [gordonmzhu/questions#187]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/1027547

Write your response here (required).

So why are you using onclick="handlers.displayTodos()"? 
Isn't it bad practice to add JavaScript into HTML since it's not following the separation of concerns? Are your videos outdated or am I missing something because you are also teaching 'var' instead of 'let'(unless you fix that later on)? Was recommended to your website by a friend but I don't want to pick up bad habits.

However, I really am enjoying the course so far. I liked the emphasis on the debugger which other JS tutorials never really put too much time into explaining it or its importance.

**Comment by gordonmzhu** [comment]
I'd encourage you to think about things in a more nuanced way. The chief concern is always that the code is clear and understandable. So if there's a different approach you think might be clearer, try it out and reflect on the pros and cons. Usually these things are much more subtle and are not black/white issues.

About `var`, my philosophy is to teach students the core part of the JavaScript language. When I do that, my students pick up additional features that are added over time without any problem (like `let`, `const` and whatever else comes down the line). This is the opposite approach of most instructors, so it may be uncomfortable, especially if you're coming here from another instructor.
