### ISSUE TITLE
8.1 Our first refactoring - handlers is not defined

### ISSUE THREAD

**Issue by t-mak** [gordonmzhu/questions#188]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547
8.1 - Out first refactoring

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/GAQ8qssMo3pfjUdi?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Open the console and click all 4 buttons. Check the results.

### What did you expect to happen? 

I expected all of them to result in "Your list is empty!" message.

### What actually happened? 

The buttons connected to functions with DOM work. The buttons using handlers object throw an error:
Uncaught ReferenceError: handlers is not defined
    at HTMLButtonElement.onclick ((index):14)

And:
Uncaught ReferenceError: handlers is not defined
    at HTMLButtonElement.onclick ((index):15)

### Describe what you've done so far to troubleshoot the problem. 

I've tried retyping the code from the video, deleted the DOM functions, checked everything twice, moved the object declaration to the beginning of the file. No effect so far. I must be missing something, but I  can't figure out what it is.

[plunk-GAQ8qssMo3pfjUdi.zip](https://github.com/gordonmzhu/questions/files/2885748/plunk-GAQ8qssMo3pfjUdi.zip)

**Comment by t-mak** [comment]
What's strange is that everything works fine when I open the index.html after downloading code.
All the buttons work. 

On JSFiddle I have the same problem as on Plunker.

**Comment by gordonmzhu** [comment]
Hey @t-mak. If you delete the package.json file it will work. See http://plnkr.co/edit/s0V7qvnKhOQwFVD4sIyh?p=info.

**Comment by t-mak** [comment]
Thanks!

**Comment by manojcracked007** [comment]
> Hey @t-mak. If you delete the package.json file it should work. Give it a shot and let me know.

as you said in one of  your lectures asking questions when you're is a good practice...when i'm struck i thought instead of asking question i wanted to skip ...but i thought of your words and wanted to ask question and came this way....and i got the perfect solution ...thank you gordon...your lectures are awesome

**Comment by jacksone85** [comment]
@gordonmzhu I am having this problem in Plunker after i delete the portion of code we are refactoring. It works when I keep the "button id" lines in. Is the solution proposed here also something for Plunker only users?
