### ISSUE TITLE
Position connected to Index no. in example

### ISSUE THREAD

**Issue by mquilitzsch** [gordonmzhu/questions#189]
### What is the associated Watch and Code lesson? https://watchandcode.com/courses/60264/lectures/928388
Timing: around 02:54

Write your response here (required).
I understand the coding logic how the parameter represent the index no., but how does JS understand the connection between 'position' in 'todos[position]' and the index number as two different data types. Is 'position' a keyword reserved to represent any index no.?

### Include a live demo link so that I can run your code. 

Write your response here (required).
This is the code from the example:

function changeTodos(position, newValue) {
  todos[position] = newValue;
  // ? how does the 'position' connect to the array's index number (0,1,2...)?
}

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
This is how parameters work. It is exactly the same concept explained in https://watchandcode.com/courses/60264/lectures/2368421, so I'd recommend going back to make sure that makes sense before continuing. If you have a question about that lesson let me know.
