### ISSUE TITLE
Creating function to display todos results in undefined

### ISSUE THREAD

**Issue by rjtravers** [gordonmzhu/questions#19]
### What is the associated Watch and Code lesson?   Version 2, video 5 - "It should have a function to display todos", timestamp 3:14

Write your response here (required).
Hey man, appreciate the course!  When I try to create a function to display todos, I get "undefined" as my result (screenshot attached).  Not sure what I'm doing wrong and why it's not accepting my code?  This is in Chrome.
![undefined](https://user-images.githubusercontent.com/38090110/44127990-3bdbeb28-a00e-11e8-8963-ac9bdc00aedf.JPG)

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Hey @rjtravers. What you're seeing is the normal expected behavior so you're all good. Chrome recently changed what it logs to the console when you define a function. Now it logs `undefined` whereas it used to log the function (like in the videos). Hope this clears things up.

**Comment by rjtravers** [comment]
I see, thanks for the quick reply Gordon!

**Comment by gordonmzhu** [comment]
No problem. Keep up the great work @rjtravers!
