### ISSUE TITLE
I did it differently but it works. Is that okay?

### ISSUE THREAD

**Issue by LeeXiuLong** [gordonmzhu/questions#190]
### What is the associated Watch and Code lesson? 

My question is about version 6 in general.

### Include a live demo link so that I can run your code. 

http://next.plnkr.co/edit/4JQbIZy7oDycsCcYJ932

### Explain the exact steps I need to take to replicate the problem. 

There is no problem.

### What did you expect to happen? 

My code works fine.

### What actually happened? 

My code works

### Describe what you've done so far to troubleshoot the problem. 

My code works.

Hi Gordon,

I am taking your course and I was just wondering about my toggle all function. The way that I go through your course is I look at the requirements for the current version and then on my own I try and code a solution. I then go back and watch your video to see what I may have done wrong or what I might do better at etc. However, in version 6 I have simply used a different method of achieving toggle all then you, but my code does exactly what I want it to, just like yours does. However, I was wondering if there were any disadvantages to using my method versus your method? Is there a reason I shouldn't be doing it the way I'm doing it? Does it make a difference? Thanks for reading. 

-LeeXiuLong

**Comment by gordonmzhu** [comment]
Hey @LeeXiuLong as long as it works it's fine. If you are curious about pros/cons, I'd put the two approaches side-by-side and write out a list. That'll be the best way to build your intuition.
