### ISSUE TITLE
basic question for v4

### ISSUE THREAD

**Issue by dominick-designs** [gordonmzhu/questions#191]
### What is the associated Watch and Code lesson? 

just a quick question from this video: https://watchandcode.com/courses/60264/lectures/946809

are the todoText the same? See screenshot: https://share-inspiration.d.pr/xZ2bgN

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
What would you say based on what you learned from this section? https://watchandcode.com/courses/practical-javascript/lectures/4368171

**Comment by dominick-designs** [comment]
> What would you say based on what you learned from this section? https://watchandcode.com/courses/practical-javascript/lectures/4368171

After watching this video again, I would say that they are the same.

**Comment by gordonmzhu** [comment]
Really? Did you draw the diagrams?
