### ISSUE TITLE
OOP question

### ISSUE THREAD

**Issue by Cory-Thomas** [gordonmzhu/questions#192]
Not exactly related to a single video in your free version of your course but to the whole course.

Is the whole course based on an object oriented style approach to programming? Been hearing the past few years that functional programming has been getting more popular and i'm trying to understand the differences.

Not complaining but just trying to understand the pros and cons to each in terms of JavaScript, but i've heard it's good to mix both.

Just finished the free version of your course and plan to start the paid version soon once i've done some reviewing on the project that was built and some extra research on topics that i'm still trying to get down.

**Comment by gordonmzhu** [comment]
I don't follow style or fads in my teaching. They come and go just like fashion. When people say they only like functional programming, to me it's like saying people should only wear skinny jeans. Sure okay. I guess that's fine?

Anyway, my approach is to avoid trivialities like style. Instead I try to develop core skills that are timeless in nature (e.g. ability to read code, think about clarity, debug methodically). What is rather counterintuitive is that these are the skills you need to appreciate the pros and cons of different styles. If you do not have these core abilities, it's like worrying about icing before you have cake.

**Comment by gordonmzhu** [comment]
Added `faq` tag since styles are faddish these days :)
