### ISSUE TITLE
Watch and Code Lesson Version 2, changing todos

### ISSUE THREAD

**Issue by eileenrichardson617** [gordonmzhu/questions#194]
Not really a problem with coding, just wondering why we use brackets instead of parenthesis for the position of the item we want to change in our todo list.
 ie: todos[position] = newValue  instead of todos(position) = newValue

**Comment by gordonmzhu** [comment]
I suggest going back and reviewing a few sections back. I explain what brackets and parentheses are for when they are initially introduced.
