### ISSUE TITLE
clearing HTML input fields - clarification on how it works

### ISSUE THREAD

**Issue by michaelzmiller** [gordonmzhu/questions#195]
Hi Gordon, I'm not stuck - I'm actually ahead of the game and loving this, but I wondered how this is working. I've diagrammed this and run the debugger, but I'm not clear on how it's working, so I wanted to ask and see if you knew what I was overlooking or should I just accept not knowing....

  addTodo: function() {
    var addTodoTextInput = document.getElementById('addTodoTextInput');
    todoList.addTodo(addTodoTextInput.value);
    addTodoTextInput.value = '';
  },

On line 2 of the code above, we had to pull the data from the specific "addTodoTextInput" input in the DOM by using the ID. It's an absolute path (in HTML lingo) and it's stored in a variable.

On line 4 of the code above, we clear the input by setting the value to ''. But it's using a relative path (in HTML lingo). 

So the question is, how did the input know we were talking to it to clear itself when we had to specifically talk to it to get the data out of it? And how did it know to refresh/clear itself without refreshing the page?

I can see that line 4 would clear the value on the server, but how did it get back to the browser?

Or, do I need to forget about this for now and move on?

### What is the associated Watch and Code lesson?

Practical Javascript Version 8: https://watchandcode.com/courses/60264/lectures/1027557

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/fedIsefGf9MQbmkgddCD

### Explain the exact steps I need to take to replicate the problem. 

There is no problem

### What did you expect to happen? 

I expected to have to write an absolute path to the HTML input field on line 4 of the code and refresh it somehow.

### What actually happened? 

The code works without having to refresh the HTML input. 

### Describe what you've done so far to troubleshoot the problem. 

I diagrammed the code and ran the debugger, but still don't understand.

**Comment by shellhatcher** [comment]
@michaelzmiller

Please correct me if I am wrong. 
The codes are read from top down in JS, so I think, it works as follows:
1. On 2nd line it grabs the id of the imputed value, and stores it.
2. On3rd line it pushes the value into an array-using addTodo method-and hence this value is stored there.
3.on 4th line, it simply asks the value inside the input box to be cleared or set it empty.

In other words, the value is first stored, and then it will be removed from the input box. 

CMIW

**Comment by michaelzmiller** [comment]
@shellhatcher 

You are correct. It works. 

But still my questions are:

1) how did the input know we were talking to it to clear itself when we had to specifically talk to it to get the data out of it? And 2) how did it know to refresh/clear itself without refreshing the page?

I thought the addTodoTextInput.value was stored in memory, so clearing it would remove it from memory, but how does the input know?

Anyway, I may be making something out of nothing, but I couldn't diagram it, or track it in the debugger - but maybe I'm doing something wrong.

**Comment by gordonmzhu** [comment]
@michaelzmiller I'd encourage you to refrain from using language that is more complicated than needed unless you are 100% you are being precise.

For example, I have absolutely no idea what you mean when you say "absolute path (in HTML lingo)". I also have no clue what "But it's using a relative path (in HTML lingo)" means.

You also have the incorrect assumption that you need to refresh the page to clear data.

Okay, so let's start from a blank slate... It might help to forget everything you think you know.

After this line runs, `addTodoTextInput` points to a DOM element (recall memory addresses).
`var addTodoTextInput = document.getElementById('addTodoTextInput');`

This line adds the text inside the input to the todos array.
`todoList.addTodo(addTodoTextInput.value);`

Finally, the line in question. Did you run the code through the debugger? Do it a few times and experiment with typing different things in the input and see what you find.
`addTodoTextInput.value = '';`
