### ISSUE TITLE
Alternative to a google Chrome console? 

### ISSUE THREAD

**Issue by Codeissimple** [gordonmzhu/questions#197]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/946809

### Include a live demo link so that I can run your code. 

https://embed.plnkr.co/oUDlcJqfGYPsadjdYoTT/

### Explain the exact steps I need to take to replicate the problem. 

Does not work in Google Chrome - try it.

### What did you expect to happen? 

I expected it to work.

### What actually happened? 

My console constantly lags, and I cannot find a solution for it. Do you know an alternative to a 

### Describe what you've done so far to troubleshoot the problem. 

I have written and re-written the code many times, but it does not help. Do you know any alternative to using chrome, without having to build HTML and CSS structure? I tried everything I could online, and none of them allows to have an active input through the console. 
I am thinking of using a stand alone Javascript editor, I got a subscription with JetBrains.

**Comment by gordonmzhu** [comment]
You have a typo in your addTodo method. Go through it character-by-character and you will spot it.
