### ISSUE TITLE
Version 3 - Objects: plunkerPreviewTarget not recognizing todoList object

### ISSUE THREAD

**Issue by vishrutarya** [gordonmzhu/questions#198]
### Version 3 - Objects. Lesson "It should store the todos array on an object"
url: https://watchandcode.com/courses/60264/lectures/900211

### Screenshot below

![image](https://user-images.githubusercontent.com/12104721/54327003-d0796000-45c5-11e9-9a2b-089e0bf3b094.png)

### Explain the exact steps I need to take to replicate the problem.

1. Created the plunker
2. Wrote the code (as seen in screenshot).
3. Executed the program (hit the Run button)(see screenshot).
4. Opened chrome developer tools (see screenshot).
5.  Used drop down to select plunkerPreviewTarget.
6. Typed `todoList` in console and executed it.

### What did you expect to happen?

As shown in the lesson video, I expected:
1. the console to tab complete `todoList`
2. upon running `todoList`, its contents are displayed in the console.

### What actually happened?
> todoList
`Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1`

### Describe what you've done so far to troubleshoot the problem.

1. Tried using the new alpha version and the old version of plunker (as used in the video). 
2. Re-ran it several times.
3. Added a `console.log('this proves its executing.');` command in the plunk but, unexpectedly, the string was not printed in the Preview pane.

**Comment by gordonmzhu** [comment]
Is there a reason you left out your Plunker link? This is part of the issue template. Re-pasting for reference:

"Include a live demo link so that I can run your code. This should be a link to a Plunker or Glitch."

**Comment by vishrutarya** [comment]
Here's the link: http://plnkr.co/edit/rutH50ESEjOx8eyH?p=preview

Thanks for your reply, Gordon!

The main reason I didn't initially include the plunker link is that I wasn't sure whether the url in my browser would be accessible by you (that is, whether it was defaulted as public or private) and my quick investigation didn't return a useful answer.

**Comment by joeylil** [comment]
I'm also experiencing this issue. 
I'd like to add that when running the code the following error also occurs: 
"Failed to load resource: the server responded with a status of 404 ()".

**Comment by gordonmzhu** [comment]
@vishrutarya If you use the exact same file structure that I use in the video, it'll work (e.g. your project has additional files like package.json, while the following link does not).

I just tested this link and it works http://plnkr.co/edit/QMi1C06gEgNvTL89LMeA?p=preview. Let me know if it works for you.

**Comment by vishrutarya** [comment]
Aha. I didn't notice the file structure difference (what caused this difference isn't immediately obvious to me). Thank you, @gordonmzhu!

**Comment by gordonmzhu** [comment]
@vishrutarya You're welcome!
