### ISSUE TITLE
Help troubleshooting 500 server error.

### ISSUE THREAD

**Issue by eamaccready** [gordonmzhu/questions#199]
### What is the associated Watch and Code lesson? 

Hi Gordon,
I am working on version 8 on the first two lessons for refactoring the displayTodos and ToggleAll functions.

### Include a live demo link so that I can run your code.  

Here is my demo link http://plnkr.co/edit/Fpd7tnk7dSqi8C8Ko27R?p=gitter

### Explain the exact steps I need to take to replicate the problem. 

Everything was working fine in Plunker until the refactor. Then when I'd click the buttons in my UI with the event handlers attached to run my functions the GET request in the console would return a 500 error. If I called the same function in the console, it worked fine. I tried reverting my code to before that lesson and running it, it then produced the same problem. I tried running it in Firefox, same thing. I know 500 errors are server errors, so I'm thinking there may be something wrong on Plunker's end, but I want to 100% confirm there's nothing I can do because I can't keep coding. If there isn't I'm wondering if you know who to contact about the server. I tried their chat, but it doesn't look like it's checked very often, the last post before me was 2/27.  I have attached a screenshot of the console actions and responses showing it working in the console, and the GET request that failed. Hopefully you can help me troubleshoot this, I'm 68% done and was hoping to shift this to GitHub ASAP! Thanks for your help!
Sincerely,
Liz MacCready

![Error](https://user-images.githubusercontent.com/17777293/54800580-e4553f80-4c1f-11e9-9ca7-a103a0a7d0f6.PNG)

**Comment by gordonmzhu** [comment]
Hey @eamaccready! Looks like it's an annoying bug on Plunker's end. I ran your code and it worked maybe 7/10 times. 3/10 times, I'd get the same 404 you mentioned.

To get around this issue, I recommend following the steps here. It'll show you how to use a regular text editor and move away from Plunker. https://github.com/gordonmzhu/questions/issues/1

In the next version of Practical JavaScript, I will move away from Plunker and have everyone use a regular text editor too. Thanks and let me know if you have any issues with the new setup!

**Comment by eamaccready** [comment]
Thanks so much. I'll give it a go!

**Comment by eamaccready** [comment]
Got it working in VS Code and Chrome. I haven't figured out how to launch
it from VS code (which I think you can do) but I can search my drive on
chrome and grab it. Thanks so much! I even made separate html, css, and js
files and it's working with references in the html like Plunker. Sorry it
took a while, I got sidetracked (I'm also jobhunting for dev and data
science positions but I think that finally is coming to a close! )
