### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by djuraub** [gordonmzhu/questions#202]
### Include a live demo link so that I can run your code. 
http://embed.plnkr.co/lhDAQjTap6cYnnaRsdgv/

### Explain the exact steps I need to take to replicate the problem. 
got this => Uncaught TypeError: todoList.toggleCompleted is not a function

### What did you expect to happen?
  to check "x" between braces

### What actually happened?
 Uncaught TypeError: todoList.toggleCompleted is not a function
![2019-03-24 20 37 09 plnkr co 3264d124dac4](https://user-images.githubusercontent.com/48455827/54884741-c9c7d400-4e74-11e9-99a7-59877f512a8b.png)

### Describe what you've done so far to troubleshoot the problem. 

i don know what is the problem

**Comment by gordonmzhu** [comment]
You do not have a toggleCompleted method on your todoList object.
