### ISSUE TITLE
Cant log in to plnkr.co via github

### ISSUE THREAD

**Issue by elmira26** [gordonmzhu/questions#203]
Hi Gordon! Actually i ve an issue with sign in to plnkr.co via github. if i turn the button on the small window pops out and disappear instantly. 
Lately i update my system as my computer ask for it. I use mac (air) . And i also can't download files for example from other  resources. so maybe its a chrome issue or my Avira maybe block something...i dont know really (((
MAybe you could suppose what the problem is?? Bcs i cant move on . i stuck on Verson 3 : It should store the todos array ..    and i cant use plnkr or inspect the element(((
I will appriciate any help . Thank you.
ps: i use github and i sing in with plnkr...but i only cant enter it through the button. (macOS 10.14.4 last updated)

**Comment by elmira26** [comment]
i have found the solution! I erased www and replaced it with HTTPS and it works now))!!

**Comment by elmira26** [comment]
And i have another one issue now ...when i inspect the element and try to return todoList there is error
![Снимок экрана 2019-03-27 в 14 31 47](https://user-images.githubusercontent.com/43086050/55072851-40dfb100-509d-11e9-8e62-3fa29e924b7d.png)

**Comment by gordonmzhu** [comment]
Hmmm since you are having a lot of issues with Plunker, it might be good to use something else. If you follow the issue here https://github.com/gordonmzhu/questions/issues/1 you'll find out how to do that.

**Comment by elmira26** [comment]
Thank you Gordon!
