### ISSUE TITLE
Unable to get property '0' of undefined or null reference

### ISSUE THREAD

**Issue by Damemo** [gordonmzhu/questions#206]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by Damemo** [comment]
What is the associated Watch and Code lesson? 
Version 5 : Loops of logic
6th Video  i.e. displayTodos should show .completed

**Comment by Damemo** [comment]
Explain the exact steps I need to take to replicate the problem. 

var list = {
  line: [],
  display: function()
  {
    if (this.line.length === 0) 
    {
      console.log('Your todo list is empty');
    } 
    else 
    {
      console.log('My line: ');
      for (var i = 0; i < this.line.length; i++) 
      {
         if(this.todos[i].completed === true)
        {
          console.log('(x)',this.line[i].todos);
        }
        else
        {
          console.log('( )',this.line[i].todos);
        }
      }
    }
  },
  add: function(todos) {
    this.line.push({
      todos: todos,
      completed: false
    });
    this.display();
  },
  change: function(pos, todos) {
    // this.line[pos] = val;
    this.line[pos].todos = todos;
    this.display();
  },
  delete: function(posit, number) {
    this.line.splice(posit, number);
    this.display();
  }
};
 
Write the above code in plunker, save it, run it and do it in the Microsoft Edge Browser if you have one.
Open Console on Inspect. Write line.add('hi')
It will give an error after clicking on Enter key that shows

My line:                                                   script.js (11,7)
Unable to get property '0' of undefined or null reference

**Comment by ElC-Dev** [comment]
Hello.
You probably want to name your variables, functions, and objects as close, if not to the letter when coding along for this. It makes things a lot easier to troubleshoot.
Anyways, when I ran it on google chrome, and got the error, I noticed that your line --- if (this.todos[i].completed === true) --- was referring to this.todos[i], when it should've been this.line[i] instead.

I made the correction on your code here, and put it up on plunker so it's easier to compare. it's at: 
https://next.plnkr.co/edit/G0yLjA?preview

One thing I found is helpful, is to always check each variable, method, or reference, and make sure everything is pointing to the right place. You changed several names while following the lessons, so spotting differences became that more difficult for you. There are certainly pros when naming things differently, in that you need to pay more attention, and it's especially helpful when you make things just like the video, and change names a little to more easily spot what is related to what. But for the first time, it's probably better to follow lines, naming, and all to the letter, and make a separate version later to play around and get a better sense of what each line does, and how the computer is interpreting them.

With that in mind, I switched my version 3 of the todo list to public so you don't have to rebuild the whole thing to the letter, though that could also be helpful in itself, but then again, so could just re-reading all the code, so I'll post my version 3 link so you can decide which is better for you.  it's at:
https://plnkr.co/edit/YEcwMB

Good luck!

**Comment by gordonmzhu** [comment]
@Damemo If you'd like me to take a look. Please fill out the required fields (like "Include a live demo link so that I can run your code").

**Comment by gordonmzhu** [comment]
Closing due to 5 days of inactivity.
