### ISSUE TITLE
V3 It Should Have an addTodo Method

### ISSUE THREAD

**Issue by kbmeyerowitz** [gordonmzhu/questions#207]
### What is the associated Watch and Code lesson? 

Hi Gordon,

I'm having a bit of trouble with getting my code to run properly on plunker for the lesson "It Should Have an addTodo Method" at the 2:42 mark in the video. The url is: https://watchandcode.com/courses/60264/lectures/942295

Write your response here (required).

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/EPkAwoa72TupCrw6j7S6?p=preview

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

I think it's just a problem with the actual code I wrote? Meaning, I must have a missing comma or bracket or something, but I just can't find a difference between the code I wrote and the code from the lesson. After I add the addTodo method to the todoList object and then use the console to add an item to the todoList using push I get an error message.  

Write your response here (required).

### What did you expect to happen? 

I expected the new item I entered using push to be added to my todo list.
Write your response here (required).

### What actually happened? 

This is my error code from Plunker:
todoList.addTodo('plunker');
script.js:8 Uncaught TypeError: this.todos.plus is not a function
    at Object.addTodo (script.js:8)
    at <anonymous>:1:10

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

I compared the code I wrote with the code from the video and I just don't see a difference at all. Which worries me because I know that coding requires attention to detail! I also looked at line 8 in my JS code (which, according to the error code, seems to be the line that is causing the error)

**Comment by gordonmzhu** [comment]
The code you have in line 8 is not in the course. Restart the videos from a point where things still worked and then work through things again. This time, make sure that you have *character-by-character* accuracy.
