### ISSUE TITLE
function inside of object

### ISSUE THREAD

**Issue by JeremyFields** [gordonmzhu/questions#209]
### What is the associated Watch and Code lesson? 

Version 3, lesson 2 - "objects and functions"
URL: https://watchandcode.com/courses/60264/lectures/900210

Write your response here (required):

Hey man, really like your lessons. Pretty new to coding and have a (probably) basic question because I am not really understanding the point of why you would put a function inside of an object which just references to the object itself and prints the name? What I'm saying is, what is the benefit of doing it that way?

var Jeremy = {
   name: 'Jeremy',
   sayName: function (){
      console.log(this.name)
   }
}

and then running:
Jeremy.sayName();

VERSUS making a function not inside of the object that performs the same thing:

function sayName(){
   console.log(Jeremy.name);
}

and then running:
sayName();

?? I understand there must be a reason for doing it within the object for the sake of efficiency? I assume? I'm basically just not understanding what the benefit is of putting the function inside of the object and what that accomplishes? Why is it better to do it that way?

Thank you!!

Jeremy Fields

**Comment by ElC-Dev** [comment]
Hello. One great usage for putting functions inside objects, or defining methods, is that it makes it a lot easier to organize and manage code. Like having all functions related to displaying data, all contained inside a single object, named "view", and having all properties as descriptive and organized as possible. Organizing code, and making it as readable to other humans besides yourself (and even yourself later on, when you forget what you coded) is a very important thing to keep in mind when coding in general. 


I'm still a beginner, so there may be other reasons besides this to store functions inside objects, but I'm sure code organization is a pretty big, if not the main reason for doing this.

**Comment by nadat11** [comment]
Hello 
With method inside object you accomplishes that object performs an action. If you are and object Jeremy you need to have method walk or speak. Properties describe object but methods are actions.
Hope this explanation helps you.
BR

**Comment by gordonmzhu** [comment]
Putting a function on an object (i.e. creating a method) is just for organization. You can of course just have a standalone function instead.

But if you want to group a bunch of functions together, putting them onto a single object could be useful. Again, just an organizational convenience.
