### ISSUE TITLE
Hello Gordon First thank you very much for you tutorials :) and I'm having small problem. I don't have a track in debugger when I go into the displayTodos() method. I'm using Chrome and it is all ok until I go into the method. todoList.addTodo inside debugger.

### ISSUE THREAD

**Issue by nadat11** [gordonmzhu/questions#210]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
If you'd like a response, please fill out all of the question fields. At the moment, you have not provided enough information for me to help.
