### ISSUE TITLE
Debugger in diplayTodo() question

### ISSUE THREAD

**Issue by nadat11** [gordonmzhu/questions#211]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/997382

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/qA5rIau26DDF372xziuK?p=preview

### Explain the exact steps I need to take to replicate the problem. 

When I run todoList.addTodos('example') debugger runs just fine and I can saw code highlighted that is added. But when I go inside displayTodo() method highlighted code is not shown.

### What did you expect to happen? 

I expect to see iteration in for loop, because there is more than one todos item.

### Describe what you've done so far to troubleshoot the problem. 
I have checked debugger settings and Google the problem.
![var not visible beside code](https://user-images.githubusercontent.com/46525861/55936669-a0ae8e00-5c3f-11e9-9829-7fa7d9497939.png)
![Todotext visible beside code](https://user-images.githubusercontent.com/46525861/55936671-a1472480-5c3f-11e9-9ef8-6709c03a526d.png)

**Comment by gordonmzhu** [comment]
You said "But when I go inside displayTodo() method highlighted code is not shown."

Isn't that exactly what is happening in your first screenshot?

**Comment by nadat11** [comment]
Yes that is what I'm asking, why I can't see highlighted code like before I go into the method? Do I need to adjust settings in debugger?

**Comment by gordonmzhu** [comment]
In your screenshot, line 9 *IS* highlighted. You are saying it's not...

**Comment by nadat11** [comment]
Why I can't see   i=0  and forward beside the code?

**Comment by gordonmzhu** [comment]
Chrome changes the way it shows variables from time-to-time. If you want to check what `i` is at any moment, you can hover your mouse over it and it will show you.]
