### ISSUE TITLE
plnkr

### ISSUE THREAD

**Issue by Olopai** [gordonmzhu/questions#212]
**What is the associated Watch and Code lesson?**

        https://watchandcode.com/courses/60264/lectures/900211

**Include a live demo link so that I can run your code.** 
      http://plnkr.co/edit/1uP3khB8gc1bArbzgy4z?p=preview

**Explain the exact steps I need to take to replicate the problem.** 
     I followed every step of the video. After 'saving' my work, I clicked on 'Run'. And then I opened up the console and clicked on the 'dropped down.' 

 **What did you expect to happen?** 
     I expect to see PlunkerPreviewTarget.

**What actually happened?** 
         The drop down didn't contain 'PlunkerPreviewTarget'. 

 **Describe what you've done so far to troubleshoot the problem.** 
          I restart Chrome and tried again but to no avail. I tried in Safari and the same happened.

**Comment by gordonmzhu** [comment]
Please include a screenshot that shows the app running and the dropdown so I can see what you mean.

**Comment by Olopai** [comment]
![Screen Shot 2019-04-12 at 11 34 27 AM (2)](https://user-images.githubusercontent.com/13980970/56069033-1d7c5d80-5d4f-11e9-8839-6c53c4d41c2b.png)

**Comment by Olopai** [comment]
http://plnkr.co/edit/1uP3khB8gc1bArbzgy4z?p=preview

**Comment by Olopai** [comment]
Is this what you need?

**Comment by Olopai** [comment]
Here is a video.

[IMG_7294.MOV.zip](https://github.com/gordonmzhu/questions/files/3075341/IMG_7294.MOV.zip)

**Comment by Olopai** [comment]
Hi Gordon,
Just wondering if you saw the video that I posted?
Basically right now I'm just watching the videos but not writing because I can't see 'PlunkerPreviewTarget'. 
Thank you for your time.

**Comment by ElC-Dev** [comment]
Hello.
In my opinion, It's probably not a good idea to just passively watch the video. I don't know about you, but it would be very hard for attain a deeper understanding without typing, experimenting, or even handwriting code. 
Also, I don't recall how I solved it, but I had a similar experience with plnker. If you really want to do this through plunker, you could click through each of the drop downs to see if any of them appear to work. But if that doesn't work, you should consider copying your code so far to [glitch ](https://glitch.com/). Or even download VS code, and loading your script file externally, directly to HTML. There are just too many options you choose from, and all of them are better than just watching without coding along. It's also worth mentioning that Gordon switches from Plunker to Glitch at around version 9, and Glitch is actually easier and friendlier than Plunker. 

If/when you do copy or write code for your current version of the Todo list, I recommend you read through the code line by line from the beginning, and try to see how much you understand, and even use the debugger on functions to get a better feel on how the computer is interpreting each line. But whatever you do, be sure to code along with any of the countless options. Also, if you're using firefox on plunker, or even Chrome, etc, be sure to enable scripts for the site, as well as enabling ads. Havings ads/scripts disabled could be breaking some of the functionality like plunker preview target, etc.
Anyway. Hope that helped a bit.
 Good luck!

**Comment by Olopai** [comment]
Hi,
Thank you.
I will use glitch. 

Thank you for your reply and time.
Ty

**Comment by gordonmzhu** [comment]
Thanks for the screenshot. If you pay close attention in the videos, you will see that I hit the "Play" button first. You have to do that for `plunkerPreviewTarget` to show up. If you hit "Play" as I do, you will get the same results that I do.
