### ISSUE TITLE
'plunkerPreviewTarget'

### ISSUE THREAD

**Issue by Olopai** [gordonmzhu/questions#213]
[IMG_7294.MOV.zip](https://github.com/gordonmzhu/questions/files/3081864/IMG_7294.MOV.zip)

Please take a look at the video.
I don't know how else to explain the issue with plnkr.
I saw old post with similar situation and yes I tried everything.
[IMG_7294.MOV.zip](https://github.com/gordonmzhu/questions/files/3081875/IMG_7294.MOV.zip)

**Comment by gordonmzhu** [comment]
Closing. I responded in the original thread.

**Comment by Olopai** [comment]
Aha!
I'll click on 'run' and then 'inspect' and the 'run' turns off! So hit the start button again. 
Thanks.
