### ISSUE TITLE
Increment for addTodos function

### ISSUE THREAD

**Issue by leahrowland** [gordonmzhu/questions#214]
Hello, 
### https://watchandcode.com/courses/60264/lectures/928385
Is is possible to add a parameter that will automatically number the added 'Next Item'? So for example it will add 'Next Item #4', then 'Next Item #5' each time the addTodos function is performed? 
```
function addTodos () {
	todos.push('Next Item');
	displayTodos();
}
```

**Comment by gordonmzhu** [comment]
If you stick with the course and understand everything, you should know how to do this by the end.
