### ISSUE TITLE
What are you using?

### ISSUE THREAD

**Issue by Bubzeal** [gordonmzhu/questions#215]
It's the very start of the Version 2, I don't know how to follow along because I have no idea what you're typing the function into.

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You can use any text editor like Google docs, Microsoft Word, etc. At the beginning of V2 I'm just writing notes, not actual code.
