### ISSUE TITLE
Console.log function.

### ISSUE THREAD

**Issue by lxkant26** [gordonmzhu/questions#217]
For me console.log(todos) always prints undefined even todos variable have some value.

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
This is normal behavior. You'll learn about why later on in the curriculum.
