### ISSUE TITLE
Version 6 Toggle All does not work

### ISSUE THREAD

**Issue by ssairafe** [gordonmzhu/questions#218]
### What is the associated Watch and Code lesson? 

Version 6 Toggle All function

### Include a live demo link so that I can run your code. 

here is my code:
toggleAll: function () {
      var totalTodos = this.todos.legth;
      var completedTodos= 0;
      for (var i=0; i< totalTodos; i++) {
        if (this.todos[i].completed===true) {
          completedTodos++;
          }
        }
        if (completedTodos===totalTodos){
          for (var i=0; i< totalTodos; i++){
            this.todos[i].completed = false;
            }
          } else{
            for (var i=0; i<totalTodos; i++) {
              this.todos[i].completed= true;
            }
            
          }
          this.displayTodos();
        }
  };

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

toggle all between completed and incomplete.

### What actually happened? 

the code ran without error however nothing changes from complete to incomplete. everything but the toggle all functions work.

### Describe what you've done so far to troubleshoot the problem. 

I have tried rewatching and redoing the code. I have attempted to use boolean value to receive opposite outcome, and I have attempted using a different compiler however I couldnt figure it out and I dont want to waste time figuring it out yet.

Write your response here (required).

**Comment by ssairafe** [comment]
Here is my whole code just in case you need it:
var todoList = {
  todos: [],
  displayTodos: function(){
    if (this.todos.length===0) {
      console.log ('Your todo list is empty')
    } else {
    console.log('You Need To:');
    for (var i=0; i<this.todos.length; i++){
     if(this.todos[i].completed===true){
      console.log ('(x)', this.todos[i].todoText);
    } else { 
    console.log ('( )', this.todos[i].todoText);
          }
        }
      }  
    },
  addTodo: function (todoText) {
    this.todos.push({
      todoText: todoText,
      completed: false
    });
    this.displayTodos();
    
  },
  changeTodo: function (position, todoText){
    this.todos[position].todoText= todoText;
    this.displayTodos();
    },
    deleteTodo: function(position){
      this.todos.splice (position, 1);
      this.displayTodos();
    },
    toggleCompleted: function (position){
      var todo= this.todos[position];
      todo.completed= !todo.completed;
      this.displayTodos();
    },
    toggleAll: function () {
      var totalTodos = this.todos.legth;
      var completedTodos= 0;
      for (var i=0; i< totalTodos; i++) {
        if (this.todos[i].completed===true) {
          completedTodos++;
          }
        }
        if (completedTodos===totalTodos){
          for (var i=0; i< totalTodos; i++){
            this.todos[i].completed = false;
            }
          } else{
            for (var i=0; i<totalTodos; i++) {
              this.todos[i].completed= true;
            }
            
          }
          this.displayTodos();
        }
  };

**Comment by gordonmzhu** [comment]
Open a new issue and fill out all the fields (including a live demo link as described in the question template) and I'll take a look then.
