### ISSUE TITLE
plunker stopped my chrome console from working 

### ISSUE THREAD

**Issue by juanie** [gordonmzhu/questions#220]
### What is the associated Watch and Code lesson? 
Not about the your class it about my chrome  
Write your response here (required).

### Include a live demo link so that I can run your code. 
I don't want any program to save files on my machine which it is doing 
Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 
tried to uninstall program 
Write your response here (required).

**Comment by abdo2017** [comment]
can you try open the console again, and make sure to choose (top) plunker in the field next to the clear console button

**Comment by gordonmzhu** [comment]
Plunker is a website, not a program that you install. That said, if you'd still like to use something else, see #1.
