### ISSUE TITLE
.document does not work in Gltch, Version 10

### ISSUE THREAD

**Issue by ramirologi** [gordonmzhu/questions#221]
### What is the associated Watch and Code lesson? 

Associated lesson: https://watchandcode.com/courses/60264/lectures/1102309
Timestamp: 1:46.

### Include a live demo link so that I can run your code. 

Live demo: https://iris-parka.glitch.me

### Explain the exact steps I need to take to replicate the problem. 

.document does not work in Glitch (does not turn green when written)
 
### What did you expect to happen? 

.document to work in Glitch (turn green)

### What actually happened? 

Error message: view is not defined
    at <anonymous>:1:1

### Describe what you've done so far to troubleshoot the problem. 

Just copy the code from Watchandcode video "there should be a way to creat delete buttons" Version 10

**Comment by gordonmzhu** [comment]
What are you doing to trigger the error `Error message: view is not defined at :1:1`?

**Comment by ramirologi** [comment]
Now i did. Figure out that the version of Gliter on you tutorial is different than mine and that is why i clicked on other option that did not define view at 1:1. Thank you.
