### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by crazydeveloper119** [gordonmzhu/questions#226]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by crazydeveloper119** [comment]
Hi i just have a general question for you.  So ive began learning javascript about 2 weeks ago or so and i was wondering....if you struggle alot does it mean its not for you or should i just be patient and keep going?  Like you said in your video i see this huge gap from where im looking and where i "think" i need to be?

**Comment by gordonmzhu** [comment]
Programming is problem solving. Having problems is a type of struggle, only if you perceive it to be.

Having a healthier perspective is very simple, but not easy. When you run into issues, work to the best of your ability to resolve them. When you are truly stuck, then ask for help following the guidelines in the how to ask questions article (post a question, go to office hours, etc). That's it.
