### ISSUE TITLE
V3 it should have displaymethod

### ISSUE THREAD

**Issue by DivyanshTest** [gordonmzhu/questions#227]
### What is the associated Watch and Code lesson? 
V3 it should have displaymethod
Write your response here (required).
In the plunker console im getting an exception

Please assist how to resolve it
### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
![image](https://user-images.githubusercontent.com/44339783/57647293-31caa900-75e0-11e9-898a-550046d358b9.png)

**Comment by gordonmzhu** [comment]
Please open a new issue and make sure to fill out all the fields. When you do that, I'll be happy to help.
