### ISSUE TITLE
Plunker Errors 

### ISSUE THREAD

**Issue by Airfieldd** [gordonmzhu/questions#23]
Please see snapshot below. Keep getting the Server 404 from Plunker. Did anyone get plunker working on your end?

![screen shot 2018-08-15 at 4 41 02 pm](https://user-images.githubusercontent.com/23464665/44179106-19a61780-a0aa-11e8-8e5a-65f24df114fb.jpg)

**Comment by hydroweaver** [comment]
You need to inspect from the HTML page and secondly clear the console, these are not related to your code. You can use the command `clear();`

**Comment by Airfieldd** [comment]
Thank you for answering my question! I tried it from the HTML page and cleared the console. It is still giving me the error whenever I tried to run the code.

**Comment by hydroweaver** [comment]
What's your plunkr link?

**Comment by Airfieldd** [comment]
Here it is: 
http://embed.plnkr.co/xvPGPd3EcR1IsQNq/

**Comment by hydroweaver** [comment]
Check line 80, can you spot the problem with your function syntax?

**Comment by Airfieldd** [comment]
Thank you! I replaced Function with function on link 80. However, I am not sure if the function syntax error cause the server 404 error. Removing line 76 to 83 didn't fix the problem.

**Comment by hydroweaver** [comment]
I think it might have something to do with Plunkr, maybe Gordon might know.

**Comment by Airfieldd** [comment]
I really appreciate you answering my question and going over my code. Thank you!

**Comment by gordonmzhu** [comment]
If you reformat your code to follow the same style as mine, I can take a look. The way the code is formatted is too hard to read.

**Comment by Airfieldd** [comment]
Hi Gordon,

Thank you so much for responding the message. And thank you for the tips. I will fill in the required fields next time. 

I am not certain if the "Failed to load resource: the server responded with a status of 404" error has much to do with the code. The error persists even when I create a simple object. I have updated my plunker to a simple object. Could you please give it a try on your end?

Plunker url: http://embed.plnkr.co/xvPGPd3EcR1IsQNq/


![image](https://user-images.githubusercontent.com/23464665/44239249-4b33e700-a16d-11e8-9e4b-03d6dfa6c1e2.png)

**Comment by Airfieldd** [comment]
Interesting!!! Thank you. I initially thought it must have something to do with Plunker site. You are right, your plunk was working perfectly. I will start everything over again. 

Really appreciate your time!
