### ISSUE TITLE
"todos.splice is not a function"?

### ISSUE THREAD

**Issue by BRValentine** [gordonmzhu/questions#230]
### What is the associated Watch and Code lesson? 
Practical Javascript - Version 2 - It should have a function to delete a todo
Write your response here (required).
//Here is the code, as shown in the video and typed into about:blank page in the console, with error message:
function deleteTodo(position) {
	todos.splice(position, 1);
	displayTodos();
}
undefined
deleteTodo(0)
VM1195:2 Uncaught TypeError: todos.splice is not a function
    at deleteTodo (<anonymous>:2:8)
    at <anonymous>:1:1

triple confirmed my code was that same as that shown in the video
searched for related error message
please help! thanks :)

**Comment by gordonmzhu** [comment]
You need to make sure `todos` is defined.

**Comment by BRValentine** [comment]
Thanks, Gordon!
