### ISSUE TITLE
"i" vs. "this.todos[i]"

### ISSUE THREAD

**Issue by chotorn** [gordonmzhu/questions#232]
Hi,

I have a general syntax question, related to the overall todoList project, but not to any of the specific videos.

On my own I wrote another method, deleteCompleted to remove just completed todos from the array.

Initially, I was using the following method, but it did not behave as intended:

deleteCompleted: function(){ 
      for( var i = 0; i < this.todos.length; i++ ){
        if (this.todos[i].completed === true) {
          this.todos.splice(this.todos[i], 1);
        }
    }
  },

Then, after asking for help, I was told to modify the method accordingly (and it worked):

deleteCompleted: function(){ 
      for( var i = 0; i < this.todos.length; i++ ){
        if (this.todos[i].completed === true) {
          this.todos.splice(i, 1);
        }
    }
  },

The problem is that I don't fully understand why this worked, I was hoping you could shed some light on why "this.todos[i]" is telling the computer to do something different than "i".

Thanks!

**Comment by gordonmzhu** [comment]
`this.todos[i]` is one thing and `i` is something else entirely. Run your code through the debugger and you will see exactly what's going on.
