### ISSUE TITLE
usage of = instead of ===

### ISSUE THREAD

**Issue by kirbxy** [gordonmzhu/questions#233]
Hello Gordon,
Minor question about this lession.

https://watchandcode.com/courses/60264/lectures/936343

Time: (3:50)

for (var i= 0; i < all; i++ ) {
      this.todos[i].complete = false
      }

why do we have to use = in this  

 {this.todos[i].complete = false} 

for loop instead of ===  ? I initially used === but the ToggleAll function did not uncheck the list when I execute it. There is no error message but it simply show the list with every item remained checked. 

Thanks for responding!

**Comment by gordonmzhu** [comment]
Comparisons are described in the next section "Interlude - Data types and comparisons". Hold on to your question and it will be answered then.
