### ISSUE TITLE
Why doesn't todo.completed need a .this in front of it?

### ISSUE THREAD

**Issue by andreaguillou** [gordonmzhu/questions#234]
### What is the associated Watch and Code lesson? 

I didn't run into a problem, but I'm just having trouble understanding when or not to use .this

https://watchandcode.com/courses/60264/lectures/946811

Why doesn't the line of code "todo.completed = !todo.completed;" require a this. in front of it?

So how come it doesn't have to be:

this.todo.completed = !this.todo.completed ?

Thanks!

**Comment by gordonmzhu** [comment]
Well... what is the variable `todo` equal to?

**Comment by andreaguillou** [comment]
> Well... what is the variable `todo` equal to?

Oh so var todo = this.todos[position];

That makes sense now, I didn't catch that. Thank you!

Does that mean todo.completed could also be written as this.todos[position].completed if you wanted to?

**Comment by gordonmzhu** [comment]
Don't wonder about things you can try yourself. Try it and you'll see.
