### ISSUE TITLE
ChangeTodo button isn't changing anything

### ISSUE THREAD

**Issue by NokiaBird** [gordonmzhu/questions#236]
Lesson Link: https://watchandcode.com/courses/60264/lectures/1027557

I did follow the lesson and did all the steps correctly but the code is only working at everything else but changeTodo button it just displays the things i added using the addTodo button.

here is the link of the code:
https://plnkr.co/edit/D0Q0Hd8DPYvfz16ctE16?p=preview

above is the plunker link of my code where change todo button wouldn't run.

### Explain the exact steps I need to take to replicate the problem. 

After adding new todos i tried to change them but it just won't do that 
I only use Chrome.

### What did you expect to happen? 
I was expecting from change todo button to modify or change todos but it didn't and the reason led me to expect that was my careful and deep understanding of the lesson
Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You said "I did follow the lesson and did all the steps correctly".

How confident are you about this statement on a scale of 0-10, where 0 is no confidence and 10 is absolutely sure?

**Comment by NokiaBird** [comment]
I'm 10 out of 10 sure about
i even double checked it before writing this reply

Thank you for your time in advance.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gordonmzhu** [comment]
Your code is definitely *not* the same. I would check things more carefully this time, character-by-character this time and also reconsider your confidence about these types of things. It would help to have more skepticism about how carefully you are checking things.

**Comment by gordonmzhu** [comment]
I'm closing this issue because I am expecting that you'll find the problem when you carefully review things again. If you're still having trouble after spending a minimum 30 minutes checking your work, please open a new issue and I'll be happy to take a look.

**Comment by NokiaBird** [comment]
Sure will do it
Thank you

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
