### ISSUE TITLE
Error message in console Version 8

### ISSUE THREAD

**Issue by tkurita07** [gordonmzhu/questions#237]
### What is the associated Watch and Code lesson? 

Write your response here (required).
Version 8 - Getting data from inputs

## Include a live demo link so that I can run your code. 

Write your response here (required).
https://plnkr.co/edit/irAtcYI04O1yxS3xoQzJ

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
Rewrote code 2x
Well actually redid the lessons also
### What did you expect to happen? 

Write your response here (required).
Constant error message
Finish lesson with same error.  Tried to goggle search for the answers but with no luck

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
Like I said redid lesson really carefully and matched codes
![IMG_8370](https://user-images.githubusercontent.com/50464155/58214562-e1afae80-7c91-11e9-94a1-53b4f39e90ae.jpg)

**Comment by gordonmzhu** [comment]
What did you do specifically to trigger the error?

**Comment by tkurita07** [comment]
Found my answer thanks for the response
