### ISSUE TITLE
Playcode > Plunkr

### ISSUE THREAD

**Issue by BRValentine** [gordonmzhu/questions#238]
Ongoing issue with Plunkr: constantly getting "Uncaught reference error" with variable "undefined" when checking code in the console.

Stopping the code, then exiting and reopening the plunk often works, sometimes doesn't.

Here is a screenshot of a typical instance of this "uncaught reference error.
![plunkr](https://user-images.githubusercontent.com/29690117/58306704-fc6b5a00-7e2e-11e9-8e86-5f6d89c1caa2.JPG)

I c + p'd the exact same code into playcode.io, and it displayed in the console perfectly. Which, btw, I didn't have to go through that tiresome 'inspect ->  console -> select plunkr view-> clear code  ' process to view.

Screenshot for proof, code c+p'd from last screenshot: 

![playcode](https://user-images.githubusercontent.com/29690117/58306721-0d1bd000-7e2f-11e9-862d-2fe6c87b54df.JPG)

Question: Is there any reason I should be using plunkr & not playcode.io for this course?

**Comment by gordonmzhu** [comment]
You have a syntax error in your Plunker code. If you include the link (as requested in the template), I can tell you what it is.

**Comment by BRValentine** [comment]
No need, Gordon - I'm a fool. I see the syntax error. Apologies for flouting the ONE thing you ask of us - to ask good questions! :/ However, I see the same error in playcode, and the console is still returning correctly, without the need for the constant "inspect-console-plunker-clear" schtick. 
Any feedback on whether I can use playcode just as effectively for your wonderful course?
