### ISSUE TITLE
Cannot get the dropdown menu

### ISSUE THREAD

**Issue by HelmutLicht** [gordonmzhu/questions#24]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/900211
### Include a live demo link so that I can run your code. 
What is a live demo link?
Write your response here (required).
You say: We should save the project. I hit SAVE. then you say: Let's RUN the program and ignore the 'Hello Plunker'. I hit run. Then you say: Right click, click on Inspect and when YOU do that you make reference to a drop down menu. I see the drop down menu on your screen, but when I hit inspect I don't get the same screen you get. I do not see a drop down menu and in 2 seconds the inspect screen disappears and I am back to the  previous screen, the one before I right click to get the inspect,
### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

I expected to see the same drop down list that you get after you right click and then click on inspect.
![after i hit run and then inspect use](https://user-images.githubusercontent.com/41840662/44188335-023b4e80-a0eb-11e8-9b33-6cc4b23d9cb7.jpg)

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by HelmutLicht** [comment]
I am in Plunker and when I right click I get the drop down list with 'inspect' at the bottom. I click on 'inspect' and a new screen pops up, however, it is not the same screen that you show on your tutorial. You point to a new drop down list THAT I DO NOT GET.

**Comment by hydroweaver** [comment]
Hi @HelmutLicht, your inspection screen is **docked** to the right side, see the three dots, click on them and change the docking setting to **Dock to Bottom**, then check the dropdown and go to Plunker Preview Target.

![docking](https://user-images.githubusercontent.com/6553008/44202062-9697c680-a168-11e8-9df6-d34cc6a79212.png)

**Comment by HelmutLicht** [comment]
It would be a good idea to number each tutorial sequentially instead of with a line of text. Or, perhaps both. Can I proceed  to the next lesson without completing the one that's blocking my progress?

**Comment by HelmutLicht** [comment]
Thank you!!! It works. 14 days of learning wasted because of one simple little unknown solution. Let me resume my lessons and we’ll see what happens. Have a great day!

Sent from Mail for Windows 10

**Comment by gordonmzhu** [comment]
Thanks for helping out @hydroweaver.
