### ISSUE TITLE
Objects and Functions

### ISSUE THREAD

**Issue by rghvsharma4** [gordonmzhu/questions#240]
Can the name of an object be same as one of its property name? I tried to create an object ("name") with the same name as one of its property ("name") and tried to create a function ("display ()")to display the property. and i got error "VM1286:1 Uncaught TypeError: name.display is not a function     at <anonymous>:1:6".

I am wondering why the property name can't be same as the object name. Can u please tell the logic behind this.

**Comment by gordonmzhu** [comment]
Hey @rghvsharma4. If you open a new issue and include a link to a live demo of your code (as I request in the issue template), I'll be happy to take a look.
