### ISSUE TITLE
Booleans in JavaScript

### ISSUE THREAD

**Issue by rghvsharma4** [gordonmzhu/questions#241]
This question is regarding toggleCompleted method in video (https://watchandcode.com/courses/60264/lectures/946811) at timestamp 3:41.

I was wondering why do we get undefined error when we use single line code 
"this.todos[position].completed=!this.todos[position].completed;" 

instead of multiple lines

"var todo=this.todos[position];
  todo.completed=!todo.completed;
  this.displayTodos();"

**Comment by gordonmzhu** [comment]
@rghvsharma4 if you open a new issue and fill out all of the required fields, I'll be happy to take a look. I can't see what the error message is if you don't provide working code for me to run.
