### ISSUE TITLE
Question about assigning variable

### ISSUE THREAD

**Issue by kirbxy** [gordonmzhu/questions#244]
https://watchandcode.com/courses/60264/lectures/946811

Timestamp (3:38)

When you added the variable,   var todo= this.todos[position],  why couldn't you add the ".completed" after the [position]? ( var todo = this.todos[position].completed)

Then on line 23, it simply becomes (todo = !todo)

I tried doing it this route. There was no error message and the code still executed but it did not change the false to true. Why was that the case?

**Comment by gordonmzhu** [comment]
You'll find the answer for this later on in "Interlude - Data types and comparisons" (right after version 6).
