### ISSUE TITLE
Todo List is Working But I Get an Error Code

### ISSUE THREAD

**Issue by kbmeyerowitz** [gordonmzhu/questions#245]
### What is the associated Watch and Code lesson? 

Version 8: Getting Date from Inputs
https://watchandcode.com/courses/60264/lectures/1027559
2:29

Write your response here (required).

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/EPkAwoa72TupCrw6j7S6?p=preview

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

I am able to add todos by clicking the Add button.  
After clicking this button the console immediately displays all the todos in my list. 
Next, I click Toggle Completed. I immediately get the following error message: 

                  script.js:38 Uncaught TypeError: Cannot read property 'Todos' of undefined
             at Object.toggleCompleted (script.js:38)
             at Object.toggleCompleted (script.js:111)
             at HTMLButtonElement.onclick ((index):37)

Next, I click the button Display Todos. Even though I have just received the error message listed above, the todo item that I deleted is shown as deleted (it has an 'X')

In terms of trying to figure out what I've done wrong, I've tried to go back into my code and check out lines 38, 111 and 37, but I'm unable to find where I've gone wrong. 

### What did you expect to happen? 

Write your response here (required).
When clicking Toggle Completed I expected to immediately see my Todo List appear with the appropriate items "X"ed off to indicate completion. I anticipated this because this is what I watched happen in the video.

### What actually happened? 

Write your response here (required).

Instead of having my entire todo list appear with the appropriate item "X"ed off as completed, I get the following error message in the console:

 script.js:38 Uncaught TypeError: Cannot read property 'Todos' of undefined
             at Object.toggleCompleted (script.js:38)
             at Object.toggleCompleted (script.js:111)
             at HTMLButtonElement.onclick ((index):37)

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

I have visually looked at my code and compared it to what was done in the course. I have tried debugger and am still a bit confused using it. I will try it again, if you think it is the best way to learn at this point in the course.

**Comment by gordonmzhu** [comment]
The error message is telling you exactly what is wrong. You have a typo in line 38. Looking through "visually" is not enough. You need to go through character-by-character and be 100% sure they are the same (hint, they are not).


Relevant quote from Alan Perlis: "For all its power, the computer is a harsh taskmaster. Its programs must be correct, and what we wish to say must be said accurately in every detail."

https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-5.html

**Comment by kbmeyerowitz** [comment]
Thank you, Gordon! Will look through with a "fine-tooth comb" tonight! :)
