### ISSUE TITLE
What error to report for missing dependencies ~ librarySystemWithDependencies.js

### ISSUE THREAD

**Issue by ugitch** [gordonmzhu/questions#246]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/77710/lectures/8465977

### Include a live demo link so that I can run your code. 

https://glitch.com/edit/#!/library-system-with-dependencies?path=librarySystem.js:1:0

### Explain the exact steps I need to take to replicate the problem. 

1. Open the app ~ https://library-system-with-dependencies.glitch.me/
2. Open the developer console.
3. Code inside librarySystem.js is already ran.
4. Code in script tag in index.html is already ran.
5. Observe the result.

### What did you expect to happen? 

I am expecting to see **ReferenceError**. Since one dependency for the _workBlurb_ library is missing (_company_), my application was configured to report **ReferenceError**.

### What actually happened? 

`Uncaught ReferenceError: Library not created, lacks 1 dependencies: company.
    at librarySystem (librarySystem.js:39)
    at (index):22
`

### Describe what you've done so far to troubleshoot the problem. 

Is it a good choice to report **ReferenceError** here or some other type of error?
Is it too cumbersome to provide information about the error like I did? Is it a good practice?
```
throw new ReferenceError(`Library not created, lacks
  ${missingDependencies.length} dependencies: 
  ${missingDependencies.reduce((accum, dep) => (accum + ', ' + dep)) }.
`);
```

**Comment by ugitch** [comment]
James Squillante's opinion is that the generic Error should be used here.

**Comment by gordonmzhu** [comment]
Hey @ugitch. Thanks for providing the additional info I asked for. I have two reactions.

1) Something to consider: If you don't throw any errors and run the following code, will you get an error anyway? If you do get an error anyway, then is it really necessary to throw one? 

```
librarySystem('name', [], function() {
  return 'Gordon';
});
      
librarySystem('workBlurb', ['name', 'company'], function(name, company) {
  return name + ' works at ' + company;
});
```

2) Let's say that you do think throwing an error is worth doing. Now you're concerned about what kind of error you should throw, correct? Think about errors that you've seen. What has made them more or less helpful? The same principles should apply here as well. If you come up with some principles that guide your decision, I'd be happy to give you my feedback on them. But I want to give you the chance to consider them first.

**Comment by ugitch** [comment]
Hey, @gordonmzhu. Thank you for feedback!
1. I do have in mind if the program throws an error or not, without my taking care of. That way I could use it to have less code. In this program, it doesn't, so I decided to throw an error.
2. I can't give too much thought about principles. For now:
   * use the type of error that provides information about the kind of error solely by its name
   * provide other relevant information about the error in the _message_ argument

**Comment by gordonmzhu** [comment]
What you say for #2 sounds reasonable to me. Remember the point of an error message is to communicate the problem. So anything that does that well is probably a good thing.
