### ISSUE TITLE
info, not getting expected output

### ISSUE THREAD

**Issue by zdenaa** [gordonmzhu/questions#247]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/936343  
I'm not getting expected output like in video on 5:55

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/if35yQ7mLKUweiad7NPL?p=preview

### Explain the exact steps I need to take to replicate the problem. 

I'm going step by step with videos, 
![Screenshot_10-1](https://user-images.githubusercontent.com/26312844/59097896-0c9b3300-891f-11e9-9c0a-66316488dbfc.png)
![Screenshot_11](https://user-images.githubusercontent.com/26312844/59097926-2177c680-891f-11e9-9e9d-9426ed3311b4.png)

### What did you expect to happen? 

I expected to get output like on video, because I did all same

### What actually happened? 

There is no error message
![Screenshot_12](https://user-images.githubusercontent.com/26312844/59098014-64399e80-891f-11e9-8dc7-e85679e53595.png)

### Describe what you've done so far to troubleshoot the problem. 

I review code all over again , tried at least 10 times, didn't use debugger

**Comment by ugitch** [comment]
@zdenaa, I saw your issue. Check the code in your displayTodos() method that deals with logging todos. You want to log todo; in one way if todo is completed and in the other way, if it's not completed. That's 2 options. How many options do you have?

**Comment by gordonmzhu** [comment]
Thanks @ugitch.

Yep, the `displayTodos` method is very different from mine. That's why the results are different. I suggest backtracking to find where you deviated from my code. At every step, if you want the same results as me, your code needs to be *exactly* the same.
