### ISSUE TITLE
Handlers Object

### ISSUE THREAD

**Issue by roblew123** [gordonmzhu/questions#248]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/QbmOetsPn8AJfc5nCNqQ?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Not that there is a problem, its more of a general question on how you approached the problem.

### What did you expect to happen? 

I see that you made a new variable named Handlers, so that you can use the onClick method to call to the new object. So you can save space and not use as much code, but why didn't you just call directly from the todoList object, then there would be no added code.

### Describe what you've done so far to troubleshoot the problem. 

I just feel as though it would take a lot less code, and a lot less room if you called directly to the main object, then making an entire new object called handlers. No?

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97.
