### ISSUE TITLE
Question about further defining of variable on todoList.toggleCompleted() function

### ISSUE THREAD

**Issue by paperclipman123** [gordonmzhu/questions#249]
Hi Gordon,

This is a great series for someone with low coding knowledge such as myself, thank you.

I have a question about alternative ways of typing a particular code in the "todoList.toggleCompleted should flip the completed property" lesson.

The code used in the video is as follows and works without issue when I replicate it:

toggleCompleted: function(position) {
    var todo = this.todos[position];
    todo.completed = !todo.completed;
    this.displayTodos();
  }

My question is, why can't I further define var todo so that it is more specified as shown below?

toggleCompleted: function(position) {
    var todo = this.todos[position].completed;
    todo = !todo;
    this.displayTodos();
  }

JS does not seem to recognize that even though logically it seems to be defined properly.

**Comment by gordonmzhu** [comment]
This will be answered later in the interlude on data types and comparisons: https://watchandcode.com/courses/practical-javascript/lectures/938892.

**Comment by paperclipman123** [comment]
Thank you!
