### ISSUE TITLE
Google Chrome Console is not reading plunkerPreviewTarget

### ISSUE THREAD

**Issue by nevtay** [gordonmzhu/questions#25]
### What is the associated Watch and Code lesson? 
- Lesson: https://watchandcode.com/courses/60264/lectures/900211 (Version 3, Lesson 5 - It should store the todos array on an object )
- Timestamp of issue: 2:51

### Include a live demo link so that I can run your code. 
- Live Demo Link: https://plnkr.co/edit/ZWI7A5qT9RPDpwSr428K
- My PC Details: Windows 10, Chrome Version 68.0.3440.106 (Official Build) (64-bit)
  -Chrome version is latest as of 16 August, 2018

### Explain the exact steps I need to take to replicate the problem. 

I followed everything as instructed in the video up to the point of the error.

### What did you expect to happen? 
I expected the console to load the objects as displayed shortly after the timestamp of the issue above.

### What actually happened? 

Despite changing "top" to "plunkerPreviewTarget" in Google Chrome, typing "todoList" in Chrome's console leads to the following error:

"Uncaught ReferenceError: todolist is not defined
    at <anonymous>:1:1"

<img width="960" alt="plunkererror" src="https://user-images.githubusercontent.com/41568907/44200216-a6b7a200-a178-11e8-91c2-18ec7c15c34f.PNG">

### Describe what you've done so far to troubleshoot the problem. 

I've cleared console history. I've tried running the code in Incognito Mode. I've tried using the other options in the same drop-down menu as plunkerPreviewTarget.

**Comment by hydroweaver** [comment]
Hi @nevtay Looks like you haven't followed all the steps, your index.html file is empty!

It should have the following stuff in it, which @gordonmzhu hasn't changed.

`<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
  </head>

  <body>
    <h1>Hello Plunker!</h1>
  </body>

</html>`

**Comment by gordonmzhu** [comment]
Thanks again for the help @hydroweaver!

**Comment by nevtay** [comment]
Hi all,

Just wanted to say a quick thanks for the fast response!

Cheers,
Nevin
