### ISSUE TITLE
Help I'm stuck by '' Function''

### ISSUE THREAD

**Issue by anthonytjonasan1978** [gordonmzhu/questions#250]
### What is the associated Watch and Code lesson?  By VERSION 2 FUNCTIONS: IT SHOULD HAVE A FUNCTION TO DISPLAY TODOS.  3 minutes and 17 seconds.

Write your response here (required). I got stuck, instead of giving FUNCTION etc as a response it gives undefined as a response.

### Include a live demo link so that I can run your code. 

function displayTodos() {
	console.log('My todos:', todos);
}

Write your response here (required). I'm not quite sure by copy pasting it and showing you is the way. But here goes.

### Explain the exact steps I need to take to replicate the problem. 
I followed every little step until it showed '' undefined'' by the '' function '' part.
After trying for several times I started all over again and got stuck by the '' function '' part.
I then copy paste the code and tried to find a solution on google.
I found a similar problem but for a more advanced level.
I followed the instructions and changed my browser from Chrome to Mozilla.
Started the course from the beginning and got stuck again by the ''function'' part.
I then let my partner looked at and tried to find what I was doing wrong.
We both got stuck on the '' function'' part.
Did it both in ''Chrome'' and '' Mozilla''  from the  beginning.
 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Chrome has changed slightly. Now when you type a function definition you get back `undefined`. This is normal.
