### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by weenie666** [gordonmzhu/questions#252]
https://watchandcode.com/courses/60264/lectures/900211

I'm someone who needs to know WHY your doing what your doing, in this video it seems like u just type the array, then copy paste it on the 2nd part & just delete the top, it seems like a lot of unnecessary stuff?!

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Objects are used to group related pieces of data in a single location, as explained in https://watchandcode.com/courses/60264/lectures/900209. This is the same thing we're doing here. Grouping data from our todo list in a single object.
