### ISSUE TITLE
V3 unable to run code.

### ISSUE THREAD

**Issue by JuliusWilliams8944** [gordonmzhu/questions#257]
### What is the associated Watch and Code lesson? 

V3 todos array on an object. 2:28 is the approximate time I'm having an issue.

<p><a href="https://watchandcode.com/courses/60264/lectures/900211?wvideo=r283w2r39y"><img src="https://embed-ssl.wistia.com/deliveries/987fdf9051bc32fda570f298fa94fbebb426637d.jpg?image_crop_resized=800x450&amp;image_play_button_size=2x&amp;image_play_button=1&amp;image_play_button_color=09A59Ae0" width="400" height="225" style="width: 400px; height: 225px;"></a></p><p><a href="https://watchandcode.com/courses/60264/lectures/900211?wvideo=r283w2r39y">It should store the todos array on an object | Watch and Code®</a></p>

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/qGDZhpJAzpXjI03r7KFn?p=info

### Explain the exact steps I need to take to replicate the problem. 

I entered the same exact code as you did. Made sure I hit the run button and then inspect to console. The console states that "todoList" is undefined every time. I triple checked my code and I could not find an error. Maybe there's something I missed along the way?

### What did you expect to happen? 

I expected plnkr to run my code the exact same way as it was in the tutorial, but I get an error instead.

### What actually happened? 

Screenshots posted below.
![D87HY8PmRM20BvamQXYhrA](https://user-images.githubusercontent.com/51384449/60386180-8d010f80-9a57-11e9-9894-f158b3c17804.jpg)
![xE%6bsrGRlqUtXrC3aypNA](https://user-images.githubusercontent.com/51384449/60386181-8d010f80-9a57-11e9-96ca-f505c4ed9fbf.jpg)

### Describe what you've done so far to troubleshoot the problem. 

I watched the tutorial about 4 times now and I get the same result. Me sending this message is currently my form of trouble shooting.

**Comment by gordonmzhu** [comment]
I ran your code and it worked fine. See screenshot.
<img width="1280" alt="Screen Shot 2019-07-01 at 12 46 07 PM" src="https://user-images.githubusercontent.com/734575/60462472-426dc780-9bfe-11e9-9f40-8f271ee67c97.png">

If you continue to have issues, it might be easier to use a regular text editor instead, which should solve the problem. The steps to do so are here: https://github.com/gordonmzhu/questions/issues/1.
