### ISSUE TITLE
Why can HTML access this Js object and not the other?

### ISSUE THREAD

**Issue by Shady960** [gordonmzhu/questions#258]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547 6:00

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/R5aYWsUahQPHbmBOBd5S?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Why not use onclick="todoList.displayTodos() " instead of onclick="handelrs.displayTodos()" ? Is it wrong to do it this way or it's just about best practice?

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97
