### ISSUE TITLE
Uncaught Type error

### ISSUE THREAD

**Issue by damienBlack006** [gordonmzhu/questions#259]
### Include a live demo link so that I can run your code. 
https://plnkr.co/edit/jBQwZzWYw5qejj7hYETc?p=preview

### Explain the exact steps I need to take to replicate the problem. 

When I tried to change todo with the UI button it showed "script.js:30 Uncaught TypeError: Cannot set property 'todoText' of undefined" i don't understand this error. All i know that this a typo and i tried to see where the error lies but i failed. I'm still trying to find the error and if i find it on my own before you do then i will let you know. Also how could this be undefined? 

### What did you expect to happen? 

I thought atleast i won't be stuck with a typo. I thought my codes would run smoothly. 

### What actually happened? 

VM3939 script.js:30 Uncaught TypeError: Cannot set property 'todoText' of undefined
    at Object.changeTodos (VM3563 script.js:30)
    at Object.changeTodos (VM3563 script.js:80)
    at HTMLButtonElement.onclick ((index):19)

### Describe what you've done so far to troubleshoot the problem. 

I rechecked it. then with debugger but it is still giving me the error.
Also what is uncaught type error?

**Comment by gordonmzhu** [comment]
Did you run this through the debugger?

**Comment by damienBlack006** [comment]
yeah . I did but i was lost using it.

**Comment by gordonmzhu** [comment]
Ummm ok. Where did you get lost when using the debugger? That should be your question instead — it's a prerequisite you need to address before we can even discuss your original question.

**Comment by damienBlack006** [comment]
when i was running the debugger in change todo function . It showed the
error exactly at line 33 after putting the debugger inside the function.
'this.todos[position].todoText=todoText'
It is saying uncaught type error: cannot set property  "todoText"  of
undefined.

**Comment by damienBlack006** [comment]
sorry i was not clear the first time.

**Comment by damienBlack006** [comment]
then the debugger stops at line 83
'todoList.changeTodo(changeTodoPositionInput.valueByNumber,
changeTodoTextInput.value)' I have no idea why the debugger stopped here.
Also some reference error saying todoList  is not defined.

**Comment by damienBlack006** [comment]
I found the type error. As you said asking question is important  and all
this time i was asking the wrong ones. I'm happy that i found the typo on
my own Thanks Gordon for telling about
'asking the correct question'. Also let me know if there are any more of
your free courses or projects as i can't afford the paid ones and i wish to
continue. It would be of great help bro if you did that. I just barely
bought my laptop bro. I would be much obliged if you can guide me in any
way.

**Comment by gordonmzhu** [comment]
Good job. Glad you were able to figure out the issue with a little nudging.

The Watch and Code premium subscription is expensive to provide so we are not able to offer access for free. There are a lot of free alternatives out there though.
