### ISSUE TITLE
Instead of deleting the todo I select, it is deleting the first one

### ISSUE THREAD

**Issue by crash180** [gordonmzhu/questions#263]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1148117?wvideo=j2mz1crtph

I am thinking it is related to all of section 10, but cannot be certain. I thought I understood what was going on, but then the delete button is only deleting the first item no matter if I am clicking the 6th or 3rd item in the list of todos.

### Include a live demo link so that I can run your code. 

https://embed.plnkr.co/reWK8BB7CWclXm1tUrFc/

### Explain the exact steps I need to take to replicate the problem. 

1. Load the live preview
2. Add 3 - 5 items of different names that you will remember
3. Click the delete button on the fourth of fifth item
4. Watch as the first item is removed
5. Repeat and it will do it again, deleting the very first item

### What did you expect to happen? 

I expected it only to delete the todo next to the Delete button, not the first entry every time the button is clicked

### What actually happened? 

1. No error to capture
2. When clicking the delete button on any todo, the first item in the list will be removed

### Describe what you've done so far to troubleshoot the problem. 

1. I reviewed section 9 and 10
2. Perform tests by deleting numerous items in the web browser and watching what is happening in the debugger

**Comment by gordonmzhu** [comment]
You have a typo. Go back to a point where your code worked and then work forward from there, making sure that things work at every step. If you do that, you will find your problem.

**Comment by crash180** [comment]
Thank you Gordon,

I will start at section 9 and start forward from there.

Thank you for checking on this for me,

Kevin Eldridge

**Comment by gordonmzhu** [comment]
No problem. The typo will be pretty obvious when you come across it. Inspecting things with the debugger will also pinpoint the issue as well.

**Comment by crash180** [comment]
Hello Gordon!

I found and fixed the issue. I omitted *todoLi.id = i;* from the
*displayTodos* function in the *view* variable.

Apparently, when I was watching the videos, I must have omitted video
https://watchandcode.com/courses/practical-javascript/lectures/1144120

Which is the 6th video in Version 10.

Thank you,

Kevin Eldridge
