### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by Merovingian87** [gordonmzhu/questions#265]
Hey Gordon, love your tutorial! 
I got stuck and need some help:

I have an issue at lesson 10.7:
"Delete buttons should have access to the todo id"
https://watchandcode.com/courses/practical-javascript/lectures/1102312
~2:10.

I cannot declare the <ul> element as a variable, it keeps being "null" and I keep getting this error on the console:
"Cannot read property 'addEventListener' of null"

Basically, I can add a todo to the list but the eventListener on the <ul> won't work to log the event on the console. 

My code:
https://next.plnkr.co/edit/fTVxzPJ0cdwMtVjfZJoX

Note: The only difference between my code and the one on the tutorial, as far as I can tell, is that my code uses a few "modern" JS elements like "let" instead of "var" and "For of" loops instead of regular loops. 

I'm using atom + chrome. 

I've tried declaring the variable again using different names and I also tried using getElementById instead of querySelector. 
While searching on stackoverflow. I found that this:

let foo = document.querySelector("ul");
  if (foo) {
  foo.addEventListener('click', function(parameter) {
    console.log(paramater);
  });
}

It works, but not really because it takes the variable as false, which I don't get. 

Thanks in advance!

**Comment by gordonmzhu** [comment]
Let's make things simpler by making sure your modifications are not breaking things. Write the code as I have, making sure you've followed the steps exactly (removing things like let). When you're 100% sure that you have the same thing, let me know if you still have the issue.

**Comment by Merovingian87** [comment]
Ok will do :)
