### ISSUE TITLE
Why isn't volume remembered for videos?

### ISSUE THREAD

**Issue by HeyItsGwen** [gordonmzhu/questions#267]
### What is the associated Watch and Code lesson? 

All of them.

### Include a live demo link so that I can run your code. 

There's no code

### Explain the exact steps I need to take to replicate the problem. 

Open a video, it's so loud and if i forget to turn it down to 10% my desk vibrates and earthquakes happen in far off lands

### What did you expect to happen? 

To remember the volume i pick between videos.

### What actually happened? 

It didn't remember the volume i picked between videos.

### Describe what you've done so far to troubleshoot the problem. 

Changed the volume and gotten hearing issues for forgetting to change it ever time.

(also I don't have a completion percentage bar anymore. Idk what's up with that. Switched from chrome on an old bad mac to my real pc and it's gone. I like numbers going up, so if I can possibly fix that too. thanks.)

**Comment by gordonmzhu** [comment]
Hey @HeyItsGwen. I suggest turning down the volume on your computer. That should sort things out.

I removed the completion percentage because I want students to focus on more subtle points of understanding, which take time. Number of videos watched is easy to measure but it encourages students to rush through things without absorbing much.

**Comment by HeyItsGwen** [comment]
That's not a solution. You're a programmer, is that really what you come up
with for not having a simple cookie to remember the volume between videos
like every other video player on the internet? The volume on my computer is
tuned to everything else I do on my computer. What a silly attitude to have.
