### ISSUE TITLE
Output is not Coming as i expected

### ISSUE THREAD

**Issue by Bhajarangi** [gordonmzhu/questions#27]
output of my code is not coming as expected and i attached those code below, please check and replay me.

 var NameList = {
                    name: ["ab","def","hi"],
                    displayName: function()
                    {
                      if(this.name.length === 0)
                      {
                        console.log("The name list is empty");
                      }
                      else
                      {
                        console.log("My Name: ");
                        for(var i=0;i<this.name[i];i++)
                        {
                          console.log(this.name[i]);
                        }
                      }
                      
                    },
                    addName: function(namelist)
                    {
                      this.name.push(namelist);
                      this.displayName();
                    },
                    changeName: function(position,changeName)
                    {
                      this.name[position] = changeName;
                      this.displayName();
                    },
                    deleteName: function(position,noofdelete)
                    {
                      this.name.pop(position,noofdelete);
                      this.displayName();
                    }
                  };

**Comment by Bhajarangi** [comment]
With continuation to the above message, if i store number to that list this items are executing in for loop, but when i enter strings to that list its not executing.

**Comment by IvandCodes** [comment]
Please close this issue and recreate it using Gordon's template.
We cannot understand what result you expect from this code.
Also, add your code to some online sandbox so we can just run it, otherwise you are adding the burden of doing that on us which drastically lowers your chances of getting a response ;)

**Comment by gordonmzhu** [comment]
Hey @Bhajarangi — To get a response, you must provide all the required fields in the issue template: https://github.com/gordonmzhu/questions/issues/new?template=Custom.md

See https://github.com/gordonmzhu/questions/issues/1 for an example of a well-formed question.
