### ISSUE TITLE
missing position effects [i]

### ISSUE THREAD

**Issue by CreativeOneDay** [gordonmzhu/questions#273]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/956111 timestamp: 1:28

### Include a live demo link so that I can run your code. 

I got confused with this position (highlighted in bold).

for (var i = 0; i < this.todos.length;i++) {
        if (this.todos**[i]**.completed === true) {
          console.log("(x) ", this.todos[i].todoText);    
        } else {
          console.log("( ) ", this.todos[i].todoText);    
        }
      }  

### Explain the exact steps I need to take to replicate the problem. 

I first forgot the [i] at this specific point (highlighted above). The code was running (adding, displaying, even toggle when looking at the array properties) but one feature did not work: printing out **(x)** for objects that were completed: true. Instead it would print out ( ) for every object. 

### What did you expect to happen? 
Since I forgot the positioning, I would have thought the whole code wouldn't work. Instead in the object specs completed was set to true when toggled but not printed out (x).

### What actually happened? 

The code worked and the array parameter was set to true BUT (x) was not printed out for completed objects.

### Describe what you've done so far to troubleshoot the problem. 

I fixed the code as I compared my code with the example in the video and eventually found the missing [i]. I just can't explain, why the code would work, even setting the right parameter within the array-object, but not print it out.

**Comment by CreativeOneDay** [comment]
On a side note, as I tried to figure it out myself but got more confused :/

If you take the code below, you can push items into the array and they will be displayed nicely. However, if you take out the i when you reference this.todo[i].todoText for consol.logging it out, the loop works but it logs out "undefined". Why? I thought the loop circles through the array and prints out the individual items - one by one. Why does it care about the positions?

I'm sure I just have a little thinking mistake but this detail confuses me so much that right now I am not even sure if I am breathing correctly.

```
var myTodo = {
	todo: [], // array empty since will push objects
	displayTodo: function() {
		console.log("My todos are: ");
		for (var i = 0; i < this.todo.length; i++) { //Syntax of a for loop starts with for
		console.log(this.todo**[i]**.todoText); //the position - i - is key. 
		}
	},

	

	addTodo: function(todoText) {
		this.todo.push({
			todoText: todoText, //first todoText is name of the property on this object, the second todoText is the parameter (can change depending on what you pass in)
			completed: false
		});
		this.displayTodo();
	}
}
```

**Comment by gordonmzhu** [comment]
You should go back to version 1 and review how arrays work and I think that should clarify things. For example, you aren't yet clear on how to access a specific element in an array. Make sure you get that before doing anything else.

Also, when the template asks you to include a live demo link, you should follow the directions and actually do that.

**Comment by CreativeOneDay** [comment]
> You should go back to version 1 and review how arrays work and I think that should clarify things. For example, you aren't yet clear on how to access a specific element in an array. Make sure you get that before doing anything else.

Thx, this is what I'll do. I do think I know how to access a specific element in an array though. What is not logic to me is why the code would run changing the parameter but not logging it out.

> Also, when the template asks you to include a live demo link, you should follow the directions and actually do that.

Thought about it but to which live demo should I've linked? The working or the broken code? This wasn't quite clear.

**Comment by gordonmzhu** [comment]
See https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603
