### ISSUE TITLE
Not able to display todos in console

### ISSUE THREAD

**Issue by marmar32** [gordonmzhu/questions#274]
### What is the associated Watch and Code lesson? 

I am getting this error in console:
Uncaught reference error
I think its stemming from not being able to view the plunkr in console, is it ok to do it from Top?

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Closing due to blank fields.

Please review https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603. Then open a new issue and fill out all the required fields in the template if you'd like assistance.
