### ISSUE TITLE
Trouble getting Plunker set up

### ISSUE THREAD

**Issue by mhiGraphics** [gordonmzhu/questions#275]
### What is the associated Watch and Code lesson? 

Version 3 - Objects / It should store the todos array on an object  / Time 2:44 

### Include a live demo link so that I can run your code. 

https://next.plnkr.co/edit/nwEdMlaDpFUuGWN4?preview

### Explain the exact steps I need to take to replicate the problem. 

I'm using the alpha version of Plunker in Chrome (Mac).
1. Wrote some object code. 
2. Right-clicked on the preview pane & selected "Inspect".
3. Selected the "Console" tab.
4. Clicked on "top" dropdown
5. I don't see plunkerPreviewTarget as an option, so selected "preview (run.plnkr.co/) iFrame"
![Screen Shot 2019-08-12 at 3 26 02 PM](https://user-images.githubusercontent.com/52835124/62892209-a9aa8b80-bd15-11e9-9d1f-ac09ac5d1682.png)
6. Tried to call a value from my "cello" object: "cello.origin" and hit enter
7. This generated an error in the console: "runtime.34ff8150983c47b66c38.js:1 GET https://run.plnkr.co/preview/cjz8rp91g000a3f69hfbh1t8a/jsconfig.json 404"

### What did you expect to happen? 

I expected this result: "Bologna" 
var cello = {
  instrumentClass: 'string',
  noStrings: 4,
  material: 'wood',
  origin: 'Bologna'
};

### What actually happened? 

This error displayed in the console:
runtime.34ff8150983c47b66c38.js:1 GET https://run.plnkr.co/preview/cjz8rp91g000a3f69hfbh1t8a/jsconfig.json 404

### Describe what you've done so far to troubleshoot the problem. 

I tested the same code in the Chrome console (outside of Plunker), as used for the earlier part of the course, and it ran as expected (showed "Bologna"). So the code seems OK.

**Comment by gordonmzhu** [comment]
If you use the stable version (rather than alpha) everything will work the same way it does in the videos.

**Comment by mhiGraphics** [comment]
The classic version of Plunker is buggy; I got a lot of "failed" errors when I tried to save. I'm using CodePen instead, and it seems to be doing the job. Thanks for your reply.
