### ISSUE TITLE
Plunker issue after running the code and choosing PlunkerPreviewTarget

### ISSUE THREAD

**Issue by JriveUSA** [gordonmzhu/questions#277]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/942295

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/jeiY1pQhctPhycmHxfE6?p=info

### Explain the exact steps I need to take to replicate the problem. 

So I ran the code I currently had typed up inside of plunker and then I go to the google chrome console and clicked on top which brought down a list of different options to which I click on the PlunkerPreviewTarget one. Despite me having clicked run before pressing on plunkerpreviewtarget and choosing it, nothing is working when I go to test out my code from plunker in the console. All I keep getting is an uncaught reference error.
### What did you expect to happen? 

I expected it to show me all my todos when I target the displayTodos function from my object todoList and to add a new todo when I target my addtodo function from my todoList function as well. 

### What actually happened? 

https://gyazo.com/53a011eb5dbe334d45da3de9c9947452

### Describe what you've done so far to troubleshoot the problem. 

I used my todosList.displayTodos(); command inside playcode.io to see if it would work and it worked there but I don't think I have a way of testing the addTodos one from there which is why I really wanted the google chrome console to work properly with the code I have written up in plunker. 

Also when I hover over PlunkerPreviewTarget option, its only highlighting the output section of plunker but I dont know if its supposed to be that way or not. Link to it below.
https://gyazo.com/cb781af89799e3ddc5d738f6ac972d16

**Comment by JriveUSA** [comment]
Also I have just tried out my code on a different tab purely on the google chrome console and everything worked out great but i'm still really confused as to why its not working right along side of plunker.

**Comment by gordonmzhu** [comment]
Your index.html file is blank. This is not the case in the videos. 

Slow down, go back and make sure your index.html is the same as mine and things will work. Precision is important. Your issue reminds me of this https://watchandcode.com/courses/rough-drafts/lectures/10569149.
