### ISSUE TITLE
Plnkr doesn't seem to work

### ISSUE THREAD

**Issue by gt44m** [gordonmzhu/questions#28]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/900211

I am trying to use Plunker for the first time as per this lesson. I have Chrome and have successfully used the console with it so far. However, when I use Plunker, I see an error that says: 

VM1207:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) @ VM1207:1

![image](https://user-images.githubusercontent.com/42483299/44294202-5c055b00-a248-11e8-89b0-2843887f48bb.png)

Write your response here (required).

### Include a live demo link so that I can run your code.

Write your response here (required).

Should I use Safari instead? Would like to get this working in Chrome if possible.
http://plnkr.co/edit/shH1MOHcWlCDl4Lfeg2U?p=preview

### Describe what you've done so far to troubleshoot the problem. 

I disabled all extensions. Started a new project, wrote the code, no dice.

Write your response here (required).

**Comment by IvandCodes** [comment]
That happens because your index.html file is empty and it does not have the link to your script.js
When you "Run" plunker, it shows you the empty HTML file that has no JS code at all.
Hence the error "There is no todoList".

**Comment by gordonmzhu** [comment]
Thanks for helping out @IvandCodes! Yep, you're index.html is not formed as it should be. I suggest going back in the course and following the directions exactly so that you see how the index.html should look.

**Comment by gt44m** [comment]
Indeed, thought I had it. Thanks for the quick responses.
