### ISSUE TITLE
parseInt() vs .valueAsNumber

### ISSUE THREAD

**Issue by jenkc** [gordonmzhu/questions#283]
### What is the associated Watch and Code lesson? 

Practical JavaScript - Version 10 - Clicking delete should update todoList.todos and the DOM

Question: What is the difference between parseInt() and .valueAsNumber and under what circumstances should we use each of them?

**Comment by gordonmzhu** [comment]
See:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

They're slightly different as explained in the docs above. To answer your question, see if you can use them interchangeably. If not, that might point to a significant difference. If you can use them interchangeably, consider the pros and cons of using one approach over the other.
