### ISSUE TITLE
I am working through Watch and Code JS. It's a very informative course. Is there more details about the monthly class - do we build projects or solve problems?

### ISSUE THREAD

**Issue by fwallacephd** [gordonmzhu/questions#284]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You can find more info at  https://watchandcode.com/p/premium. I also talk about it here https://watchandcode.com/courses/60264/lectures/9604319.
