### ISSUE TITLE
Still not seeing progress as percentage completed on top despite clicking top right CTA

### ISSUE THREAD

**Issue by andrew678** [gordonmzhu/questions#285]
Tried clicking the complete and continue CTA as I moved onto next videos. Not even seeing it at 0%. 

Screenshot attached.

![image](https://user-images.githubusercontent.com/55116340/64574874-0190de00-d326-11e9-82e1-79cb1e0781c7.png)

Thanks,

A

**Comment by gordonmzhu** [comment]
There is no percentage bar anymore.
