### ISSUE TITLE
Q: Using todoList object as opposed to handler

### ISSUE THREAD

**Issue by edmanHoesmadie** [gordonmzhu/questions#287]
Watch and Code lesson: Version 8 - Getting Data from Inputs, More on refactoring
https://watchandcode.com/courses/60264/lectures/1027791

Hi Gordon, this not about an Issue or a problem, just a silly question.
Just occurred to me while I was working on the lesson and creating the new object handlers,
couldn't you just use the todoList object directly? 

for example in html:
`<button onclick="todoList.toggleAll()">toggle</button>`

 as opposed to

`<button onclick="handlers.toggleAll()">toggle</button>`

They both work, is there a reason why we need to create a new object handler?

Glitch project-->https://glitch.com/~eds-task-list

Thank you
-Edman Hoesmadie

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97.
