### ISSUE TITLE
It should store todo array on object: I can't open console in plunker.

### ISSUE THREAD

**Issue by BuoRotti** [gordonmzhu/questions#289]
### What is the associated Watch and Code lesson? Lesson on "It should store todo array on object".
Failed to load resource: the server run.plnkr,co/plunks/...6ku/jsconfig.json:1 responded with a status of 404()
Write your response here (required).  I copied down the error messages and After i failed to find the error searched, I decided to write To Gordon.

### Include a live demo link so that I can run your code. https://next.plnkr.co/edit/oMwtGqY6pIwfY6KU?preview

Write your response here (required). yes I had copied the link to my plunker account.

### Explain the exact steps I need to take to replicate the problem. I was and am using firefox and chrome ...but the last one happened also in Chromium.I tried to open console by right clicking on jscript widget ( the code we supposed to work on version 3 object - file todoList...What listed only command pallet F1...No list of option to select open console through right click and choose inspect, then choose console...none whatsoever...
The but I was able to open it through right click the outcome widget to the right of editor widget of javascript...( the one has out put Hello Plunker! ).
under the console tab → preview(run.plnkr.co/)IFrame is selected with background pink color.

Write your response here (required).

### What did you expect to happen? I 
expected to be able to select the "plunkerPerviewTarget(run.plnkr)"...but it was not available..
Write your response here (required).
I wrote down what I saw and found.
### What actually happened? 
Failed to load resource: the server run.plnkr,co/plunks/...6ku/jsconfig.json:1 responded with a status of 404(); And also-> 
And then after I typed in “todoList” in the Console another error showed up :

VM1527:1 Uncaught ReferenceError: todoList is not defined     at <anonymous>:1:1
(anonymous) @ VM1527:1

Write your response here (required).
I wrote down the error message to be sent to Gordon.
I did research the error on google.
### Describe what you've done so far to troubleshoot the problem.  No I did redo the step on running the code to get the result:Hello Plunker!  according to instruction.

Write your response here (required).I ascertained the errors were consistent.They were consistent.

Thank you for your help.Buonar.

**Comment by gordonmzhu** [comment]
Hey @BuoRotti if you're having trouble with Plunker, you can just use a normal text editor instead. I explain the steps for doing so in this issue: https://github.com/gordonmzhu/questions/issues/1.
