### ISSUE TITLE
The delete button (with input field) deletes to do's without anything in the input field.

### ISSUE THREAD

**Issue by TheAlexPark** [gordonmzhu/questions#29]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1102309
(This is the URL of when I found this "bug" not necessarily having anything to do with the bug itself. But it does show that this "bug" is found prior to creating individual delete buttons for each to do)

### Include a live demo link so that I can run your code. 

https://actually-alto.glitch.me

### Explain the exact steps I need to take to replicate the problem. 

1. On Safari, added two "to do"s. Specifically, they were "first" and "second".
2. Hit "Toggle All" button twice.
3. Hit the delete button without entering anything in the input field.

### What did you expect to happen? 

Expected nothing to happen when pressing the delete button (with nothing entered into the input field).

### What actually happened? 

The "to do" were deleted one by one, starting from the first one.

### Describe what you've done so far to troubleshoot the problem. 

I went into the HTML code and the JS code to see what the delete button was doing and it asks for whatever is in the input field, then returns its value "as a number". My hunch is that a blank field is being returned as "zero" instead of undefined or null, thereby causing the delete button to erase the to dos starting at the top of the todo list. As such, I console.log the deleteTodoPosition input both by itself and .valueAsNumber, and it turns out the former is blank and the latter is NaN. 

**How then is NaN causing the 0th item in the to do list to be selected (and deleted)?** To experiment, I created an array eg var a = [1,2,3]; and tried to selected a[NaN], which didn't work -- it returns "undefined". So that's not going to work, yet in the app, the to do items get deleted somehow.

**Comment by gordonmzhu** [comment]
Yep good catch and nice job experimenting with different scenarios.

If you `splice` use `NaN` as the position, it'll delete starting at index 0. This is unlikely to be what you want, so you can add checks to make sure this isn't happening beforehand like @IvandCodes suggested.

**Comment by gordonmzhu** [comment]
Hey @IvandCodes —  Send an email to gordon@watchandcode.com with your mailing address. I'd like to send you some stickers (if you're interested) to thank you for helping out with questions.

**Comment by TheAlexPark** [comment]
Thank you both. That was concise. Just wondering now why array[NaN] returns undefined instead of the first element, if NaN is falsy and translates to zero, eventually. I suppose it only "works" for certain built-in methods such as splice?

**Comment by IvandCodes** [comment]
@gordonmzhu , thanks for clarification and for the link to the ES5.1 standard!

**Comment by gordonmzhu** [comment]
@IvandCodes No problem! Yeah when you're not sure about something and want to know exactly how something works, you'll want to look at the spec. It's a bit tiring to read, but there's really isn't any other option :)
