### ISSUE TITLE
Cannot preview plunker on chrome console

### ISSUE THREAD

**Issue by ruthyclark** [gordonmzhu/questions#290]
### What is the associated Watch and Code lesson? 

Version 3 objects; lesson 5: It should store the todos array on an object https://watchandcode.com/courses/60264/lectures/900211

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/UgbrhZeIf9DM0HynSmjb

### Explain the exact steps I need to take to replicate the problem. 

In the video you click inspect to open the console, then change the dropdown list to change the option to "plunkerPreviewTarget" This is not an option in my console

![image](https://user-images.githubusercontent.com/31045537/65184025-b2882e80-da32-11e9-8adf-a23ac0cae7fe.png)

### What did you expect to happen? 

Based on the video I expected that same option to be there.

### What actually happened? 

The selection is not coming up as an option.

### Describe what you've done so far to troubleshoot the problem. 

I tried choosing other options on that page or refreshing.

**Comment by Reebes72** [comment]
Hi, I don't know if you've found a solution for this, but I had the same problem you did and found a solution that made plunkerPreviewTarget appear for me.

For some reason, even though I had clicked run on the Plunker site, after Inspected and opened up the Console it had been toggled off. If you click the Run button again and make sure it changes to a stop button, you should be able to select plunkerPreviewTarget. 

Hope this helps!

**Comment by gordonmzhu** [comment]
You have to hit the play button.
