### ISSUE TITLE
Wrong videos on Watch and Code (analysing literature)

### ISSUE THREAD

**Issue by portugueseninja** [gordonmzhu/questions#292]
Hi Gordon!

I was just working through the section called "Interlude - Data Types and Comparisons" but then when I get to the Code Examples, the thumbnail on the image looks correct but then when the videos play they are actually about analysing a literature passage for the CB test.

Not sure if this is a known issue but I figured I'd mention it just in case.

Joey

**Comment by MarckBamaca** [comment]
Hey I am also facing this along with a 504 error sometimes if i try and launch from a different browser or incognito mode

**Comment by gordonmzhu** [comment]
Sorry about this. It was a known issue that has since been resolved. Some context: https://twitter.com/gordon_zhu/status/1175107445057679361
