### ISSUE TITLE
Videos are not showing up for Practical Javascript

### ISSUE THREAD

**Issue by SyHurdle** [gordonmzhu/questions#293]
### What is the associated Watch and Code lesson? 

None of the Videos are working for me. They were working just fine and I went out of town for a little bit and now I am back and wanting to resume the course but when I click on any video it just gives me a blank screen for all of the lessons. I've restarted, used different browsers and am fairly certain I don't have anything blocking your site so I'm not to sure what to do.

### Include a live demo link so that I can run your code. 

n/a

### Explain the exact steps I need to take to replicate the problem. 

n/a

### What did you expect to happen? 

n/a

### What actually happened? 

n/a

### Describe what you've done so far to troubleshoot the problem. 

restarted computer, logged out and in, checked for anything blocking the content, used different browsers.

**Comment by SyHurdle** [comment]
well right after i made this issue i refreshed the page again after trying for a little bit and it just worked so disregard sorry and thank you

**Comment by gordonmzhu** [comment]
Glad it worked out. Thanks for updating the issue.
