### ISSUE TITLE
My Response 

### ISSUE THREAD

**Issue by DevHabib** [gordonmzhu/questions#294]
### What is the associated Watch and Code lesson? 

I did't had any issues.

### Include a live demo link so that I can run your code. 

http://next.plnkr.co/plunk/DAs0XpKqm1GwUvRTsxk0

### Explain the exact steps I need to take to replicate the problem. 

I use chrome I had no problems on Chrome but When I try to watch videos on opera i can see the video but audio is muted.

### What did you expect to happen? 

I can learn code easily

### What actually happened? 

No errors.

### Describe what you've done so far to troubleshoot the problem. 

I have completed version 1 to 10 and still learning.
One of the best tutorial I have ever found in online. 
Thanks a lot for this

**Comment by gordonmzhu** [comment]
You're welcome. Didn't see any question in this so closing the issue. Let me know if there's something I'm missing.
