### ISSUE TITLE
Trouble running displayTodos in the v3, objects lesson

### ISSUE THREAD

**Issue by FujiBou** [gordonmzhu/questions#296]
### What is the associated Watch and Code lesson?  https://watchandcode.com/courses/60264/lectures/936334

Write your response here (required).
I followed along and had the code written the same way, but I keep getting an error satying my todoList wasn't defined. I've scanned it so many times for typos, I've even changed the capitalization to exactly match the video as well. It 
### Include a live demo link so that I can run your code.  https://embed.plnkr.co/rAyPYhrPgeW7Y3F3G2FT/

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
I just followed along to the video and didn't really deviate from the code. I've ran it in chrome on plunker, codepen.io, and bracket but I mean I guess that's all the same anyway? 

### What did you expect to happen? 

Write your response here (required).
I expected the todoList.displayTodos(); to run the anonymous function, which doesn't need to be called because we're using the property name of displayTodos instead. 

### What actually happened? 
![TDL error](https://user-images.githubusercontent.com/55768295/65562088-fd161900-df12-11e9-895f-7b138efab2c1.jpg)

Write your response here (required).
Error in defining the variable 'todoList', not too sure on future steps I can take htough, besides just attempting to dissect my code as much as I can- which I've definitely over-done if anything at this point. I'm just thinking I'm really overlooking something simple, but I can't see it for myself. 

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I've rewatched the video a bunch and re-written the code numerous times the exact way it was in the video. I'm aware of the danger of just straight copying code and being satisfied with the end result, but I was hoping I could at least have the code run correctly and then compare that to what I had, although honestly what I had was basically the same thing anyway, with the only differences being capitalization such as "toDoList" instead of "todoList"- but I always made sure i logged out the correct variable capitalization to the console. I feel like I literally made the smallest dumbest typo or something and I just can't find it, if the solution is obvious I'd appreciate at least a hint at what it could me. Sorry I feel like getting stuck up on something this early on in the course is a sign I need to be more diligent or something, but I literally don't know how I can really analyze what I've done wrong for this. 

I'm sure I'm doing something weird that's messing with the 'todoList' variable, but I'm really unsure as to how I'm doing it. Any insight at all would be great, this is literally my first few days of picking up code but I won't be offended at all at any criticism at all or anything! Thanks so much, your course has been great by the way!

**Comment by gordonmzhu** [comment]
You need to go back and redo things. Your files are not structured like mine.

For example, I have HTML in my index.html and my JavaScript in script.js. You're putting your JavaScript in index.html, which is completely different.
