### ISSUE TITLE
version 4

### ISSUE THREAD

**Issue by Iwcode3** [gordonmzhu/questions#299]
### What is the associated Watch and Code lesson? 

Version 4- Booleans

https://watchandcode.com/courses/60264/lectures/946811, 

timestamp: 3:07

Write your response here (required).

hey Gordon.  I'm attempting to flip the value of todo from false to true.  But my code is not working and its identical to the lesson.

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/k0ZjfWeGiUnMux6qHtaY?p=preview

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened?  

<img width="615" alt="E" src="https://user-images.githubusercontent.com/32726261/65702606-27152b80-e038-11e9-9c64-db3e16af7977.png">

<img width="410" alt="g" src="https://user-images.githubusercontent.com/32726261/65702417-ce459300-e037-11e9-8fea-d2ab3c3dc507.png">

rite your response here (required). 

### Describe what you've done so far to troubleshoot the problem. 
Write your response here (required).

**Comment by gordonmzhu** [comment]
Your code is not the same. You have many many typos. I counted at least 3 within 20 seconds. Make sure it's the same and then try again.
