### ISSUE TITLE
Plnkr Preview list not an option on my Google Chrome

### ISSUE THREAD

**Issue by mcollums** [gordonmzhu/questions#30]
https://watchandcode.com/courses/60264/lectures/900211 
Timestamp 2:46

I was using Plunker and tried to open up the console to select the Plunker Preview List but I didn't see it as an option. The options available are the ones screenshot below. 

I selected both "top plnkr.co" and "worker-javascript.js" and tried to run the variable but it didn't retrieve my code from the version 3 plunk.

<img width="329" alt="screen shot 2018-08-19 at 1 20 08 pm" src="https://user-images.githubusercontent.com/37056419/44311742-a276c900-a3b2-11e8-9cf8-4be354d55d25.png">
<img width="329" alt="screen shot 2018-08-19 at 1 20 03 pm" src="https://user-images.githubusercontent.com/37056419/44311743-a276c900-a3b2-11e8-9a95-bfe71a3edd6f.png">

**Comment by IvandCodes** [comment]
You did not provide enough information about your issue, but I suspect that you forgot to **run** your code in Plunker before trying to access it with the Chrome Console.

**Comment by gordonmzhu** [comment]
Hey @mcollums. Please open another issue and fill out the required fields and I'll be happy to take a look.

https://github.com/gordonmzhu/questions/issues/new?template=Custom.md
