### ISSUE TITLE
Delete button next to the item won't delete the item

### ISSUE THREAD

**Issue by jovanimal** [gordonmzhu/questions#300]
### What is the associated Watch and Code lesson?
Lesson 10. https://watchandcode.com/courses/60264/lectures/1102313 (time 5:14)

### Include a live demo link so that I can run your code.
https://glitch.com/edit/#!/join/5216261e-88c6-4a97-880c-e09141f0051b

### Explain the exact steps I need to take to replicate the problem.
I clicked on the 'delete' button but it won't delete the item in the Todo List. 

### What did you expect to happen?
The item next to it will be deleted after I clicked on the 'delete' button.

### What actually happened? 
The item can't be deleted, nothing happened.

### Describe what you've done so far to troubleshoot the problem. 
I've checked the code again and make sure there is no error.

**Comment by gordonmzhu** [comment]
Did you run the code through the debugger?
