### ISSUE TITLE
My console doesnt have access to plnkrpreviewtarget

### ISSUE THREAD

**Issue by giogrigio** [gordonmzhu/questions#301]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
If you'd like a response, open a new issue and fill out all the fields. As mentioned in the issue form, each field is required.
