### ISSUE TITLE
Understanding Splice

### ISSUE THREAD

**Issue by zmagickap** [gordonmzhu/questions#302]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/923806

### Include a live demo link so that I can run your code. 

Write your response here (required).
n/a

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
Documentation says splice REMOVES items from an array and RETURNS the removed items.
Yet what we see in our examples is the array with the removed items.

### What did you expect to happen? 

Does that mean we could have two arrays -- the one returned from the splice function and which contains the removed items; and the original with only the remaining items?

**Comment by gordonmzhu** [comment]
`return` is a very specific concept that you haven't learned about yet. It'll appear later in the material. For now, all you should notice is how `splice` affects the array. For example, if you run `['a', 'b', 'c'].splice(0, 1);`, the first element ('a') will be removed.
