### ISSUE TITLE
Semicolons still needed?

### ISSUE THREAD

**Issue by zmagickap** [gordonmzhu/questions#303]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/928384

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

From what I'm reading online, modern JS no longer requires semi colons at end of lines, yet you encourage them, here. What's your thinking on that?

**Comment by gordonmzhu** [comment]
Always use semicolons.
