### ISSUE TITLE
todoList.toggleCompleted should flip the completed property

### ISSUE THREAD

**Issue by Oxmodius** [gordonmzhu/questions#304]
### What is the associated Watch and Code lesson? 

Write your response here (required).

https://watchandcode.com/courses/60264/lectures/946811  --> timestamp: 4:46

### Include a live demo link so that I can run your code. 

Write your response here (required).

https://plnkr.co/edit/dCDfOk9tcFwKObJoZDyE?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

the todoList.toggleCompleted function does not work properly. I have made sure that my code is verbatim to yours.

### What did you expect to happen? 

Write your response here (required).

I was expecting the function to work, but I get an error.

### What actually happened? 

Write your response here (required).
I end up getting an error that displays: 'Uncaught TypeError: Cannot read property 'completed' of undefined at Object.toggleCompleted (script.js:23)

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

I made sure I have copied everything you have done in the video, but I still have not been able to fix it.

**Comment by gordonmzhu** [comment]
I just ran the toggleCompleted function and it worked fine. If you're having trouble under a specific use-case, please elaborate with step-by-step directions so I can reproduce the issue.
