### ISSUE TITLE
Property assignments

### ISSUE THREAD

**Issue by zmagickap** [gordonmzhu/questions#305]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/900209

### What did you expect to happen? 

Write your response here (required).
One area I struggle with is knowing when to use : and when to use = for assignments.

In your intro to Objects, you point out that properties use colons to assign values.

Can you help me with a way to lodge that in memory? I keep thinking an equal sign is more intuitive. So, is there a rationale or meme or something that can help me know to use colons for property value assignments?

**Comment by gordonmzhu** [comment]
You answered your own question. Only use colons when assigning object properties.
