### ISSUE TITLE
Curly Braces

### ISSUE THREAD

**Issue by zmagickap** [gordonmzhu/questions#306]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/900210
Lesson 3: Objects & Functions

### Include a live demo link so that I can run your code. 

Write your response here (required).
[https://www.screencast.com/t/F389omPbSr3v](url)

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

Another area I get lost in is when to use curly braces vs parenths.

Earlier in the course, you explained that we create objects by enclosing them in curly braces. That makes sense and I think I have that down.

But, then you have a function inside an object and that function also uses curly braces. (see screencast, above).

Can you help me with a memory jog to know when to use curly braces and when to use parenths? To me, parenths after a function feel more intuitive.

I have no problem following the logic of curlies in lessons or when looking at code, but if I'm writing my own, I keep screwing it up.

**Comment by gordonmzhu** [comment]
The logic is always consistent. So if you're not sure, go back and look at how things should be.

As you noted, objects use curly braces. If you look at functions, they always use braces too. You don't need to worry about memorizing. If you're not sure, just go back and look.
