### ISSUE TITLE
'this' keyword

### ISSUE THREAD

**Issue by ejitex** [gordonmzhu/questions#307]
### What is the associated Watch and Code lesson? 

Hi Gordon,

Thanks for the good job you did providing watchandcode tutorial. I'm wondering why 'this' keyword is not needed when using 'completed' property in 'toggleTheCompleted' method. For instance, when you wanted to use 'todos' array property of the object 'toDoList' you use 'this' keyword to reference to the object but not used when accessing property 'completed'.
![Screenshot1](https://user-images.githubusercontent.com/36595711/65945210-ca4cb300-e433-11e9-890f-8ac0dd075a6d.png)

thanks,
Ken

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
What is the associated Watch and Code lesson?

**Comment by ejitex** [comment]
Yes, Version 4 - Booleans last requirement!

**Comment by gordonmzhu** [comment]
You say we aren't using `this` in the second line of `toggleCompleted` method, but are you sure about that? Take a second and think about what `todo` is equal to in the first line.

**Comment by gordonmzhu** [comment]
Closing due to 5 days of inactivity.
