### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by zmagickap** [gordonmzhu/questions#308]
### What is the associated Watch and Code lesson? 

Write your response here (required).

Conclusion of the course

You say our sole criteria for whether to continue is the progress we made in Practical. But you also say Premium doesn't hold our hand the way Practical does. So, we really don't know if Premium will be as helpful because it sounds like you conduct the training quite differently.

**Comment by gordonmzhu** [comment]
The way progress happens at each level is different and is not important. It's like that saying, "what got you here won't get you there".
