### ISSUE TITLE
Question regarding to Practical Javascript lesson Version 8 video 4 - <<there should be a button for adding todos>>

### ISSUE THREAD

**Issue by johnjohnG** [gordonmzhu/questions#309]
### What is the associated Watch and Code lesson? 

Write your response here (required).
Practical Javascript lesson Version 8 video 4 - <there should be a button for adding todos> time stamp 6:06
https://watchandcode.com/courses/60264/lectures/1027557
### Include a live demo link so that I can run your code. 

Write your response here (required).
Here is my Glitch link
https://glitch.com/~surf-swoop
### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
Same as the video, except I assigned the input value to the variable
`let inputText = document.getElementById('addText').value;` and  `inputText='';`
### What did you expect to happen? 

Write your response here (required).
I am expecting it will be the same as the tutorial.
The reason is, in the video it assigned the input element to a variable then passing the variable's value into the function, finishing by reassigning the value back to empty in order to keep the input field empty. 
So I thought why not assign the element's value to the variable straight, save some extra typing and potential typo, however, when doing the reset input value to empty, it didn't work. 
### What actually happened? 

Write your response here (required).
relevant line of code
`     addTodo:function(){
        let inputText = document.getElementById('addText').value;
        todoList.addTodo(inputText);
        inputText='';
        console.log('input'+inputText);
    }`

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I have tried using console log to see what's the actual value in the input, why it didn't pass to the element, however, in the console log it shows the value is empty, but the input field is not updated. Also tried to assign the vaule to "undefined", didn't worke either. So I am not sure....

**Comment by gordonmzhu** [comment]
If you carefully review the interlude on "Data types and comparisons" you'll find out why. Try drawing the diagrams I suggest in that section.

https://watchandcode.com/courses/60264/lectures/938892

**Comment by gordonmzhu** [comment]
Once you review that section, let me know what you find.

**Comment by johnjohnG** [comment]
> Once you review that section, let me know what you find.

Thanks Gordon,
my variable is assigned to a value instead of value inside a memory address, then I want to update the value inside the memory address through the variable just contains value instead of the memory address which is not doable. Your graph is better than my words explanation... Thanks :)
It's an awesome course so far

**Comment by gordonmzhu** [comment]
Right on the money! Good job!
