### ISSUE TITLE
Callback functions and variable scope

### ISSUE THREAD

**Issue by TheAlexPark** [gordonmzhu/questions#31]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1181255

### Include a live demo link so that I can run your code. 

https://actually-alto.glitch.me
(This won't really matter as the question is relevant to the final todo app code that everyone should have at the end of the Practical JS course).

### Explain the exact steps I need to take to replicate the problem. 

This doesn't have anything to do with the todo app itself. The question is about the todosUl variable on line 87. In case it isn't line 87 for other people, I'm referring to todosUl inside the callback function in the .forEach inside the view.displaysTodo method.

### What did you expect to happen? 

When following along with the video, nothing stood out to me. As I wrote the code, however, I wondered how the todosUl variable was found inside the callback function. Is this another circle and arrows problem? That is, because the callback function is inside the view.displaysTodos method, the todosUl variable is accessible from inside the callback function? 

### What actually happened? 

No error. It works.

### Describe what you've done so far to troubleshoot the problem. 

Looked up "javascript and callback functions and variable scope" on search engines but just got confused as none of the results (on the first page anyway) really nailed the answer in any clear concise high-level view way. For now, I'm thinking even though a variable that had been defined outside the callback function is accessed inside a callback function, the callback function is like any other function that is nested in another function, i.e. nested functions can access variables in the parent function **without being explicitly passed in** (unlike the "this" keyword that needs to be passed in).

**Comment by IvandCodes** [comment]
Hi! We cannot see your actual code from the link you provided.

Please use the "edit" mode when providing the link. I reconstructed you link here [Glitch](https://glitch.com/edit/#!/actually-alto?path=public/client.js:87:0) to the "edit" mode.

**Comment by gordonmzhu** [comment]
```Is this another circle and arrows problem?```

Yep! Draw the diagrams and you'll see it works exactly the same way.
