### ISSUE TITLE
.push not working

### ISSUE THREAD

**Issue by osasnat** [gordonmzhu/questions#313]
i get an error wen i try pushing an item into an array
name
"osas,mike,uche,osahon"
console.log(name)
VM1570:1 osas,mike,uche,osahon
undefined
name.push('jess')
VM1616:1 Uncaught TypeError: name.push is not a function
    at <anonymous>:1:6
name
"osas,mike,uche,osahon"
name.splice(1, 1)
VM2055:1 Uncaught TypeError: name.splice is not a function
    at <anonymous>:1:6

**Comment by gordonmzhu** [comment]
This is not valid code. Follow along with the videos on arrays to see how they work.
