### ISSUE TITLE
Console Results Looking Different From Examples

### ISSUE THREAD

**Issue by trwexler** [gordonmzhu/questions#314]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/900210
Version 3 - Objects - Objects and Functions: 2:17

Hey Gordon, love the class so far. I am seeing slight differences on my console than what you are getting however. This is not the first time, but i wanted to make sure it's just a version change/update (I suspect) and not something more significant. 

Thanks again,
Tom Wexler

![image](https://user-images.githubusercontent.com/47966330/66689204-fba95800-ec57-11e9-9663-71bdda7c649a.png)

**Comment by gordonmzhu** [comment]
Hey Tom. Just a version thing with Chrome. Chrome changes over time so output can look slightly different.
