### ISSUE TITLE
Version 3 - Add toDo Method to an Object

### ISSUE THREAD

**Issue by joannapham** [gordonmzhu/questions#316]
### What is the associated Watch and Code lesson?  https://watchandcode.com/courses/60264/lectures/942295 - Min. 2:50

Write your response here (required).
Hi Gordon! 

I'm trying to add the addTodo Method in my object but the word "plunker" is not showing up in my code...what am I doing wrong??

<img width="738" alt="10-23-2019 9-19-50 PM" src="https://user-images.githubusercontent.com/56797204/67453344-4ffaf300-f5db-11e9-93fa-4eef89fb9cfa.png">

As a side note, coding is already so confusing to me, but I'm trying my best and you're really good at explaining things :)

Thank you in advance!

Joanna
### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by zeelib1** [comment]
Hi Joanna, just a fellow student on W&C. I hope you fixed it. What I can see, there's a little typo. Practice makes perfect. Gl!

**Comment by gordonmzhu** [comment]
You aren't getting what you expect because you have typos. That is also why you're getting errors. Go through your code character-by-character and find all of your typos and the issue will go away.
