### ISSUE TITLE
How to trigger the button click on addToDos using the enter button.

### ISSUE THREAD

**Issue by harrywalker94** [gordonmzhu/questions#318]
Version 8 - Getting Data From Inputs
There should be a button for adding todos - https://watchandcode.com/courses/60264/lectures/1027554

Hi Gordon,

First of all I just wanted to say how much I am enjoying learning JS through your techniques, it's really helping me develop and understand concepts and fundamentals a lot better.

I know this is not part of your material included within the video however, I would like to trigger the addToDo button text when I click 'enter' on the keyboard. I have been doing my own background research and have come up with this conclusion.

https://plnkr.co/edit/hcbXdewam9CyEHqkKBlm?p=preview

The issue I am having is, that when I type just one letter into the submit box, it automatically enters and will only allow me to enter one letter at a time.

To replicate the problem, try inserting a letter or number into the 'Some text...' field.

I expected for it to allow me to enter the text and when I click the enter key, it will add to the toDoList.

I hope this is enough information.

I hope to hear from you soon.

Regards,
Harry

**Comment by gordonmzhu** [comment]
In line 92 of script.js, you're running a function on every 'keyup' event. Do you fully understand how 'keyup' works? Once you do that research, you'll realize, it's not the best fit for what you're trying to do.
