### ISSUE TITLE
Practical JS function issues

### ISSUE THREAD

**Issue by XanMan336** [gordonmzhu/questions#320]
"It should have a function to display Todos" (Practical JS free)

https://watchandcode.com/courses/60264/lectures/928384

3:18

http://run.plnkr.co/plunks/tomtFrHEXxpypkdxaJEi/

Write your response here (required).

I typed in the code but Google console returned "undefinded" instead of the exact same arrays

I expected the console to return the same input as what is seen in your practical JS lessons.

It returned "undefined"

I've played around with the spacing & testing whether todos & the ('My todos:' todos) array would work. They did. Var and function didn't. 

<img width="960" alt="display function not working" src="https://user-images.githubusercontent.com/57318830/68154010-9f62ec80-ff14-11e9-8374-db4ffc8f7d72.png">

**Comment by gordonmzhu** [comment]
When you say, "I typed in the code but Google console returned "undefinded" instead of the exact same arrays", what code did you type?
