### ISSUE TITLE
toggleCompleted(1); not working for displayTodos 

### ISSUE THREAD

**Issue by XanMan336** [gordonmzhu/questions#324]
### What is the associated Watch and Code lesson? 

Version 5-Loops of Magic, 3:30 onwards

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/ZtU1OUZWMjJNkWXweec3?p=info

### Explain the exact steps I need to take to replicate the problem. 

Nothing; I get an error code regarding the toggle function and the parenthetical tick-boxes don't work

### What did you expect to happen? 

I expected (X) and ( ) to show up

### What actually happened? 

I tried typing in "todoList.toggleCompleted(1);" and got:

VM3295:34 Uncaught ReferenceError: todos is not defined
    at Object.toggleCompleted (<anonymous>:34:5)
    at <anonymous>:1:10

### Describe what you've done so far to troubleshoot the problem. 

I tried aligning all the brackets in the right location to line up with the brackets you have in your video. I tried going back and seeing how the toggleCompleted function is supposed to be coded. Everything looks fine to me, I ran PLNKR and entered the entire code into the console to "prime it" or declare/define it (whatever the right industry terminology is). When I attempted to toggle the code for the 2nd item in the todoList by denoting it with "1" in the parantheses, all I get is an error message so now I'm just stumped.

**Comment by gordonmzhu** [comment]
Closing since student notified me that they figured out the problem
