### ISSUE TITLE
Plunker console is not reading my code.

### ISSUE THREAD

**Issue by sofianiu** [gordonmzhu/questions#328]
Hi Gordon,

Thank you for creating this course. Here's my question:

### What is the associated Watch and Code lesson? 

[V3 - Plunker.](https://watchandcode.com/courses/60264/lectures/900211)

### Include a live demo link so that I can run your code. 

[My Plunker.](https://plnkr.co/edit/4j1rLn?p=info)

### Explain the exact steps I need to take to replicate the problem. 

The console (PlunkerPreviewTarget) does not recognize any of my code.

### What did you expect to happen? 

I expected the console to be able to run my functions.

### What actually happened? 

[Screenshot.](https://imgur.com/a/vlB0CWW)

### Describe what you've done so far to troubleshoot the problem. 

Checked the Facebook Support Group for answers.

**Comment by sofianiu** [comment]
[Updated Plunker Link.](https://plnkr.co/edit/vmokqhD2kU2ZH0vjecDp?p=preview)

The problem has disappeared after I created multiple planks. The website appears buggy, perhaps due to the big update. Can you perhaps suggest an alternative to Plunker?

**Comment by gordonmzhu** [comment]
Hey @sofianiu. Glad the issue worked out. If you'd still like to use another approach, you can follow my suggestions from issue #1 .

**Comment by gordonmzhu** [comment]
@sofianiu The reason it didn't work initially is that you had a syntax error in `deleteTodos`. There was a colon that shouldn't have been there.
