### ISSUE TITLE
8.1 Our first refactoring - handlers is not defined

### ISSUE THREAD

**Issue by jacksone85** [gordonmzhu/questions#329]
What is the associated Watch and Code lesson?
https://watchandcode.com/courses/60264/lectures/1027547
8.1 - Out first refactoring

Include a live demo link so that I can run your code.
https://plnkr.co/edit/ne4BadqyenP5VrpjOU95?p=preview

Explain the exact steps I need to take to replicate the problem.
Open the console and click all 4 buttons. Check the results.

What did you expect to happen?
I expected all of them to result in "Your list is empty!" message.

What actually happened?
 I am having this problem in Plunker after i delete the portion of code we are refactoring. It works when I keep the "button id" lines in. The buttons connected to functions with DOM work. The buttons using handlers object throw an error:
Uncaught ReferenceError: handlers is not defined
at HTMLButtonElement.onclick ((index):14)

And:
Uncaught ReferenceError: handlers is not defined
at HTMLButtonElement.onclick ((index):15)

Describe what you've done so far to troubleshoot the problem.
I've tried retyping the code from the video, deleted the DOM functions, checked everything twice, moved the object declaration to the beginning of the file. No effect so far. I must be missing something, but I can't figure out what it is.

https://plnkr.co/edit/ne4BadqyenP5VrpjOU95?p=preview

**Comment by gordonmzhu** [comment]
It's because you have a typo in your `handlers` object. The code you have is not valid JavaScript. Go through that object with character-by-character precision, and you'll find the problem.

**Comment by jacksone85** [comment]
@gordonmzhu I was off by one comma in the code. Sorry for wasting your time sir
