### ISSUE TITLE
let that = this as a way to change scope for a callback function

### ISSUE THREAD

**Issue by IvandCodes** [gordonmzhu/questions#33]
### What is the associated Watch and Code lesson? 

Interlude - Understanding *this*
Case 5: When you're in a callback function
https://watchandcode.com/courses/60264/lectures/2762323

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/U72VMblFF48yHbqGbyA2?p=preview

```javascript
var myObject = {

  firstFunction: function() {
    let that = this;
    document.addEventListener('click', function() {
      that.secondFunction();
    });
  },

  secondFunction: function() {
    alert("It worked!");
  }
};

myObject.firstFunction();
```

### Explain the exact steps I need to take to replicate the problem. 

Run the Plunker and click anywhere in the preview window.

### What did you expect to happen? 

An error "that is not an object/not defined/or something"

### What actually happened? 

It worked.

### Describe what you've done so far to troubleshoot the problem. 

- As I understand, saving `this` as a variable to use it in other functions is kind of a hack.
- Do I understand it correct that it is a hack? Or is it a normal practice?
- If it is indeed a hack, is there a way to run `secondFunction` within `document.addEventListener` without (1) this hack or (2) explicitly calling it as a method (`myObject.secondFunction`)?

Thank you in advance!

**Comment by gordonmzhu** [comment]
It happens quite often. You could also do:

```
var myObject = {

  firstFunction: function() {
    let that = this;
    document.addEventListener('click', () => {
      this.secondFunction();
    });
  },

  secondFunction: function() {
    alert("It worked!");
  }
};

myObject.firstFunction();
```
