### ISSUE TITLE
'plunkerPreviewTarget' not available in next.plnkr.co

### ISSUE THREAD

**Issue by richardcmckinney** [gordonmzhu/questions#331]
### What is the associated Watch and Code lesson? ###

- **Lesson** https://watchandcode.com/courses/60264/lectures/936334
- **Timestamp** 2:10
- In the next.plnkr.co release of the Plunker website, there isn't an ability to select ''plunkerPreviewTarget''. What can/should be done?

**Comment by gordonmzhu** [comment]
Don't use next. Use the current stable version.

**Comment by gordonmzhu** [comment]
If you'd like to use something else entirely, take a look at the "Get ready" section here: https://watchandcode.com/courses/rough-drafts/lectures/5812763. This is from an unreleased version of Practical JavaScript (in the long-term, we'll be moving away from Plunker).

P.S.

Good to see a product manager learning to code!
