### ISSUE TITLE
Handlers is undefined (v8)

### ISSUE THREAD

**Issue by XanMan336** [gordonmzhu/questions#333]
### What is the associated Watch and Code lesson? 

v8; https://watchandcode.com/courses/60264/lectures/1027557

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/daaxXJYR7L8MwqNe9pWb?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Inspect>plnkrpreviewtarget>AddTodo 

### What did you expect to happen? 

I expected 'originals' to be added

### What actually happened? 

(index):17 Uncaught ReferenceError: handlers is not defined
    at HTMLButtonElement.onclick ((index):17)

### Describe what you've done so far to troubleshoot the problem. 

I tried finding any spelling mistakes and changing the script.js position in the html index

**Comment by gordonmzhu** [comment]
Your JavaScript is invalid. There are several errors in it. Compare your code against mine character by character and you'll find where the problem is.
