### ISSUE TITLE
https://watchandcode.com/courses/60264/lectures/1027554

### ISSUE THREAD

**Issue by zoranobr** [gordonmzhu/questions#337]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by zoranobr** [comment]
https://watchandcode.com/courses/60264/lectures/1027554
Hello :). I have learned how to add some text into a console by pressing a add button but I want to know how to add some text by pressing enter button on the keyboard? 
The lesson explains how to add text onclick, but I would like to know how to make it both at the same time?

**Comment by gordonmzhu** [comment]
Later on in Premium you'll learn how to do this. Stay tuned. If you can't wait, I'd be happy to discuss during one of the weekly meetups (on Mondays).
