### ISSUE TITLE
plunker console access

### ISSUE THREAD

**Issue by Zaboomafu** [gordonmzhu/questions#338]
### What is the associated Watch and Code lesson? 

Version 3 - Objects - It should store the todos array to an object
https://watchandcode.com/courses/60264/lectures/900211
2:40

### Include a live demo link so that I can run your code. 

https://next.plnkr.co/edit/OlmKQige8th7QHok?preview

### Explain the exact steps I need to take to replicate the problem. 

I did the exact steps as you

### What did you expect to happen? 

I expected the console to return the object todoList

### What actually happened? 

todoList
VM487:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1

### Describe what you've done so far to troubleshoot the problem. 

I tried different context fields in the console. I tried in the old version of plunker and the new(alpha).  Still, getting the reference error.

**Comment by gordonmzhu** [comment]
If you use the stable version of Plunker like I am (not alpha), it'll work.
