### ISSUE TITLE
Todos question

### ISSUE THREAD

**Issue by camigm1** [gordonmzhu/questions#339]
### Include a live demo link so that I can run your code. 

![todos](https://user-images.githubusercontent.com/58408419/69926058-29e53000-1470-11ea-9ae7-b079d119bb0b.PNG)

### Explain the exact steps I need to take to replicate the problem. 

I'm pressing enter and it's still not showing my function.

### What did you expect to happen? 

I was expecting it to show me the function to display todos as I made the variable and set up the function for it and I did everything on the video

### What actually happened? 

It kept showing me undefined.

### Describe what you've done so far to troubleshoot the problem. 

I went back and saw the tutorial and it was written the same way but somehow it's not working for me.

**Comment by gordonmzhu** [comment]
This is totally fine. Chrome has changed a little bit. So what you're experiencing now is the new normal.
