### ISSUE TITLE
plunkerPreviewTarget not showing up

### ISSUE THREAD

**Issue by cw323** [gordonmzhu/questions#34]
### What is the associated Watch and Code lesson? 

It should store the todos array on an object: 2:47

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/Mlf2xAWaMBg3HfeYAXed.

### Explain the exact steps I need to take to replicate the problem. 

I clicked "Preview your work" then right clicked to "inspect", went to console tab, and there is no "plunkerPreviewTarget" option on the drop down list.

### What did you expect to happen? 

To have "plunkerPreviewTarget" on the list.

### What actually happened? 

It's not on the list.

### Describe what you've done so far to troubleshoot the problem. 

I did followed the video exactly and googled solutions, but I still don't see it on the drop down list.

**Comment by IvandCodes** [comment]
I couldn't replicate your problem. I clicked "Preview your work" then right clicked to "inspect", went to console tab, and "plunkerPreviewTarget" is there.

Most often it's not there when you forget to run your Plunker before opening the Console.

Cheers!

**Comment by gordonmzhu** [comment]
Yep worked fine for me. Make sure you hit "Run" first as instructed in the lessons.

**Comment by cw323** [comment]
Found the problem. I was in split screen (Mac) while following along exactly with the video and it didn't give me the "plunkerPreviewTarget" option, but trying it on one screen/full screen it showed up and worked!

Thank you!!
