### ISSUE TITLE
cannot get console.log to tab in

### ISSUE THREAD

**Issue by Mocha-Time** [gordonmzhu/questions#340]
Hi Gordon,
I am on V2 at lesson 5, time stamp 2:08. I am typing in the code, but mine does not look like yours particularly where console.log is positioned. When I hit enter, I just get undefined. In your code, the console.log appears to be tabbed in. Mine does not tab in, and I'm wondering if this is where the problem is created. I have googled this, but the answers are way over my head. 

My code is pasted below. Thank you! Marguerite

var todos = ['item 1', 'item 2', 'item 3']
undefined
function displayTodos() {
console.log()
}
undefined
function displayTodos() {

}

undefined

**Comment by gordonmzhu** [comment]
Can you provide a screenshot so I can actually see what's happening in your browser?

**Comment by Mocha-Time** [comment]
Here it is. You can see that yours is indented and mine is not. When I hit
enter after writing the code, I just get undefined.

Thank you for your help!
Marguerite

**Comment by Mocha-Time** [comment]
Hi Gordon,
Would you suggest a different text editor. What do you recommend?
Thank you,
Marguerite

**Comment by gordonmzhu** [comment]
Hey @Mocha-Time. There's no screenshot in the thread. What you see at https://github.com/gordonmzhu/questions/issues/340 is what I see too.

**Comment by Mocha-Time** [comment]
Yours is on the left, mine is on the right (split screen... I am in Google
chrome)

**Comment by gordonmzhu** [comment]
There's still no screenshot... did you actually preview to check and make sure one was showing up?

There are step-by-step directions for adding a screenshot here: https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests.

**Comment by gordonmzhu** [comment]
Closing for now. I'll reopen after I see a screenshot.
