### ISSUE TITLE
Variable Problem (????)

### ISSUE THREAD

**Issue by ioabili** [gordonmzhu/questions#341]
Hi Gordon! Thanks so much for this tutorial and for your willingness to help! 

### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027557

### Include a live demo link so that I can run your code. 

http://next.plnkr.co/edit/WfAXW3Ggxo2nvuZU

### Explain the exact steps I need to take to replicate the problem. 

Chrome. Everything has been working good so far but I got stuck here. Have been bunging my head on the wall for two hours. 
Please add few items in the list and then try to change one of them.

### What did you expect to happen? 

Was expecting that the variable would get changed. Position works good, changeTodoTextInput is problematic. 

### What actually happened? 

![Screen Shot 2019-12-06 at 22 23 22](https://user-images.githubusercontent.com/58186363/70360687-1f170a80-1877-11ea-835f-3d1f059ff278.png)

### Describe what you've done so far to troubleshoot the problem. 

Banged my head. Read everything. Checked semi columns etc. Read your code again. Line by line. Used the debugger to see my variables' values, however I need to become more confident with it! 
I am sure it's gonna be the silliest thing ever and I am so embarrassed for that.  
Thanks so much!

**Comment by gordonmzhu** [comment]
Did you figure out the problem? Seem to work fine for me. Couldn't replicate the problem.

**Comment by ioabili** [comment]
Hi Gordon!

Thanks ever so much for your reply. Yes, I got it sorted out and moved
forward this morning. Didn't know how I could flag this as resolved, I am
sorry.
Have a great week ahead!

Best,
*Ioanna Bili. MA*
T: +447543556473
T: +306973788092
E-mail: ioabilli@gmail.com
Skype: ioanna.billi
