### ISSUE TITLE
I am receiving an error when attempting to run the togglecompleted function on my todo list

### ISSUE THREAD

**Issue by joshromero17** [gordonmzhu/questions#343]
### What is the associated Watch and Code lesson?  

Write your response here (required)
https://watchandcode.com/courses/60264/lectures/946811 @ 4.40

### Include a live demo link so that I can run your code.  

Write your response here (required).
http://embed.plnkr.co/WrqKzkz9HqLHDAS60QRO/

### Explain the exact steps I need to take to replicate the problem.  
Write your response here (required).
Hit inspect and use the addTodo function to add a todo, then attempt to run the togglecompleted function, once that is ran an error pops up

### What did you expect to happen? 

Write your response here (required).
 I expected the new todo that i added to show up and return True

### What actually happened? 

Write your response here (required).
I receive this error message:
script.js:22 Uncaught ReferenceError: position is not defined
    at Object.toggleCompleted (script.js:22)
    at <anonymous>:1:10

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I went through again step by step and reviewed everything and looked for minor errors such as typos etc...

**Comment by gordonmzhu** [comment]
You have a typo in your `toggleCompleted` method. Go through character-by-character and you'll find the mistake.
