### ISSUE TITLE
Error in Plunker when todoList.addTodo('new value');

### ISSUE THREAD

**Issue by tianapetrovic** [gordonmzhu/questions#344]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/936343

Version 6 - When trying to do anything in Plunker console.
I have this problem from the beginning of Practical JS, but I just kept copy/paste the code written in Plunker to a Google Chrome console, and everything worked there. 
But, the new lessons are requiring to connect html and js, and I'm stuck here. 
I have no longer ability to write both html and js codes in the console. So I tried multiple times with no avail to use plunker and access it through console. It gave :
todoList undefined all the times I tried to call the method using: todoList.addTodo('new value');

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/ynMzccgrKS78lZXn?p=info

### Explain the exact steps I need to take to replicate the problem. 

1. After I wrote new lines of codes in Plunker I ensure to hit the Save button
2. I hit Run button
3. I opened the console and chose for plunker preview target
4.  I wrote todoList.addTodo('first thing'); and got the following message

>     VM1215:1 Uncaught ReferenceError: todoList is not defined
>     at <anonymous>:1:1

 But if I just pasted the codes on the Google Chrome console, I got everything working just fine

### What did you expect to happen? 

I expected from Console in Plunker to act the same as the Google Chrome Console

### What actually happened? 
It happen nothing. Only Refference Erorr message.

> VM1215:1 Uncaught ReferenceError: todoList is not defined
>     at <anonymous>:1:1
> (anonymous) @ VM1215:1

### Describe what you've done so far to troubleshoot the problem. 

I have followed the exact same steps as Gordon in his tutorials, searched the Google and YouTube for solutions, but nothing helped.

![1](https://user-images.githubusercontent.com/56056155/70613429-e6758900-1c08-11ea-90d1-18319528939e.png)
![2](https://user-images.githubusercontent.com/56056155/70613448-ed9c9700-1c08-11ea-97bd-ec95b0e16387.png)
![3](https://user-images.githubusercontent.com/56056155/70613457-effef100-1c08-11ea-8b90-883d2a5b6e54.png)
![4](https://user-images.githubusercontent.com/56056155/70613462-f2f9e180-1c08-11ea-9f79-1f574759aaa3.png)
![5](https://user-images.githubusercontent.com/56056155/70613469-f5f4d200-1c08-11ea-94c4-2202fd03ebc5.png)
![6](https://user-images.githubusercontent.com/56056155/70613480-f8572c00-1c08-11ea-9906-6ce3be4f76e1.png)

**Comment by tianapetrovic** [comment]
@gordonmzhu

**Comment by gordonmzhu** [comment]
Hey @tianapetrovic. Thanks for the detailed issue. Try this project and let me know if it works. Sometimes Plunker has issues with the package.json file. All I did was change the contents of it to an empty object and it seems to have done the trick.
