### ISSUE TITLE
having an issue with 'i is already defined'

### ISSUE THREAD

**Issue by Astrocat-dev** [gordonmzhu/questions#345]
###
Hello, I am on version 6 of your practical java script lesson and line 50 and 55  both have 'i is already defined' errors:
https://plnkr.co/edit/pGalHUL52ps9JLLaKnhN?p=info
however the video of your lesson is showing the exact same code i put into plunker:
https://watchandcode.com/courses/60264/lectures/975962  
timestamp: @1:52
  

I know that you can get errors like this when you try to reference to a variable that is in a different item but this i is in the same item as the original i variable.

i tried to debug the problem but plunkr didn't offer any results other than the fact that the i is already defined
 
you wont need to take any steps to see the issue, the issue is on the script page, you'll see error on line 50 and 55

I've rewritten the code multiple times and it just seems like nothing is working.
I'd appreciate any help you can offer!

**Comment by gordonmzhu** [comment]
So those aren't errors. Just warnings. They won't affect how your code runs.

If it's really bothering you, in the second loop, you can use a different variable.
