### ISSUE TITLE
Error Message when Trying to Add a Todo

### ISSUE THREAD

**Issue by RobertMDoyle** [gordonmzhu/questions#35]
### What is the associated Watch and Code lesson? 

[https://watchandcode.com/courses/60264/lectures/956106](url)

### Include a live demo link so that I can run your code. 

[https://plnkr.co/edit/zZ7zFStiMMm2umNqj9sJ?p=preview](url)

### Explain the exact steps I need to take to replicate the problem. 

After writing the displayTodos function including the for loop, I was unable to add a todo in chrome console.

### What did you expect to happen? 

I expected the add todo to work as it seemed to match your example code

### What actually happened? 

Yes I received this error:

todolist.addTodo('one');

VM917:1 Uncaught ReferenceError: todolist is not defined
    at <anonymous>:1:1
(anonymous) @ VM917:1

### Describe what you've done so far to troubleshoot the problem. 

I clicked on the error message which took me to the chrome debugger. It said that todoList is not defined, but var = todoList object, so I believe it is declared. Multiple attempts are resulting in the same error.

**Comment by hydroweaver** [comment]
Hey @RobertMDoyle , looks like you have a syntax error on line 34 in script.js, remember, you're trying to refer to a position inside the todo array.

**Comment by RobertMDoyle** [comment]
Thank you. I put 
todo.[position]
With the unnecessary dot notation breaking the array command. Thank you for pointing me in the right direction. I can see how debugging is so important now

**Comment by gordonmzhu** [comment]
Hey @RobertMDoyle. Just checking to see if you got this sorted out. I tried adding a todo and it worked fine, so it seems like things are working now. Please reply to this comment if this is not the case.
