### ISSUE TITLE
plunkerPreviewTarget not working at Version 3 Objects at 3:00

### ISSUE THREAD

**Issue by sniperglass** [gordonmzhu/questions#351]
### What is the associated Watch and Code lesson? 

Write your response here (required).
Hi Im not sure how old this vid is but cant seem to get the above to show in inspect.
Cheers.

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Closing due to incomplete issue. I need to know more... for example, what did you try? I need your Plunker URL so I can try to recreate the issue... etc. That's why there's a template. If you'd like assistance, please open a new issue and take the care to fill it out.
