### ISSUE TITLE
Hi I'm working on a contact list in javascript,when to know if i have to use a loop? 

### ISSUE THREAD

**Issue by johnmas12** [gordonmzhu/questions#352]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Closing. Question is not related to curriculum. Also none of the fields were filled out.
