### ISSUE TITLE
Can't access data in latest version of plunker.

### ISSUE THREAD

**Issue by pawandalmia** [gordonmzhu/questions#354]
### What is the associated Watch and Code lesson? 

**https://watchandcode.com/courses/60264/lectures/900211.**
**Time: 3:02**

### Include a live demo link so that I can run your code. 

**http://plnkr.co/edit/VV0IMlHlMIM3dEAR?p=preview**

### Explain the exact steps I need to take to replicate the problem. 

**After writing code in plunker, then running the code, after right-clicking as on the video, I clicked on "inspect", in the console, I cannot access "todoList". It shows error : VM887:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1**

### What did you expect to happen? 

**I expect to access "todoList" and display its contents**

### What actually happened? 

**It shows error : VM887:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1**

### Describe what you've done so far to troubleshoot the problem. 

**I tried using the old version of plunker. But the error persists.**

**Comment by gordonmzhu** [comment]
Hey @pawandalmia. In issue #1 you can find directions on how to use something else if you're having trouble with Plunker.

**Comment by gordonmzhu** [comment]
Direct link to relevant comment https://github.com/gordonmzhu/questions/issues/1#issuecomment-387138249.
