### ISSUE TITLE
deleteTodo(0, 1) refactoring broken - deletes entire array

### ISSUE THREAD

**Issue by jwhitty1** [gordonmzhu/questions#358]
### What is the associated Watch and Code lesson? 

DELETING TODOS OBJECT + BUTTON (refactoring)
https://watchandcode.com/courses/60264/lectures/1027560

### Include a live demo link so that I can run your code. 

I'm not sure how to save these and share them so I hope this works
https://plnkr.co/edit/vBhDMNOtuWo3u2Oqmohe?p=info

### Explain the exact steps I need to take to replicate the problem. 

Add 2+ todos and then delete a todo at position 0.

### What did you expect to happen? 

Only the first todo will delete

### What actually happened? 

All todos are deleted

### Describe what you've done so far to troubleshoot the problem. 

I dont see anything wrong (that I understand) in the debugger and I always check my code to make sure its the same as yours in the videos when I use them. It can delete anything past position 0 just fine, but pos 0 deletes all the array. why? i try clicking the objects/methods in the debugger on the right like you taught us, but i just see everything has values of zero and nothing seems to show me useful numbers and values being input/output like yours did in the tutorials...

**Comment by jwhitty1** [comment]
I went back and re-watched the Delete Todo refactoring and i def have all my code like yours, but you deleted position 1 and then position 0, so you didnt see the error i get when deleting position 0 right off the bat.
is this some kind of general non-permitted action? that if i add [1, 2, 3] and delete 1 (position 0 in the array) it will delete the entire thing because JS doesnt know how to shift everything forward one? like taking the bottom block out of jenga when its the only one left?

**Comment by jwhitty1** [comment]
I also just realized that if I add 4 values and delete value at position arr[1], it will delete arr[1]-arr[3].
I don't know where I went wrong in copying the code that it deletes everything AFTER the value i chose including that value...

**Comment by gordonmzhu** [comment]
Your `deleteTodo` method on your `todoList` object is not written correctly. Go back to the lesson where you wrote that and you'll spot your problem.
