### ISSUE TITLE
Refactoring... "Handler"???

### ISSUE THREAD

**Issue by trwexler** [gordonmzhu/questions#359]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/1027791           The html at 2:03 with the "handler" part written. 
Write your response here (required).

Gordon, 

I don't have a problem as much as I have a question about syntax. Why can't we just continue with the previous syntax, simply writing onclick="todoList.displayTodos();"???   It works the same way and doesn't call for any additional JavaScript. You didn't mention that while explaining and it's a strangely specific syntactical question that I can't find an answer to anywhere.

Loving the course and desperately trying to find more time to finish it. I will 100% get the premium content once I am through PJS. Thank you for everything, Gordon.

Best,

Tom Wexler 

### Include a live demo link so that I can run your code. 

Sorry, plunker was not working properly and I had to copy the code to Sublime Text.

### Explain the exact steps I need to take to replicate the problem. 

Everything works both ways.

### What did you expect to happen? 

I expected todoList.displayTodos() not to work, but it did. IF we are adding additional js, then I expected the way we called other functions within the object not to work.

### What actually happened? 

The original way "todoList.displayTodos()" worked

### Describe what you've done so far to troubleshoot the problem. 

They both ran identically from what I can tell, and the way I have listed makes a lot more sense to me, rather than creating the code associated with "handler"

**Comment by gordonmzhu** [comment]
Hey @trwexler. I answered a similar question previously. See https://github.com/gordonmzhu/questions/issues/97. Let me know if you have any questions after reading through that answer.
