### ISSUE TITLE
odoList.displayTodos(); VM1653:1 Uncaught ReferenceError: todoList is not defined     at <anonymous>:1:1 (anonymous) @ VM1653:1

### ISSUE THREAD

**Issue by 3dcheesenips** [gordonmzhu/questions#36]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Closing empty issue. If you'd like assistance, please fill out all of the required fields and someone will be happy to help.
