### ISSUE TITLE
Version 7 - HTML and the DOM

### ISSUE THREAD

**Issue by eslima5** [gordonmzhu/questions#360]
Lesson title: Clicking Display todos should run todoList.displayTodos

URL :   https://watchandcode.com/courses/practical-javascript/lectures/987943

Video timestamp: 4:55

Hi Gordon, I don't know why the code is not running. When I tested the console.log, the code is not running. I also noticed that when you run the code at 4:55, the console appeared automatically but you didn't right-click "Inspect element".

Normally, you:
- right-click "Inspect element, 
- choose console
- choose "Plunkr preview target"

but this time, you just clicked "Run" and everything appeared. I didn't see you clicking anything but "Run"

# LIVE DEMO LINK - http://plnkr.co/edit/9oKan2ogZZAWzd2cI2RS?p=info

### Explain the exact steps I need to take to replicate the problem. 

* I double checked the code, it looks exactly like the video
* I pressed the "Run" button.
* I right-clicked "Inspect"
* I clicked "Console"
* I chose "Plunkr preview target"
* I clicked the "Display button"
* Nothing happens. The code doesn't run.
* Note - my browser is Google Chrome

### What actually happened? 

Error Message: 

*Uncaught TypeError: Cannot read property 'addEventListener' of null
*[Violation] 'setTimeout' handler took 78ms

SCREENSHOT:

![image](https://user-images.githubusercontent.com/59187908/71895057-54bf5400-3193-11ea-8bed-cd83a4bbcd75.png)

### Describe what you've done so far to troubleshoot the problem. 

* I rewatched the video over and over.
* I checked the code if its identical to the code in the video
* I copied/pasted from github, a code for Practical Javascript version 7 from other students. It still doesn't work.

**Comment by gordonmzhu** [comment]
Hey @eslima5. If you want things to work in Plunker, just move your script tag in index.html to the bottom so it looks like this:

```
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">    
  </head>

  <body>
    <h1>Todo list</h1>
    
    <button id="displayTodosButton">Display Todos</button>
    <button id="toggleAllButton">Toggle All</button>
    <script src="script.js"></script>
  </body>

</html>
```

In the last few days, I redid the course to use VS Code instead of Plunker (for example see "Interlude - Editor setup" https://watchandcode.com/courses/practical-javascript/lectures/13410406). In the new setup, the script tag is already on the bottom so everything is all good. In Plunker, it was initially at the top so you just need to move it down for things to work again.
