### ISSUE TITLE
No question, just a comment.

### ISSUE THREAD

**Issue by Orbit19** [gordonmzhu/questions#361]
### What is the associated Watch and Code lesson? 

Lesson Clicking “Display todos” should run todoList.displayTodos 
@ 2:00 you start writing code.  People might get confused here and think that the buttons go inside of the object instead of below the object but still inside the script tag.

Also it would be helpful to have a link at the end of the video to your code so that if we do run into a problem we could check our code against yours since we can't scroll the videos to see all of the code.  I also understand if you don't do this because you want people to troubleshoot their own code and go over the videos to figure it out.

I really like the videos so far, thank you for creating this course.
-Karen

**Comment by gordonmzhu** [comment]
Thanks for the feedback @Orbit19. It should be clearer in the next revision of the course since all the videos will use VS Code. Now things are a little weird since what's in the videos is every so slightly off. Not ideal, but it'll just be like that temporarily.
