### ISSUE TITLE
Do you have the code from these videos published on GitHub.  It would be very helpful and expedite the learning process to be able to refer back to the code easily.

### ISSUE THREAD

**Issue by JJFore** [gordonmzhu/questions#365]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
No. If you go through the course carefully, you'll have the code.
