### ISSUE TITLE
What screen are you switching to at 0:14? 

### ISSUE THREAD

**Issue by evaturner** [gordonmzhu/questions#367]
### What is the associated Watch and Code lesson? 

 In lesson 1 "Functions are just recipes" at 0:14 seconds you switch to a black screen. What are the steps you took to get to that screen? I am in the console page and when I try to write the code in the screen it is giving me error an message: UncaughtSyntaxError

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

![image](https://user-images.githubusercontent.com/59971239/72551082-1e07ce80-3862-11ea-8d14-738ea5cbe6f4.png)

![image](https://user-images.githubusercontent.com/59971239/72551153-442d6e80-3862-11ea-9980-385f2b4566ed.png)

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

I reviewed the Browser video, requirements video as well as looked at the settings for my browser as I thought it could be a Browser difference issue. My Browser does look different. I am using Version 77.0.3865.90 (Official Build) (64-bit).

**Comment by gordonmzhu** [comment]
I'm just using a text editor (like Notepad, Word) to write down some notes. Notice that I do not run any code in this video.
