### ISSUE TITLE
Why do we need handler functions?

### ISSUE THREAD

**Issue by bravoalpha79** [gordonmzhu/questions#368]
### What is the associated Watch and Code lesson? 

The lesson in question is "Our first refactoring".
https://watchandcode.com/courses/60264/lectures/1027547

### Include a link to your code so I can run it on my computer. 

This is more of a general/understanding question, it isn't linked to a(ny) specific piece of code.

### Explain the exact steps I need to take to replicate the problem. 

When we create buttons and add "onclick" attributes to them, why do we need to create handler functions in order to make it work? 

### What did you expect to happen? 

For example, the displayTodos() function is already defined in the todoList object. Why are we defining another function (in the handlers object) just to call a function that is already defined? 

### What actually happened? 

Why cannot we just put "todoList.displayTodos()" into the "onclick" attribute of the respective button and thus invoke the displayTodos() function directly when the button is clicked? Why is there the need for a "middle man" (handler)? 

### Describe what you've done so far to troubleshoot the problem. 

I googled "why do we need handlers JavaScript", but found nothing to explain why I would specifically need a new function just to call/handle an existing function. If we can invoke the todoList.displayTodos() function directly from the console, why can't we do exactly the same from a button's "onclick" attribute?

**Comment by gordonmzhu** [comment]
See previous answer to same question: https://github.com/gordonmzhu/questions/issues/97
