### ISSUE TITLE
this/callback functions/ objects and forEach

### ISSUE THREAD

**Issue by ChristinaJackson** [gordonmzhu/questions#369]
### What is the associated Watch and Code lesson? 

Write your response here (required).
> * https://watchandcode.com/courses/practical-javascript/lectures/1181252 
> * Around 4:30 
> * around that time you talk about why the this.createDeleteButton isn't working and that this needs to be specified after the call back function. I was able to make it work by using view.createDeleteButton(around line 99). Is there any reason this is not a good way to do things?

### Include a link to your code so I can run it on my computer. 

Write your response here (required).
 > * Here is the code link https://repl.it/@ChristinaJ/watchandcode

### Explain the exact steps I need to take to replicate the problem. 
> * No problem 

### What did you expect to happen? 
 
 > * Expected it not to work but it did, curious about why or if this is not a good way to do things.  

### What actually happened? 
 > *No error, Code works

### Describe what you've done so far to troubleshoot the problem. 

> * NA
> * Thanks!

**Comment by gordonmzhu** [comment]
Hey @ChristinaJackson. It's a matter of preference. They're functionally the same since `this` also refers to the view object.
