### ISSUE TITLE
dual function - add new todo + display todos

### ISSUE THREAD

**Issue by eugenelopin** [gordonmzhu/questions#370]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/928385
3:00

### Include a link to your code so I can run it on my computer. 

https://gist.github.com/eugenelopin/97849d1416193d324f6bd67aa294aa43

### Explain the exact steps I need to take to replicate the problem. 

did everything correctly following lessons until writing the dual function of add + displaying todo, wrote it same as you did, but running addTodo after doesnt add and display todos 

### What did you expect to happen? 

^^

### What actually happened? 

pasted in gist

### Describe what you've done so far to troubleshoot the problem. 

reviewed video and tried again in my code, pasted in gist w returns

**Comment by gordonmzhu** [comment]
Watch the video carefully. You're not typing in the same thing.

**Comment by eugenelopin** [comment]
Ah! Got it, thank you 👍
