### ISSUE TITLE
Linking index.html to script.js

### ISSUE THREAD

**Issue by garyoconnor50** [gordonmzhu/questions#371]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by garyoconnor50** [comment]
Lesson: Version 7 lesson 4 - Version 8 lesson 1

Code below. Everything worked perfectly until linking the html buttons with the js code. I have tried the original way and the refactoring way and neither work. I have gone through several times and am 99.9% sure my code exactly replicates the instructions. Please help!

var displayTodosButton = document.getElementById('displayTodosButton');
var toggleAllButton = document.getElementById('toggleAllButton');

displayTodosButton.addEventListener('click', function() {
  todoList.displayTodos();
});

toggleAllButton.addEventListener('click', function() {
  todoList.toggleAll();
});



  var handlers = {
    displayTodos: function() {
  todoList.displayTodos();
    },
    toggleAll: function() {
      todoList.toggleAll();
    }
  }

<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
  </head>

  <body>
    <h1>Todo List</h1>
    
    <button id="displayTodosButton">Display Todos</button>
    <button id="toggleAllButton">Toggle All</button>
    
    <button onclick="handlers.displayTodos()">Display Todos</button>
    <button onclick="handlers.toggleAll()">Toggle All</button>
    
  </body>

</html>

**Comment by garyoconnor50** [comment]
I have deleted the original code and now the refactoring method works! No idea what was wrong with the original code and why that prevented the refactoring from being effective??

**Comment by gordonmzhu** [comment]
I can't tell unless you share all of your code. When sharing, include the entire file rather than snippets.
