### ISSUE TITLE
Lower the default volume bar holy shit rip ears on headphones, and it resets to default full 100% one every next video

### ISSUE THREAD

**Issue by rhazor** [gordonmzhu/questions#372]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
I can't control this. As a workaround, just lower the volume on your system.
