### ISSUE TITLE
Question about Code example 3 of section "Interlude - Data types and Comparisons

### ISSUE THREAD

**Issue by esegeu** [gordonmzhu/questions#374]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/3954982

### Include a link to your code so I can run it on my computer. 

I'm not having trouble with code, I just have a conceptual question. I understand what you explain in this section, but this explanation makes me wonder why something different seems to happen with the todo variable in the toggleCompleted method. In that method, var todo = this.todos[position] but when toggling the completed property of the todo variable the completed property of the actual element in the todos array is also toggled, and I haven't been able to figure out why, if the variable todo and the element in todos are different. I am loving this course and seriously considering getting the premium plan. I greatly appreciate the effort you have put into creating such a wonderful course. THANK YOU.

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
It's not different. Try drawing the diagram for `toggleCompleted`. If you take a shot at that and share your diagram, I'd be happy to continue the discussion.

**Comment by esegeu** [comment]
Hello Gordon. First of all, thank you very much for your quick response and for your willingness to help me understand. I now am definitely sure i want to continue with the premium plan once i get through this course. I did the diagram and I think I got it. The variable 'todo' first gets the memory location of 'this' (todoList), which in turn is a reference to  the address of 'todos', which in turn is a reference to an address for a particular item (I did the path in pink in the diagram attached in this message). So, indeed, 'todo' and this.todos[position] are the same object. My diagram, which hopefully is correct, prompts another question, which I don't expect to be answered by you right now, but hopefully I will get to grasp as I move forward: todoList has several properties, and every property has it's own "sub-properties". How can multiple properties be referenced by one single memory location? It occurs to me that the answer is: several memory locations have to be allocated to save every property, but how does that work? does JS create a sort of ledger where the first and last address for an object are recorded and looked up? looking forward to your premium course and thanks lot!!
![IMG_20200127_151814](https://user-images.githubusercontent.com/60351840/73211445-40c79c00-411a-11ea-933b-e25762bd8492.jpg)

**Comment by gordonmzhu** [comment]
<div><p><a href="https://soapbox.wistia.com/videos/2De7eBCSlL" target="_self"><img style="width:400px;height:225px" width="400" height="225" src="https://embed-ssl.wistia.com/deliveries/3aa8c79e2a447f17d45da5273ed6573b.jpg?image_crop_resized=800x450"/></a></p><p><a href="https://soapbox.wistia.com/videos/2De7eBCSlL">Soapbox - Issue #374 — Jan 30, 9:49 am</a></p></div>
