### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by anugusaitejareddy** [gordonmzhu/questions#376]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/1102313
Write your response here (required).

### Include a link to your code so I can run it on my computer. 
https://plnkr.co/edit/0sTbMNewACzBudjSmnbN?p=preview   //code.
Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 
I'm using windows and chrome to run the application. The delete button is not working. The console shows the error Uncaught TypeError: Cannot read property 'addEventListener' of null
Write your response here (required).

### What did you expect to happen? 

Write your response here (required).
 Expected The delete button to delete the todo item.

### What actually happened? 

Write your response here (required).
script.js:121 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at window.onload (VM646 script.js:121)
window.onload @ script.js:121
load (async)
setUpEventListeners @ script.js:119
(anonymous) @ script.js:131

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
googled the error and added a line to the function 'window .onload()'

**Comment by gordonmzhu** [comment]
Your code is different than mine. That's why you're getting different behavior.

For example, you're using `onload` and I'm not sure why. You also have two duplicate script tags in your html.

Go back in the videos to a point where your code worked and make sure your code is identical to mine. Once you do that, everything will work the same way.
