### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by dmitrysurkin** [gordonmzhu/questions#377]
Greetings! I live in Russia and have difficulties translating. Do you have transcription of your videos to text?

**Comment by gordonmzhu** [comment]
For what videos?

**Comment by dmitrysurkin** [comment]
I figured out the subtitles. Can I get all free videos separately? I can not download them from the site ... Thank you very much, if possible !!

**Comment by gordonmzhu** [comment]
No. The videos are not downloadable.
