### ISSUE TITLE
hi new to this and confused?/stuck?

### ISSUE THREAD

**Issue by sancheezy9** [gordonmzhu/questions#378]
### What is the associated Watch and Code lesson? 
im on the 4th video of the arrays section when i input codes or  lines of code mine responds diffrently 
Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
All the fields are required. *If* you take the time to fill them out I'd be happy to help out.
