### ISSUE TITLE
My variable displayTodosButton returns the value Null

### ISSUE THREAD

**Issue by StanislavAlpatiev** [gordonmzhu/questions#389]
### What is the associated Watch and Code lesson?  

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/987943
timestamp: 6:50

### Include a link to your code so I can run it on my computer. 

Write your response here (required).
https://github.com/StanislavAlpatiev/practicalJavaScript.git

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
This code is the same as the one that you have written in your lectures. However, when I run it in google chrome it returns the value Null when I try to console.log(displayTodosButton) in the script.js file. Even tho the button has the exact same id it is still returning Null.

### What did you expect to happen? 

Write your response here (required).
I expect it to return the buttons tag from the dom. This is due to the fact that when I console.log(document) I get the dom in return.
 
### What actually happened? 

Write your response here (required).
I receive this error message in the console: 
version6.js:86 Uncaught TypeError: Cannot read property 'addEventListener' of null
at version6.js:86

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I reviewed the code and looked at it in comparison to the code that you have written in this lecture thus far. I also ran all the functions of this code by themselves in order to see that the code is not flawed anywhere else which might have leed to this bug.

**Comment by gordonmzhu** [comment]
In the code you provided, you are not even linking to your JavaScript file in the script tag. You should fix this first before doing anything else...

**Comment by StanislavAlpatiev** [comment]
<script src="version6.js"></script> 
im sorry but what do you mean?
is this not inside the script tag?

**Comment by gordonmzhu** [comment]
There's no file named `version6.js`.

**Comment by gordonmzhu** [comment]
I'll take another look now that I see you've corrected your html to point to your JavaScript file now.

**Comment by StanislavAlpatiev** [comment]
I found the issue. The script ran before the dom was fully loaded so the button was not yet created so to speak when the script called for it. It was solved by putting async in the script tag or by simply moving the script tag to the bottom of the body tag.

**Comment by gordonmzhu** [comment]
👍

**Comment by goldfinger17** [comment]
Thanks! I had the same issue.

**Comment by nabinbaidya** [comment]
I had the same issue. Moving the script tag at the bottom before the body tag worked. But I have more questions now:
1. My variable displayTodosButton returns the value Null, but you say the DOM was not fully loaded. But it worked in the tutorial video. Why? In the same issue, in another thread Gordon points that its a typo. I searched for a typo but could not find one, but moving the script tag before the closing body tag the code worked fine.
2. I read that moving the script tag to the bottom reduces performance and have to use the async feature. How do I use that?
