### ISSUE TITLE
AddEventListener method

### ISSUE THREAD

**Issue by sbeck0109** [gordonmzhu/questions#393]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/987943
<img width="1091" alt="WatchAndCode_Lecture_Problem_screenshot1" src="https://user-images.githubusercontent.com/53356182/75388700-47bd0800-589a-11ea-9e63-46339597b602.png">

### Include a link to your code so I can run it on my computer. 

<!DOCTYPE html>

<html>
  <head>
    <title>Practical JavaScript</title>
  </head>
  <body>
    <h1>Todo List</h1>

    <button id="displayTodosButton">Display Todos</button>
    <button id="toggleAllButton">Toggle All</button>

  <script>

    var todoList = {
      todos: [],
      displayTodos: function () {
          if (this.todos.length === 0) {
             console.log('Your Todo List is empty!');
            } else {
              console.log('My Todos: ');
              for (var i = 0; i < this.todos.length; i++) {
                console.log(this.todos[i].todoText);

              if (this.todos[i].completed == true) {
                console.log('(x)', this.todos[i].todoText);
              } else {
                console.log('( )', this.todos[i].todoText);
              }

              }
            }
      },
      addTodo: function(todoText) {
        this.todos.push({
          todoText: todoText,
          completed: false
        });
        this.displayTodos();
      },
      changeTodo: function(position, todoText) {
        // this.todos[position] = newValue;
        this.todos[position].todoText = todoText;
        this.displayTodos ();
      },
      deleteTodo: function(position) {
        this.todos.splice(position,1);
        this.displayTodos();
      },
      toggleCompleted: function(position) {
        var todo = this.todos[position];
        todo.completed = !todo.completed;
        this.displayTodos();
      },
      toggleAll: function () {
        var totalTodos = this.todos.length;
        var completedTodos = 0;

        // Get numver of completed todos.
        for (var i = 0; i < totalTodos; i++) {
          if (this.todos[i].completed === true) {
            completedTodos++;
          }
        }
        // if everything is true, make everything false.
        if (completedTodos === totalTodos) {
          for (var i = 0; i < totalTodos; i++) {
            this.todos[i].completed = false;
          }
        }else{
          for (var i = 0; i <totalTodos; i++) {
            this.todos[i].completed = true;
          }
        }
        this.displayTodos();
      }
    };

    // we want to get access to the display todos button.
    // we want to run displayTodos method, when someone clicks the display
    // todos button.

    var displayTodosButton = document.getElementById('displayTodosBotton');
    console.log(displayTodosButton);

    displayTodosButton.addEventListener('click' , function (){
      todoList.displayTodos();
    });

    </script>
  </body>
</html>

### Explain the exact steps I need to take to replicate the problem. 

I've been working in Chrome. When I tried adding 'AddEventListener' method to displayTodosButton, it did not work. 

### What did you expect to happen? 

Every time when the button is clicked, it should show the todo list.

### What actually happened? 

It says, cannot read property 'AddEventListener' of null.
<img width="1112" alt="WatchAndCode_error_message_screenshot2" src="https://user-images.githubusercontent.com/53356182/75389074-d3369900-589a-11ea-8163-afd073dda559.png">

### Describe what you've done so far to troubleshoot the problem. 

I went back to review the previous concepts, but I got stuck here :/ Thank you for your help.

**Comment by gordonmzhu** [comment]
You have a typo. Your job is to go through the file character-by-character and find it. See 6 from https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603. If you need to go back to a point where things were working and then work from there step-by-step, then do it.

**Comment by sbeck0109** [comment]
Hi Gordon,

Problem solved! Thank you so much for your help and time! 

Sincerely,
Sawyee
