### ISSUE TITLE
getElementById or querySelector

### ISSUE THREAD

**Issue by Netacci** [gordonmzhu/questions#395]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/1056229
timestamp 7.00

Assuming we give the ul an ID, Can we use getElementById instead of querySelector? Do they do the same thing?

**Comment by gordonmzhu** [comment]
@Netacci Good question. Why not try that out and see if you can get it to work?
