### ISSUE TITLE
This. method

### ISSUE THREAD

**Issue by boovuu** [gordonmzhu/questions#396]
https://watchandcode.com/courses/60264/lectures/936348

I have been doing they step by step follow up, I provided the codes bellow. Whenever I use this. Method it doesn’t work. Just return undefined. 
I scratched my head around this but it only works when I use ‘todosList.’ Instead of using just ‘this.’

Clearly I am doing something wrong but I just can find out what.

var todosList = {
    todos: ['item 1', 'item 2', 'item 3'],
    displayTodos: ()=>{
        console.log('My Todos', todosList.todos);   
    },
    addTodo: (todo)=>{
        todosList.todos.push(todo);
        todosList.displayTodos();
    },
    changeTodo: (position, newValue)=>{
        todosList.todos[position] = newValue;
        todosList.displayTodos();
    },
    deleteTodo: (position)=>{
        todosList.todos.splice(position, 1);
        todosList.displayTodos();
    }
};

### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Please open a new issue and make sure to fill out all the fields.
