### ISSUE TITLE
Issue: Comment about the First Requirement of the new feature of Todos in the Functions Section

### ISSUE THREAD

**Issue by selcouthlyBlue** [gordonmzhu/questions#397]
This is not really a question but more of an observation. I noticed in this video https://watchandcode.com/courses/60264/lectures/928384 at the timestamp 3:23, the code is like this

```
var todos = ["item 1", "item 2", "item 3"];

function displayTodos() {
    console.log(todos);
}

displayTodos();
```

I do know that the function is able to read the `todos` variable outside, but other students might ask how the function is able to display the value of `todos` even though it is not a parameter of the function.

**Comment by gordonmzhu** [comment]
Haven't had that issue come up but I'll keep an eye on it in case people are confused.
