### ISSUE TITLE
Video cuts off at end, mid-sentence...

### ISSUE THREAD

**Issue by k2director** [gordonmzhu/questions#398]
### What is the associated Watch and Code lesson? 

**Video cuts off mid-sentence right at the end (2:15): 
https://watchandcode.com/courses/60264/lectures/2368421**

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Hey @k2director thanks for catching that. Just fixed it.
https://watchandcode.com/courses/practical-javascript/lectures/2368421
