### ISSUE TITLE
JavaScript data types and memory allocation

### ISSUE THREAD

**Issue by angie993** [gordonmzhu/questions#4]
In this lesson, https://watchandcode.com/courses/practical-javascript/lectures/3954982 , I understood how the value and reference types are being stored, but I have one concern about the memory allocation.

**My questions is**: This is my understanding of example 3, is it correct?

![js](https://user-images.githubusercontent.com/15730665/40973412-6ead4c26-68c4-11e8-8988-51d7ff1318d2.jpg)

**Comment by gordonmzhu** [comment]
Hey Angie. I'd encourage you not to think about garbage collection as it's not relevant to the material in this lesson. It's best to think of garbage collection as a separate topic.

That said, the diagram I have in the video is accurate. This one is not. There should be *just one* box for the `color` variable which changes from an initial value of `'blue'` to `'red'` at the end
