### ISSUE TITLE
question about handlers

### ISSUE THREAD

**Issue by Velcrogoblin** [gordonmzhu/questions#401]
Hi Gordon, i am not stuck in any particular lesson, but i had a doubt.

in: https://watchandcode.com/courses/60264/lectures/1027547
lesson about refactoring, you created the handlers object to manage the buttons interactions.

I just wanted to know if there is an advantage in creating the handlers instead of using the functions we made before (the ones inside todoList) directly.

for example, i tried:

**in the js file:**

addTodo: function() {
    var addTodoTextInput = document.getElementById("addTodoTextInput");
    this.todos.push({
      todoText: addTodoTextInput.value,
      completed: false
    });
    this.displayTodos();
    addTodoTextInput.value = "";
  },

**and in the html file:**

`<button onclick = "todoList.addTodo()">Add</button> 
<input id = "addTodoTextInput" type = "text">`

It works fine, so I was jut curious about the advantage of the handlers object.
I understand that handlers makes the code easier to read and "cleaner", but on the other hand it adds more lines of code to the file.

Thanks a lot, I really think these lessons are incredible for learning, using the code that we learned inside a real context.

**Comment by cerlans** [comment]
Hey Man, i'm not Gordon but i'm going to chime in my thoughts. I also thought the same thing, why can't we just use the main object we created this entire time? it accomplishes the same thing from what i'm seeing. 

but i don't think that was Gordons intention, one of the key aspects of WatchAndCode is having reliable readable code that other devs (besides you) can interpret with ease. So i feel like he made us create a separate variable for all the handlers for clarity and ease off access from an outsider developer perspective. if you had just used the main object instead, i would assume it would make it a bit confusing.

**Comment by Velcrogoblin** [comment]
> Hey Man, i'm not Gordon but i'm going to chime in my thoughts. I also thought the same thing, why can't we just use the main object we created this entire time? it accomplishes the same thing from what i'm seeing.
> 
> but i don't think that was Gordons intention, one of the key aspects of WatchAndCode is having reliable readable code that other devs (besides you) can interpret with ease. So i feel like he made us create a separate variable for all the handlers for clarity and ease off access from an outsider developer perspective. if you had just used the main object instead, i would assume it would make it a bit confusing.

I thought the same thing... Thats's why i wanted to know if that was the case, or if there's any other reason. 
Thanks for your reply!

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97 for previous answer to this same question.
