### ISSUE TITLE
Hi Gordon! again ':)

### ISSUE THREAD

**Issue by Cabechin** [gordonmzhu/questions#402]
### What is the associated Watch and Code lesson? 

Write your response here (required).
 v3 -- It should store the todos array on an object 
### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
the problem I got is not about programming, is about the plnkr.co.. That it was never explained, as I am new to this I got complete lost about that..

### What did you expect to happen? 

Write your response here (required).
I hope you have some tutorial about plnkr.co usage 
### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I saw all the content a couple of times trying to find where was the explanation, I went through tutorials in YouTube with different code makers, but couldn`t find what`s necessary to keep up the lessons.

**Comment by Velcrogoblin** [comment]
Hi Cabechin, I know the question is for Gordon, but maybe I can help. In a previous video he recommends us to use visual studio code, and explains that what you see will be different there.
A few times he explains how to proceed when using visual studio code and the google chrome console.

Just to summarize a lot, what he does in pinkr, you have to do in Visual Studio Code.

Hope I was able to help!

**Comment by Cabechin** [comment]
Thanks! You were right @Velcrogoblin  As i am new in this world is hard for me 😅

**Comment by Velcrogoblin** [comment]
> Thanks! You were right @Velcrogoblin As i am new in this world is hard for me 😅

dont worry! i am too =)

**Comment by gordonmzhu** [comment]
Thanks for helping out @Velcrogoblin!

@Cabechin I don't have anything to add to @Velcrogoblin's very thoughtful answer.

If anything else comes up let me know. Thanks again.
