### ISSUE TITLE
Are we using Hyperdev now?

### ISSUE THREAD

**Issue by Banananoops** [gordonmzhu/questions#404]
### What is the associated Watch and Code lesson?

Version 10, particularly starting [here](https://watchandcode.com/courses/60264/lectures/1102309)

I notice that you've stopped using Plunkr and are now using Hyperdev. Was this introduced in a previous lesson? Should I make a Hyperdev account and start following along with your lessons there?

**Comment by gordonmzhu** [comment]
No stick with VS Code for the entire course. See https://watchandcode.com/courses/60264/lectures/13412129.
