### ISSUE TITLE
forEach and debugger

### ISSUE THREAD

**Issue by nacafaca** [gordonmzhu/questions#405]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1125982

### Include a link to your code so I can run it on my computer. 

my script.js

var students = ['jonathan','jenny', 'elliot'];

function logName(name){
  console.log(name);
};

function forEach(myArray, myFunction){
  for(var i = 0; i < myArray.length; i++){
    myFunction(myArray[i]);
  }
}

function runWithDebugger(ourFunction){
  debugger;
  ourFunction();
}

runWithDebugger(forEach);
### Explain the exact steps I need to take to replicate the problem. 

1.  first I wrote a Array
    var students = ['jonathan', 'jenny', 'elliot'];
2. second I wrote a function logName()
    function logName(name){
      console.log(name);
    };
3. then I made function forEach()
    function forEach(myArray, myFunction){
         for(var i = 0; i < myArray.length; i++){
             myFunction(myArray[i]);
          }
    }
4. then I made function runWithDebugger()
    function runWithDebugger(ourFunction) {
     debugger;
     ourFunction();
   };
5. and finally I called
    runWithDebugger(forEach);

### What did you expect to happen? 

I wanted to go through the whole forEach() function with debugger.

### What actually happened? 

When I got into the forEach function, the debugger showed me a Type Error for .length property  on array
Uncaught TypeError: Cannot read property 'length' of undefined
    at forEach (forEach.js:8)
    at runWithDebugger (forEach.js:15)
    at forEach.js:18

### Describe what you've done so far to troubleshoot the problem. 

I was checked all code,  I was looking for a solution on StackOverflow.. But I didn't solve it.

I hope your answer and help!
Best regards,
your student Natalija

**Comment by gordonmzhu** [comment]
The `forEach` function you wrote defines two parameters (`myArray` and `myFunction`) and therefore expects two arguments.

When you call `forEach` in your code, what are the values of `myArray` and `myFunction`?

**Comment by nacafaca** [comment]
Oooh I see now! Thank you very much!

**Comment by gordonmzhu** [comment]
Yeah for sure.
