### ISSUE TITLE
displayTodos should show .todoText

### ISSUE THREAD

**Issue by Cabechin** [gordonmzhu/questions#406]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/956106 
It happens to me that I cant get the objects next to the result of displaying the todos .

### Include a link to your code so I can run it on my computer. 

var todoList = {
    todos: [],
  displayTodos: function() {
    if (this.todos.lenght === 0) {
       console.log('Your todo list is empty!');
      } else {
       console.log('My Todos:');
      for (var i = 0; i < this.todos.lenght; i++) {
       console.log(this.todos[i].todoText); 
      }
    }
  },

### Explain the exact steps I need to take to replicate the problem. 

I am a spanish native.. But i think I understand quite well. But i thought I followed the proper steps.. I dont really know.

### What did you expect to happen? 

I pretengd to overcome this.. as I cant keep on going >(

### What actually happened? 

todoList.displayTodos();
todosList.html:15 My Todos:
undefined
todoList.addTodo('second');
todosList.html:15 My Todos:
undefined

### Describe what you've done so far to troubleshoot the problem. 

WI watched te video and corrected the script a couple of times, but the thing keep on with out showing >(

**Comment by gordonmzhu** [comment]
Please provide your entire html file so that I can run your code and replicate the problem. It'll help to review https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603, especially rules 3 and 4.

**Comment by Cabechin** [comment]
Hi gordon, let me answer by here thats the only way I think, I could send you the file. Thanks a lot! I cant wait to reach advanced 😃Thanks! Have a nice weekend! Enviado desde Correo para Windows 10 De: Gordon ZhuEnviado: viernes, 27 de marzo de 2020 14:51Para: gordonmzhu/questionsCC: Cabechin; AuthorAsunto: Re: [gordonmzhu/questions] displayTodos should show .todoText (#406) Please provide your entire html file so that I can run your code and replicate the problem. It'll help to review https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603, especially rules 3 and 4.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
  
    Prueba Masterizada
  
  
     Hola hermanito!
    Seguile metiendo mostro!
   
     var todoList = {
     todos: [],
     displayTodos: function() {
       console.log('My Todos', this.todos);
     },
     addTodo: function(todoText) {
       this.todos.push({
         todoText: todoText,
         completed: false
       });
       this.displayTodos();
     },
     changeTodo: function(position, todoText) {
       this.todos[position].todoText = todoText;
       this.displayTodos();
     },
     deleteTodo: function(position) {
       this.todos.splice(position, 1);
       this.displayTodos();
     },
     toggleCompleted: function(position) {
       var todo = this.todo[position];
       todo.completed = !todo.completed;
       this.displayTodos();
     }
     };

**Comment by gordonmzhu** [comment]
Thanks for the code. So what is the problem exactly? What steps should I take to recreate the problem?

**Comment by Cabechin** [comment]
I am sonsrry for the shitty path i putted 😅 i feel im not following the
steps you explained in the printed list...
 In V4 when it add toggle true or false..
 While i try to display the objects afeter add them ad see them after
Todos, it apear {...}
 And the variables is not working /: thanks again

**Comment by gordonmzhu** [comment]
Resolved in office hours
