### ISSUE TITLE
issue-01

### ISSUE THREAD

**Issue by web-dot** [gordonmzhu/questions#407]
---------------------### What is the associated Watch and Code lesson? 

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### Include a link to your code so I can run it on my computer. 

https://gist.github.com/web-dot/7fb3bc6a602587f5265fc5454370cf10

### Explain the exact steps I need to take to replicate the problem. 

after opening in the browser, if I click on 'click me' button. It does not append the p element in dom.

### What did you expect to happen? 

after opening in the browser, if I click on 'click me' button. It should have appended the p element in dom.

### Describe what you've done so far to troubleshoot the problem. 

I have run the debugger, but  unable to understand why is the code not working.

**Comment by gordonmzhu** [comment]
What is the value of the buttons variable in the MDN example?

What is the value of the buttons variable in your example?

**Comment by web-dot** [comment]
i have figured it out, Thanks

**Comment by web-dot** [comment]
Hi,

i have figured out what the problem was, i have simplified the code and it
is working.
I have gone through the practical JavaScript curriculum, I feel that I need
to go through it again, which I am doing at present.

Once I have understood the concepts of Practical JavaScript better i want
to subscribe for the advanced course.

Thank You

**Comment by web-dot** [comment]
Hi,

i have figured out what the problem was, i have simplified the code and it
is working.
I have gone through the practical JavaScript curriculum, I feel that I need
to go through it again, which I am doing at present.

Once I have understood the concepts of Practical JavaScript i want to
subscribe for the advanced course.

Thank You

**Comment by gordonmzhu** [comment]
👍
