### ISSUE TITLE
stuck on var view, can't find typo, can't run debugger

### ISSUE THREAD

**Issue by DBNoisemaker** [gordonmzhu/questions#41]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1056225

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/3OZOAzAde4DbQt0yQLqo?p=preview

### Explain the exact steps I need to take to replicate the problem. 

enter code up to the 2:30 mark of the video, in preview target type view.displayTodos();  

### What did you expect to happen? 

expected for little bullet points to form in the UI for our list

### What actually happened? 

Uncaught ReferenceError: view is not defined
    at <anonymous>:1:1
in the past this has been a type, o.  I just can't find it.  Code was running fine up until var view was declared.  

### Describe what you've done so far to troubleshoot the problem. 

Tried running debugger to no avail.

**Comment by gordonmzhu** [comment]
Your code is not the same as the code I have in the lessons. You've missed a very large change that we made.

You should go back several versions to a point where your code still worked and then work your way back to the current lesson. As you do that, make sure that you have the same code at every step.

**Comment by DBNoisemaker** [comment]
Gordon is there any way of seeing your code independent of the videos, per lesson?
I'm having a really frustrating time trying to copy your pausing and fast forwarding and rewinding a video clip.

**Comment by gordonmzhu** [comment]
No, and even if you could, I wouldn't suggest that.

The root problem here is that you need to slow down and watch the lessons more carefully. The answer is right in the video. You just need to slow down enough to see it.

**Comment by gordonmzhu** [comment]
There is also a huge hint is right in the error message. It is telling you *exactly* what the problem is.

**Comment by DBNoisemaker** [comment]
error as in: view is not defined at 1:1 ?

**Comment by hydroweaver** [comment]
Hey @DBNoisemaker , you need to follow @gordonmzhu 's advice ! :), the plunkr editor is showing the error message, seek and find !

**Comment by DBNoisemaker** [comment]
hi @hydroweaver . thank you for your help.  I got it working somehow and not even sure what I did, but it was NEITHER of what you two said it was hahah.  I think i'm figuring it out that 'undefined at 1:1' meand I have a typo and I need to go find it my fucking self lol.  

here's the latest 

https://plnkr.co/edit/3OZOAzAde4DbQt0yQLqo?p=preview

**Comment by hydroweaver** [comment]
good if it works now, though it looks the latest plunk still has an error:

Script.js Line 42, if is missing starting paren

if this.todos[i].completed === true){
