### ISSUE TITLE
It should have a place to store todos 

### ISSUE THREAD

**Issue by t3ztsng** [gordonmzhu/questions#412]
Ok just a suggestion. You said there were only 2 things to create an array (list). They were ' and [ ], isn't good practice to include ; ?

Just a beginner learner. I have yet to watch the rest of your videos, so im sure it might come up then. 

Terry

**Comment by gordonmzhu** [comment]
Where do I say that in the video? Can you provide a timestamp?

**Comment by t3ztsng** [comment]
I've watch more of your videos and it has addressed this. Please ignore my statement
