### ISSUE TITLE
todoLi.textContent what is this??

### ISSUE THREAD

**Issue by samuelefabbro** [gordonmzhu/questions#413]
It's not an issue. But something I don't understand. In the view object when you set todoLi.textContent = todoTextWithCompletion; what is .textContent??? Don't get it. Thanks.

**Comment by gordonmzhu** [comment]
What video are you on?

**Comment by samuelefabbro** [comment]
Practical Javascript - Version 9 - Each li element should show .completed

Thanks Sam

**Comment by gordonmzhu** [comment]
You should go back and review the last few videos. I explain it earlier in V9.
