### ISSUE TITLE
Help with Practical JavaScript

### ISSUE THREAD

**Issue by Jay13thstep** [gordonmzhu/questions#414]
Version 4 - Booleans - todoList.changeTodo should change the todoText property

Write your response here (required).
### Include a link to your code so I can run it on my computer. 
<!DOCTYPE html>

<html>
  <head>
    <title>Practical JavaScript</title>
  </head> 

  <body>
    HTML GOES HERE
    <script>
        var todoList = {
          todos: [],
          displayTodos: function() {
            console.log('My Todos', this.todos);
          },
          addTodo: function(todoText) {
            this.todos.push({
              todoText: todoText,
              completed: false
            });
            this.displayTodos();
          },
          changeTodo: function(position, todoText) {
            this.todos[position].todoText = todoText
            this.displayTodos();
          },
          deleteTodo: function(position) {
            this.todos.splice(position, 1);
            this.displayTodos();
          }
        };
    </script>
    </body>
</html>

Write your response here (required).
Hi Gordon, good to talk to you. I'm just checking in to make sure I'm doing the right thing at this point in the course. When I run my code (above) as mentioned in the video, I get the following:

todoList.addTodo('first try');
todoList.html:14 My Todos 
[{…}]
0: {todoText: "first try", completed: false}
length: 1
__proto__: Array(0)

This looks different to your screen but I'm not sure if this is because you are using Plunker? All the text is in my version, but it is just displayed differently. Before I continue I'd just like to make sure if this is correct or not. I've been over the section a few times and referred back to your important note, and I'm honestly not quite sure what I should be expeting to see here. 

Many Thanks
Jamie

**Comment by gordonmzhu** [comment]
Hey Jamie, what you're getting is normal, nothing to worry about. Chrome changed how they display objects, so everything looks slightly different from when I recorded this video.
