### ISSUE TITLE
My variable displayTodosButton returns the value Null -same issue more questions

### ISSUE THREAD

**Issue by nabinbaidya** [gordonmzhu/questions#416]
Tutorial: https://watchandcode.com/courses/60264/lectures/987943

The issue is same as pointed in this link 
https://github.com/gordonmzhu/questions/issues/389#issue-564212361 
and 
https://github.com/gordonmzhu/questions/issues/393

As replied moving the script tag at the bottom before the body tag worked. But I have more questions now:

1. My variable displayTodosButton returns the value Null, and the solution says the DOM was not fully loaded. But it worked in the tutorial video. Why? 
2 In the same issue, in another thread (the second link above) Gordon points that its a typo. I searched for a typo but could not find one, but after moving the script tag before the closing body tag the code worked fine. Is there still a typo?
3  I read that moving the script tag to the bottom reduces performance and have to use the async feature. Is it necessary here and if so how do I use that?

**Comment by gordonmzhu** [comment]
1. What is the "solution" you're referring to? Are you referring to a video? If so, what timestamp?
2. Issue #393 has nothing to do with script tags. There is a typo in the code. If you look closely you will find it.
3. I'm not going to discuss performance at this time because it's not the right time to discuss it. You need more context before we can have this discussion.

**Comment by t3ztsng** [comment]
Hi Gordan, I'm also come into contact with the same problem, I think. 

Having followed the course. I have not had the same success you had on this particular video. 
Time stamp 5:09 on this video, suggest the console box to print out the button we want. My console did not look like yours. [object HTML button]..... is there a setting missing?

However I persevered and followed your example. 
var displayTodosButton = document.getElementById('displayTodosButton');
console.log(displayTodosButton);

displayTodosButton.addEventListener('click', function() {
  todoList.displayTodos();  
});

the console  displayed null for the first part of this, before even clicking the button. I've watched this video multiple times, minimum 10 times So this is why I've decided to message you. I've spent at least a couple of hours on this task alone. And I looked over my code 100's of time. Do you have a source code where i can compare? I even looked through the old videos to make sure my code was correct. All the brackets and semi colons etc.

The second part of the code comes up with an error message: 

Uncaught TypeError: Cannot read property 'addEventListener' of null
    at VM3974 script.js:78

Please advise.

**Comment by nabinbaidya** [comment]
Thank you for the quick reply Gordon. As t3ztsng points out I have the exact problem.
1. I solved the problem "displayTodosButton" returns value Null just by moving the script tag from the head section to the body section just before the closing body tag. Then, the addEventListener function on click also works. 
So, my question is if my code works by moving the script tag, why does it not work like you have shown in the tutorial https://watchandcode.com/courses/60264/lectures/987943
2. I can only see incomplete code for issue #393 but s/he was having the same problem. So I thought it must be a typo in my code too. Hence, the same question as 1.
3. I still have to learn a lot more basics to reach that async functionality as you pointed. Thanks.

**Comment by t3ztsng** [comment]
Hey nabinbaidya, I tried to move the script from the <head> section to the <body> section like you did, but still there was no difference. 

I'm having no luck. My brain is going crazy in this section. Feel like I've wasted a big chunk of my time.

**Comment by t3ztsng** [comment]
Just to update you nabinbaidya and Gordon. 

Placing <script src="lib/script.js"></script> on the line before the closing body </body> did in fact get this problem solved to my amazement. 

Placing the script element above the buttons tags did not get the same result, in fact the problem I had before. You might want to update the video so people like myself don't have to pull their hair out like I had. Hahaha

**Comment by t3ztsng** [comment]
Ah dam, I've come across another problem.  

VM299:1 Uncaught ReferenceError: todoList is not defined at <anonymous>:1:1

It doesn't recognise the todoList object some how. So I cannot add stuff into the todos list. 

I'll have another crack it.  :(

**Comment by t3ztsng** [comment]
Ok I've spent a considerable amount of time on this and I have come to the conclusion that the culprit is in fact Plunker! When i copy and pasted the code into a javascript file and of course created the index files and so on in visual studio code. I had no problems viewing this in chrome.

Viewing this on chrome showed no errors. However as above the <script> had to be placed before the closing body element </body>. So is this the case in general? Why does it seem to work in your example in the head element section and not mine?

**Comment by gordonmzhu** [comment]
@nabinbaidya @t3ztsng Please follow the file structure that I use as described in this section: https://watchandcode.com/courses/60264/lectures/13410406. If you follow those directions exactly, everything will work.

**Comment by nabinbaidya** [comment]
Thank you Gordon for a great course. This is the only course I  finished after looking into several ones. I think you gave me the right motivation to continue on. Due to national banking reasons I can't subscribe further. They say javascript.info is a great tutorial. Moving on. Thanks once again.

**Comment by gordonmzhu** [comment]
You're welcome @nabinbaidya. Best of luck with everything.
