### ISSUE TITLE
Suggestion to clarify 'this'

### ISSUE THREAD

**Issue by powerfrost** [gordonmzhu/questions#418]
### What is the associated Watch and Code lesson?

https://watchandcode.com/courses/60264/lectures/1181252
4:25

Suggestion to improve explanation (required).

![Screenshot 2020-04-17 at 4 31 22 PM](https://user-images.githubusercontent.com/8880210/79549141-2671de80-80c9-11ea-817c-3bf166b4157a.png)
I think explaining the Call Stack at this video will make it much clearer to the student where they are. In this case, they are in the anonymous callback function forEach. 

The sequence of on the call Stack is

1. onclick 
2. toggleAll (from handlers object)
3. displayTodos (from view object)
4. anonymous (from anonymous function used in forEach)

**Comment by gordonmzhu** [comment]
Thanks for the suggestion @powerfrost. Agree with you that introducing the call stack earlier will help. I'll think about how to work this in.
