### ISSUE TITLE
todoTextWithCompletion not firing

### ISSUE THREAD

**Issue by DBNoisemaker** [gordonmzhu/questions#42]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1056227

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/3OZOAzAde4DbQt0yQLqo?p=preview

### Explain the exact steps I need to take to replicate the problem. 

add a todo and toggle, the '( )' and '(x)' isn't showing up in the View.  the todo Item is, just not the check.

### What did you expect to happen? 

expected ( ) and (x) to show up. 

### What actually happened? 

the rest works, just not that bit. 

### Describe what you've done so far to troubleshoot the problem. 

Gone over the video again to see if there are typos but couldn't see any.  ran debugger  ut didn't gain anything useful from it.

**Comment by hydroweaver** [comment]
@DBNoisemaker you've had the following problems:

1. Line 42 still not have an opening brace for if condition
2. On multiple occasions, you've not referenced the specific todo with the variable i, therefore the program is unable know which todo should be toggled, see lines 9 and 48
3. Your program is missing the second condition of checking the toggle all todos - this however is NOT related to the current problem.

**Comment by DBNoisemaker** [comment]
@hydroweaver thank you for taking the time to help me out.  
1.) My line 42 is:    if (this.todos[i].completed === true) {
     is this ^ not what Gordon has in the example?  
2.) ok I see those lines have "this.todos[i].completed", but as far as i know I have the [i] everywhere that was suggested by Gordon, the other places where this.todos is referenced it is accompanied by parameters like position, length, etc...

3.  My toggleAll function is below, and has both conditions, yea? 

toggleAll: function() {
    var totalTodos = this.todos.length;
    var completedTodos = 0;
    
    for (var i = 0; i < totalTodos; i++) {
      if (this.todos[i].completed === true) {
        completedTodos++;
      }
    }
    if (completedTodos === totalTodos) {
      for (var i = 0; i < totalTodos; i++) {
        this.todos[i].completed = false;
      }
    } else {
      for (var i = 0; i < totalTodos; i++) {
        this.todos[i].completed = true;
      }
    }this.displayTodos();
  }

link to my code: https://plnkr.co/edit/3OZOAzAde4DbQt0yQLqo?p=info

**Comment by DBNoisemaker** [comment]
issue is resolved, it was something else in var view, 
thank you.
