### ISSUE TITLE
Version 6 - Thinking in Code Problem

### ISSUE THREAD

**Issue by Jay13thstep** [gordonmzhu/questions#420]
https://watchandcode.com/courses/60264/lectures/975957 - 2min 15 seconds onwards

Hi Gordon, 

Link to my code as follows - https://gist.github.com/Jay13thstep/62584eaab57ff2914aacefa76b661e47

I'm getting an issue with line 57 (I think) which means I'm unable to run the code at all in Chrome. I get the following error message: todoList.html:57 Uncaught SyntaxError: Unexpected token 'if'

I've looked at your code and gone back to the beginning of the lesson to redo mine numerous times and cant figure out at all where mine differs from yours. When I follow along and type todoList.addTodo('first'); in the console the error message shows.  Are you able to advise?

Many Thanks
Jamie

**Comment by gordonmzhu** [comment]
Hey @Jay13thstep. I took a look and your code is quite different. It's important to make sure that you follow things exactly and have character-by-character precision.

I suggest going back in time to a point where your code worked and then working back from there. If you do that, you'll spot where you veered off.
