### ISSUE TITLE
Certain tutorial videos failing to play

### ISSUE THREAD

**Issue by johnfunston** [gordonmzhu/questions#422]
### What is the associated Watch and Code lesson? 

following videos will not play:
https://watchandcode.com/courses/60264/lectures/1102308
https://watchandcode.com/courses/60264/lectures/1102312
https://watchandcode.com/courses/60264/lectures/1102313
https://watchandcode.com/courses/60264/lectures/1181249
https://watchandcode.com/courses/60264/lectures/1181250

### Include a link to your code so I can run it on my computer. 

n/a

### Explain the exact steps I need to take to replicate the problem. 

Using both Mac and Windows operating systems, and firefox/chrome as a browser, these videos fail to play when they are clicked.

### What did you expect to happen? 

n/a

### What actually happened? 

Clicking the play button seemed to refresh the video, but not play it.

### Describe what you've done so far to troubleshoot the problem. 

I've tried to load the videos on multiple browsers (safari, firefox, and chrome) on my Windows PC and my Mac laptop. I also tried to select the autoplay button and reload the page, but even with autoplay selected the videos will not play.

P.S. I'm really enjoying your course so far! You're an excellent teacher and the way you explain concept concretely while relating them to the 'big-picture' really suits my learning style. I'm looking forward to continuing on to your premium content once I've finished with Practical Javascript.

All the best.

**Comment by gordonmzhu** [comment]
Hey @johnfunston can you check again? I just tried all the links you shared and the videos loaded fine. Thinking this might have been a temporary issue.

**Comment by johnfunston** [comment]
Hey Gordon,
It looks like you may be right on it being a temporary issue. I tried them again just now and they seems to be working fine. Not sure what may have caused it. Thanks for getting back to me.
