### ISSUE TITLE
DisplayTodos button not working 

### ISSUE THREAD

**Issue by tfaru** [gordonmzhu/questions#424]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/987943
DisplayTodos should run todo list.displayTodos

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

// javascript begins here
var todoList = {
  todos: [],
  displayTodos: function () {
    if(this.todos.length === 0){
      console.log('Your todo list is empty!');
    } else {
    console.log('My Todos: ');
    for (var i = 0; i < this.todos.length; i++) {
    console.log(this.todos[i].todoText);
    if(this.todos[i].completed === true) {
      console.log('(x)', this.todos[i].todoText)
    } else {
      console.log('( )', this.todos[i].todoText)
          }
       }
    }
},
addTodo: function(todoText) {
  this.todos.push({
    todoText: todoText,
    completed: false
  });
  this.displayTodos();
  },
changeTodo: function(position, newValue) {
  this.todos[position].todoText = newValue;
  this.displayTodos();
},
deleteTodo: function(position) {
  this.todos.splice(position, 1);
  this.displayTodos();
},
toggleCompleted: function(position) {
  var todo = this.todos[position];
  todo.completed = !todo.completed;
  this.displayTodos();
},
toggleAll: function() {
  var totalTodos = this.todos.length;
  var completedTodos = 0;
  for(var i = 0; i < totalTodos; i++) {
    if(this.todos[i].completed === true){
      completedTodos++;
    }
  }
  if (completedTodos === totalTodos) {
    for(var i = 0; i < totalTodos; i++) {
      this.todos[i].completed = false;
    }
  } else {
    for(var i = 0; i < totalTodos; i++) {
      this.todos[i].completed = true;
    }
  }
  this.displayTodos();
}

};

var displayTodosButton = document.getElementById('displayTodosButton');
console.log(displayTodosButton);

displayTodosButton.addEventListener('click', function(){
  todoList.displayTodos();
});
<-- HTML begins here -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="index.js"></script>

  <title>TodoList</title>
</head>
<body>
  <h1>Todo List</h1>

  <button id = "displayTodosButton">Display Todos</button>
  <button>Toggle All</button>
</body>
</html>

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

I am coding in VS code and use Chrome as my default browser/ server.
I finished the episode wrote out the code for HTML and Javascript and my display todos button does not connect to displaytodos

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

When I click on the display todos button my console displays a null value and the event listener doesn't work. Here is the error message taken off of my console.

 null
index.js:63 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at index.js:63

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

I've tried rewatching past videos including this one to figure out why it is not working.  I believe that my toggleAll function might be bugging out because there is a red error line under i , where it gives me i' is already defined.eslint(no-redeclare) . However, my toggleAll function works so I'm not sure if that is the culprit. 

Write your response here (required).

**Comment by tfaru** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="index.js"></script>

  <title>TodoList</title>
</head>
<body>
  <h1>Todo List</h1>

  <button id = "displayTodosButton">Display Todos</button>
  <button>Toggle All</button>
</body>
</html>

**Comment by tfaru** [comment]
![image](https://user-images.githubusercontent.com/54218913/80773277-44e6c980-8b0e-11ea-937e-d67c81618750.png)

**Comment by tfaru** [comment]
I expected the todos button to displayTodos in the console

**Comment by gordonmzhu** [comment]
Can you provide me with the files as requested in the issue template? 

```
"For Practical JavaScript, just paste the contents of your todoList.html to gist.github.com and share the link."
```
