### ISSUE TITLE
Avoid adding an undefined element in our todo list

### ISSUE THREAD

**Issue by virtualbis** [gordonmzhu/questions#427]
Hello Gordon,
My son Tom and I have decided to build an app (long term goal) and are beginning with your JS course. Great approach and explanations so far. To the issue now:

Lesson in functions: It should have a function to display todos https://watchandcode.com/courses/60264/lectures/928384

In writing the function and testing it to add a todo and display it we noticed it worked fine when we actually entered a new todo such as:

`addTodo('do something')`

This added "do something" as expected to the end of the lost of todos.

When we mistakenly only entered the the function without anything in the brackets we noticed an "
undefined" element in our todo list was added. It looked like this:
`["item 1", "item 2", "item  3", "do something", undefined]`

Being proactive and wanting to avoid needlessly adding undefined into a list we decided we would go off course and add some error handling or at least an if statement to at least send us a reminder that we need to enter a value in the brackets. This is where we started getting stumped.

So far in the if statement this is what we have and this is where we've been stumped. How would we correctly use an if statement in this situation? 
`if (typeof addTodo === "undefined")
    {console.log('you need to add a todo sir!');}
else {
function addTodo(newTodo) 
{
todos.push(newTodo);
console.log(todos);
}}`

Also, we were wondering if instead of an if statement we could somehow use and error handler such as onerror to solve the same issue? If so, how? Sorry, I know that's 2 questions but I'm guessing there are at least 2 ways to resolve our issue. :-)

**Comment by virtualbis** [comment]
We're also new to Github so are not sure how to ask questions properly or really how to use Github properly yet. If you could point us to any good resources we would be grateful.

**Comment by gordonmzhu** [comment]
You need to think in more detail about the situation that creates `undefined` todos.

For example, what are concrete differences between

Situation A: `addTodo('do something');`

and

Situation B: `addTodo();`

Once you better understand the difference between A and B, you'll able to figure this problem out. I'd recommend reviewing https://watchandcode.com/courses/60264/lectures/2368421.

**Comment by virtualbis** [comment]
We spent probably 3 hours each going down rabbit holes trying to figure
this out on our own and another hour after your response. Are you able to
help or give another clue? I went over the video lesson again an honestly
do not see the link.

Thank you,
Shawn

<http://ca.linkedin.com/in/shawnfawcett>

**Comment by virtualbis** [comment]
We finally go it

`Thank you. I was staring at it for too long. Below is our final code for this:
function addTodo(newTodo) {
if (typeof newTodo === "undefined"){ // see how it says 'typeof newTodo' instead of addTodo
console.log("Whoops! You didn't type anything in the brackets!");
} else {
todos.push(newTodo);
console.log(todos);
console.log('Successfully add Todo!');
}
}`

**Comment by gordonmzhu** [comment]
Nice job. Yeah the reason I wanted you to review https://watchandcode.com/courses/60264/lectures/2368421 is that it focuses on the value of `newTodo`. In your `if` statement you can do the right thing if you're aware of whether `newTodo` is `undefined` or not.
