### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null error 

### ISSUE THREAD

**Issue by Sabila97** [gordonmzhu/questions#428]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/1102312

### Include a link to your code so I can run it on my computer. 

Write your response here (required).
https://sabila97.github.io/coursera-assignments.github.io/TodoList/

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
Yes I clicked three buttons in a specific order. no, it didn't work fine in chrome or anywhere else.

### What did you expect to happen? 

Write your response here (required).
I expected to get the id (0/1/2) of the li tag in the console when I clicked the delete button. And I followed exactly the code you used in the lesson.

### What actually happened? 

Write your response here (required).
The id (0/1/2) of the li tag of the respective button I clicked didn't show up in the console. 
Uncaught TypeError: Cannot read property 'addEventListener' of null error showed up in the console instead.

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
I reviewed the lesson where the function(event) was discussed and used the debugger as well. and checked if the ul tag is null. the ul tag was not empty.

**Comment by gordonmzhu** [comment]
Make sure you follow the directions here: https://watchandcode.com/courses/60264/lectures/13412129
