### ISSUE TITLE
WHERE TO GET PLUNKER PREVIEW TARGET

### ISSUE THREAD

**Issue by kojo-adonteng** [gordonmzhu/questions#430]
### What is the associated Watch and Code lesson? 

MY CONSOLE DOESN'T SHOW THE PLUNKER PREVIEW TARGET. I USE GOOGLE CHROME, IS THERE A PLUG-IN I NEED TO INSTALL?

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Please make sure you go through the course carefully. It no longer uses plunker. Follow the directions as stated and you will not have this issue.

https://watchandcode.com/courses/60264/lectures/13410406
