### ISSUE TITLE
program for drawing circles and lines

### ISSUE THREAD

**Issue by joeytuholski** [gordonmzhu/questions#434]
### What is the associated Watch and Code lesson?  https://watchandcode.com/courses/practical-javascript/lectures/4350616

Write your response here (required). Hey man, I don't think I missed it in the lessons. Which program do you use to mark up code with circles and lines? I had trouble finding a good one for my version os. Thanks so much for your help man, this course is great and I'mn doing it daily. 

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
I'm using an iPad pro with Apple Pencil.
