### ISSUE TITLE
Question about addTodo function

### ISSUE THREAD

**Issue by burklindahl** [gordonmzhu/questions#435]
### What is the associated Watch and Code lesson? 

Version 2 - Functions.  Review section (4:15)

### Include a link to your code so I can run it on my computer. 

I absolutely love your approach with Watch and Code!  I feel like I'm already learning something valuable and look forward to becoming a Premium member at some point. 

Just a quick question to help me learn (not a problem or error per se).  In the addTodo function, I see that we are using todo (or I suppose we could use any word, really) as the parameter and todos.push(todo) to add a new item to the todos array.  I noticed that, for this to work properly, when we call the addTodo function, we have to pass the argument in using quotations (I assume so that what we pass in is a string) or we get an unexpected syntax error.

Is there an easy way to have the addTodo function accept any text entered in as an argument without the need for quotation marks?  So, as an example:

Instead of entering:  addTodos("new item")
Just enter:  addTodos(new item)  

### Describe what you've done so far to troubleshoot the problem. 

I tried using .toString but I learned that really only works with converting numbers to strings. I was also playing around with .unshift but I see that requires passing in a string as well.  While it's certainly no big deal to add quotes around whatever I try to pass in as an argument, I was just curious if there was a way to automatically convert whatever gets passed into an argument as a string in case a user/me forgot to add quotes.  Thanks!

**Comment by gordonmzhu** [comment]
You can pass in any type of data that data JavaScript can recognize. `new item` is not any recognized data type so you will get an error.
