### ISSUE TITLE
Wrong Output

### ISSUE THREAD

**Issue by PatrickColleton** [gordonmzhu/questions#436]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/936334

### Include a link to your code so I can run it on my computer. 

 var todoList = {
  todos: ['item 1', 'item 2', 'item 3'],
  displayTodos: function() {
    console.log('My Todos', this.todos);
  }
};

### Explain the exact steps I need to take to replicate the problem. 

In Plunker, when I type "todoList.displayTodos" in the console, the output is: 
ƒ () {
    console.log('My Todos', this.todos);
  }

### What did you expect to happen? 

I expected the array the todoList to display to the console, instead of the text of the function.

### What actually happened? 

As above.

### Describe what you've done so far to troubleshoot the problem. 

I made sure my code exactly matched the code you were typing on screen. No typos that I can find.

**Comment by gordonmzhu** [comment]
Where in the video you linked do I ever type `todoList.displayTodos` in the console?

**Comment by PatrickColleton** [comment]
I fixed it, I was missing "()" in "todoList.displayTodos()"

Patrick Colleton
(973) 862-8315
LinkedIn.com/in/PatrickColleton

**Comment by gordonmzhu** [comment]
👍
