### ISSUE TITLE
Version 2 - Functions | Add new todos

### ISSUE THREAD

**Issue by CharlesPublishing** [gordonmzhu/questions#437]
https://watchandcode.com/courses/60264/lectures/928385

Hi Gordon, As far as I can see, I'm following your instruction correctly, however obviously i'm missing something as I don't seem to be getting the desired outcome.
_____________________________________________
var listing = ['listing 1', 'listing 2', 'listing 3']
undefined
listing
(3) ["listing 1", "listing 2", "listing 3"]
function displayListing() {
console.log('Current Listings:',listing);
}
undefined
displayListing()
VM5393:2 Current Listings: (3) ["listing 1", "listing 2", "listing 3"]
undefined
function addListing(listing) {
listing.push(listing);
}
undefined
addListing()
VM5539:2 Uncaught TypeError: Cannot read property 'push' of undefined
    at addListing (<anonymous>:2:9)
    at <anonymous>:1:1
addListing @ VM5539:2
(anonymous) @ VM5569:1
function addListing() {
listing.push('new listing');
}
undefined
addListing()
undefined
displayListing()
VM5393:2 Current Listings: (4) ["listing 1", "listing 2", "listing 3", "new listing"]
undefined
function addListing(next listing) {
listing.push(next listing);
displayListing();
}
VM5927:1 Uncaught SyntaxError: Unexpected identifier
function addListing(listing 1) {
listing.push(listing 1);
displayListing();
}
VM5952:1 Uncaught SyntaxError: Unexpected number
_____________________________________________

<img width="983" alt="Screen Shot 2020-05-18 at 12 21 36" src="https://user-images.githubusercontent.com/35143144/82208358-47656380-9903-11ea-8d99-ef7f5d3b0d2a.png">

**Comment by gordonmzhu** [comment]
As your code is written, it will not work. I would recommend that you follow my code exactly. If you do that, things will run as expected. AFTER you get your code to work as-described in the videos then feel free to modify it. If you do things that way, it'll be easier to follow along.
