### ISSUE TITLE
Hi, I cannot launch nothing in Visual Studio... can you help me?

### ISSUE THREAD

**Issue by yoelmartinfornieles** [gordonmzhu/questions#438]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/900211

### Include a link to your code so I can run it on my computer. 

Hi! so you asked us to install visual studio code, but then you are not using it in the videos. When i try to run the program i get stucked on errors, like first i realized i didnt jave node.js installed, and now the debugger its not running... maybe we need a bit of help installing the environment! thanks

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Follow the steps that are in this video to run the code https://watchandcode.com/courses/60264/lectures/13412129.

**Comment by yoelmartinfornieles** [comment]
Yeah! I know! But i wanted to let you know that maybe im not the only one who stopped a bit frustrated at that point!
Anyways thank you so much for your help and dedication, your videos are really helpful! :)

Yoel Martin Fornieles
