### ISSUE TITLE
Why use a new object instead of using todoList object?

### ISSUE THREAD

**Issue by reeder324** [gordonmzhu/questions#439]
### What is the associated Watch and Code lesson? 

**https://watchandcode.com/courses/60264/lectures/1027547**

### Include a link to your code so I can run it on my computer. 

**<button onclick="todoList.toggleAll()">Toggle All</button>**

### Explain the exact steps I need to take to replicate the problem. 

**It's not a problem. Just a question on why 1 way vs the other**

### What did you expect to happen? 

**It still worked for me when I used todoList.toggleAll() instead of handlers.toggleAll()**

### What actually happened? 

**It worked the same**

### Describe what you've done so far to troubleshoot the problem. 

**I tested both ways, and they both worked.**

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97.
