### ISSUE TITLE
Refactoring - <button onclick=".....">

### ISSUE THREAD

**Issue by bombinaCCio** [gordonmzhu/questions#44]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547

### Include a live demo link so that I can run your code. 

http://next.plnkr.co/edit/K6Bv43x8jVzfrKapWvtP?preview

### Explain the exact steps I need to take to replicate the problem. 

Why do we need to create a new variable 'handlers' with the all events and not use as below
considering that all theese events are already created ? Is just for a better code organization? 
And isn't breaking the "rule":  do not repeat yourself ?

**`<button onclick="todoList.displayTodos()"> Display Todos </button>`**

**Comment by gordonmzhu** [comment]
As long as it works the same way, it's just an organization issue.

It's like deciding where to put dishes away in a cabinet. Some people will make different choices. There isn't "one way" to do it.

**Comment by pragun1993** [comment]
I just saw this and was about to ask the exact same question. I too felt that when `todoList` had already been declared as a global object, we could have used it  for calling functions directly .
