### ISSUE TITLE
Booleans lecture 4 todoList.toggleCompleted

### ISSUE THREAD

**Issue by Texx45** [gordonmzhu/questions#440]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/946811
(4:45) on video

### Include a link to your code so I can run it on my computer. 

https://gist.github.com/Texx45/d4d4abe55f5eb4a247a279e76601fc13

### Explain the exact steps I need to take to replicate the problem. 

Try running todoList.toggleCompleted(0); in the console

### What did you expect to happen? 

I expected toggleCompleted to be returned as true

### What actually happened? 

Uncaught TypeError: todoList.toggleCompleted is not a function at <anonymous>:1:10

### Describe what you've done so far to troubleshoot the problem. 

I have gone back several lectures, been through them, checked for typos and then retyped the last section. 

![Screenshot (98)](https://user-images.githubusercontent.com/63190272/82667132-20729e80-9c2f-11ea-89f2-5d92ce09f37e.png)

**Comment by gordonmzhu** [comment]
I ran your code and wasn't able to replicate the issue. Be sure to send me your exact file as there might be something wrong you're doing with the formatting of the `html` file.

**Comment by Texx45** [comment]
I also ran it through Brackets just to make sure it wasn't VSC and got the same error.

Here is the exact file:

https://gist.github.com/Texx45/d4d4abe55f5eb4a247a279e76601fc13


![Screenshot (99)](https://user-images.githubusercontent.com/63190272/82722099-72610600-9cbb-11ea-885f-c1587f2dd99d.png)
