### ISSUE TITLE
Still having problems - link updated to exact file 

### ISSUE THREAD

**Issue by Texx45** [gordonmzhu/questions#442]
What is the associated Watch and Code lesson?
https://watchandcode.com/courses/60264/lectures/946811
(4:45) on video

Include a link to your code so I can run it on my computer.
https://gist.github.com/Texx45/d4d4abe55f5eb4a247a279e76601fc13

Explain the exact steps I need to take to replicate the problem.
Try running todoList.toggleCompleted(0); in the console

What did you expect to happen?
I expected toggleCompleted to be returned as true

What actually happened?
Uncaught TypeError: todoList.toggleCompleted is not a function at :1:10

Describe what you've done so far to troubleshoot the problem.
I have gone back several lectures, been through them, checked for typos and then retyped the last section.  It was all working until the toggleCompleted section of code.

I have tried the code through Brackets instead of VSC and get the same error. I also ran the code on my laptop and got the same error. 

![Screenshot (99)](https://user-images.githubusercontent.com/63190272/82786680-f43c6500-9e5c-11ea-83ce-33a37d699731.png)

**Comment by gordonmzhu** [comment]
How many todos are in the array when you run `toggleCompleted`?

**Comment by Texx45** [comment]
Thank you! I understand and have corrected, now onto the next section .

**Comment by gordonmzhu** [comment]
👍
