### ISSUE TITLE
displayTodos should tell you if .todos is empty not working for me

### ISSUE THREAD

**Issue by DoviMaj** [gordonmzhu/questions#446]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/956109

### Include a link to your code so I can run it on my computer. 

https://gist.github.com/DoviMaj/8968e4dc7ea449f2f81588ba4ea70f57

### Explain the exact steps I need to take to replicate the problem. 

when the list is empty the displayTodo isnt running the condition. its falling always into the else. it should say your list is empty when list lenght  === 0.

![screenshot-nimbus-capture-2020 06 01-00_49_14](https://user-images.githubusercontent.com/36450233/83363413-ee390d80-a3a1-11ea-8e78-d1bc9611740e.png)

**Comment by gordonmzhu** [comment]
Check your `displayTodos` method for typos. In the future, you'll want to be more careful. Every character needs to be correct in programming.
