### ISSUE TITLE
Q re the DOM

### ISSUE THREAD

**Issue by Phrilly** [gordonmzhu/questions#449]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027554 timestamp: 4.33

### Include a link to your code so I can run it on my computer. 

Its not a code issue at my end, its your explanation and you ruse of ".value" for the first time

### Explain the exact steps I need to take to replicate the problem. 

you state that "we can't pass this element directly in, but we can do something really close, remember this is the DOM input so we have to grab the value."  - this is the first use of the property "value" in all the code created so far and as a programmer brought up in the old school its difficult to understand why a variable that you have just declared in this "var addtodotextinput" cannot then be passed as the argument in the function.

### What did you expect to happen? 

I expected to be able to pass the variable addtodotextinput without having to get its property value.  what's more the property value is new to me and seems somewhat generic, it could mean anything really ....

### What actually happened? 

I think I can see that the newly declared variable addtodotextinput is an object and that you can't pass that (is that right?) since it would be passing a reference to an object, but what has it got to do with the DOM ?

### Describe what you've done so far to troubleshoot the problem. 

I looked back at the videos on the DOM which states that the DOM is what the browser understands the document to be, but that doesn't seem to add anything here rather it confuse a bit

Thank so much!  Phil

**Comment by gordonmzhu** [comment]
Try passing in addTodoTextInput instead of addTodoTextInput.value and note any differences.
