### ISSUE TITLE
my addEventListener is not working...after clicking the displayTodoButton nothing happening

### ISSUE THREAD

**Issue by yasasvy** [gordonmzhu/questions#45]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by hydroweaver** [comment]
@yasasvy Could you please provide all the details in the given format above? The video link, the plunkr link and explain the problem.

**Comment by gordonmzhu** [comment]
@yasasvy Please open a new issue and include all the required fields. Once I see the new issue, I'll take a look. In the meantime, closing this one.
