### ISSUE TITLE
Why didn't we call functions in html using already existing todoList object?

### ISSUE THREAD

**Issue by gansach** [gordonmzhu/questions#453]
**Version 8** 
Lesson 1: Our first refactoring (https://watchandcode.com/courses/60264/lectures/1027547)
Timestamp: 4:12

Hey Gordon, so in version 8 we are refactoring our code and so instead of using eventlisteners in the js file we are adding onclick attributes to our button tags in the index.html file. As the arguments to the onclick attribute we have to pass in functions. So, why aren't we passing todoList.displayTodos(), instead we are making an object **handlers** and we are giving it a property displayTodos which is assigned to refer to todoList.displayTodos()

**My code:**
`<button onclick="todoList.displayTodos()">Display Todos</button>`
`<button onclick="todoList.toggleAll()">Toggle All</button>`

**Instead of:**
In index.html
`<button onclick="handlers.displayTodos()">Display Todos</button>`
`<button onclick="handlers.toggleAll()">Toggle All</button>`

in script.js
`let handlers = {`
`  displayTodos: () => todoList.displayTodos(),`
`  toggleAll: () => todoList.toggleAll()`
`};`

**todoList.html: **https://gist.github.com/gansach/c1fecc3a9a20e775d90c9796617eb627

**Comment by gordonmzhu** [comment]
See https://github.com/gordonmzhu/questions/issues/97.
