### ISSUE TITLE
Difficulty in implementing a more generic runTheDebugger() function

### ISSUE THREAD

**Issue by rmohan91** [gordonmzhu/questions#455]
Hi I have two questions related to the following two lectures: 
https://watchandcode.com/courses/60264/lectures/1122689
https://watchandcode.com/courses/60264/lectures/2762323

After having a look at the debugger lecture, I tried to implement a more generic debugger function that can debug all the methods in the course. On stackoverflow, I found a more general alternative for passing parameters into a higher order function (https://stackoverflow.com/questions/3458553/javascript-passing-parameters-to-a-callback-function). My code currently looks like this:

function runTheDebugger(){ 
  debugger;
  arguments[0](arguments[1], arguments[2]);
}

I tried running runTheDebugger for the addTodo method in console as follows:
runTheDebugger(toDoList.addTodo, 'new item')

But I received the following error:
script.js:5 Uncaught TypeError: Cannot read property 'push' of undefined
    at Arguments.addTodo (script.js:5)
    at runTheDebugger (script.js:119)
    at <anonymous>:1:1
addTodo @ script.js:5
runTheDebugger @ script.js:119
(anonymous) @ VM2116:1

After watching the "Case 5: When you are in a call function" lecture (and the previous lectures) I interpreted my error as follows: The "this" that is referring to the todoList object in the addTodo method is not defined in the higher order function. 

Question: Is this interpretation correct? How do I point my higher order function to the "this" inside the addTodo function? 

Looking at the various cases covered in the lecture I could not really find a way to implement this. I have attached my current code if you want to replicate the problem. 
[editor-javascript-practical.zip](https://github.com/gordonmzhu/questions/files/4804945/editor-javascript-practical.zip)

**Comment by gordonmzhu** [comment]
Can you post all of your code in a single HTML file like I do in the course? I prefer not to download a zip for security reasons.

**Comment by rmohan91** [comment]
Understandable, here is my code. runTheDebugger() is near the end. 
```
<!DOCTYPE html>
<html>
  <head>
    <title>Javascript Practical</title>
  </head>

  <body>
    <h1>My Ugly To-do List</h1>
    <div>
      <button onclick="handlers.toggleAll()">Toggle All</button>
    </div>
    <div>
      <button onclick = "handlers.addTodo()">Add</button>
      <input id="addTodoTextInput" type = "text">
    </div>
    <div>
      <button onclick = "handlers.changeTodo()">Change</button>
      <input id = "changeTodoPositionInput" type = "number">
      <input id = "changeTodoTextInput" type = "text">
    </div>
    <div>
      <button onclick = "handlers.toggleCompleted()">Toggle Completed</button>
      <input id = "toggleCompletedPositionInput" type = "number">
    </div>
    <ul></ul>
    <script>
      //This represents the data as an array and contains methods that change the array
      var toDoList = {
        todos: [],
        addTodo: function(newItem){
          this.todos.push({
            todoText: newItem,
            completed: false
          });
        },
        changeTodo: function(position, newtodoText){
          this.todos[position].todoText = newtodoText; //this.todos[position] is an object in the object array so we are selecting the property of that object
        },
        deleteTodo: function(position){
          this.todos.splice(position,1);
        },
        toggleCompleted: function(position){
          var todo = this.todos[position];
          todo.completed = !todo.completed; //It can be done in one line but then it isn't very legible...
        },
        toggleAll: function(){
          // My solution was incorrect. 
          // I used the debugger to understand the loop logic and I found that the if else statement made everything false if one thing was true 
          // (while it should only do this if all things were true).
          totalTodos = this.todos.length;
          completedTodos = 0;
          this.todos.forEach(function(todo){ //Todo refers to this.todo[i]
            if(todo.completed === true){
              completedTodos++;
            }
          });
          this.todos.forEach(function(todo){
            // Case 1: if everything is true make everything false
            if(totalTodos === completedTodos){
              todo.completed = false;
            //Case 2: Otherwise, make everything true
            }else{
              todo.completed = true;
            }
          });
        }
      };

      //When a user interacts, handle it. view.displayTodos has a better place here than in the todoList object since it is a direct response to a user interaction.
      var handlers = { 
        addTodo: function(){
          var addTodoTextInput = document.getElementById('addTodoTextInput'); //You can't use .value here since inputText is then changed not the dom objects address!
          toDoList.addTodo(addTodoTextInput.value);
          addTodoTextInput.value = '';
          view.displayTodos();
        },
        changeTodo: function(){
          var changeTodoPositionInput = document.getElementById('changeTodoPositionInput');
          var changeTodoTextInput = document.getElementById('changeTodoTextInput');
          toDoList.changeTodo(changeTodoPositionInput.valueAsNumber, changeTodoTextInput.value);
          changeTodoPositionInput.value = ''; //It is stored as a value (not a number) in the input field
          changeTodoTextInput.value = '';
          view.displayTodos();
        },
        deleteTodo: function(position){
          toDoList.deleteTodo(position);
          view.displayTodos();
        },
        toggleCompleted: function(){
          var toggleCompletedPositionInput = document.getElementById('toggleCompletedPositionInput');
          toDoList.toggleCompleted(toggleCompletedPositionInput.valueAsNumber);
          toggleCompletedPositionInput.value = '';
          view.displayTodos();
        },
        toggleAll: function(){
          toDoList.toggleAll();
          view.displayTodos();
        }
      };

      //Displays everything on the screen.
      var view = {
        displayTodos: function(){
          var todosUL = document.querySelector('ul');
          todosUL.innerHTML = '';

          toDoList.todos.forEach(function(todo, position){ //To get the index number i you can use the second argument.
            var todosLI = document.createElement('li');
            var todoTextWithCompletion = '' 

            if(todo.completed === true){
              todoTextWithCompletion = '(x) ' + todo.todoText;
            }else{
              todoTextWithCompletion = '( ) ' + todo.todoText;
            }
            todosLI.id = position;
            todosLI.textContent = todoTextWithCompletion;
            todosLI.appendChild(this.createDeleteButton()); //The callback function is not inside the view object!!
            todosUL.appendChild(todosLI);
          }, this)
        },
        createDeleteButton: function(){
          var deleteButton = document.createElement('button');
          deleteButton.textContent = 'Delete';
          deleteButton.className = 'deleteButton'; //Classes allow multiple dom elements to be grouped together
          return deleteButton;
        },
        setUpEventListeners: function (){ //Event delegation
          var todosUL = document.querySelector('ul');
          todosUL.addEventListener('click', function(event){
            //Get the element that was clicked
            var elementClicked = event.target;
            //Check if elementClicked is a delete button
            if(elementClicked.className === 'deleteButton'){
              handlers.deleteTodo(parseInt(elementClicked.parentNode.id))
            }
          })
        }
      }

      view.setUpEventListeners();

      function runTheDebugger(){ //Call functions are at the mercy of whichever higher order function they are passed into
        debugger;
        arguments[0](arguments[1], arguments[2]);
      }
    </script>
  </body>
</html>
```

**Comment by gordonmzhu** [comment]
When you execute `runTheDebugger(toDoList.addTodo, 'new item')`, what case applies inside of the `toDoList.addTodo`?

**Comment by rmohan91** [comment]
Inside the `toDoList.addTodo` method, case 2 applies so "this" refers to the toDoList object.

**Comment by rmohan91** [comment]
Yes I now see my interpretation was incorrect. To figure out which case applies I entered `console.log(this)` inside the addTodo method and I got the following output:

![image](https://user-images.githubusercontent.com/15945045/85399314-e7438c00-b556-11ea-9b57-b08f6bcbaa5c.png)

I'm not sure what case this applies to since it doesn't really point to any object (is it an array?). To keep it simpler and just test this case, I got rid of the arguments[0] and arguments[1] parameters so my new function looks as follows:
```
function runTheDebugger(callback, parameter){
  debugger;
  callback(parameter);
}
```
In this case `console.log(this)` points to the window object which seems similar to case 1.

**Comment by gordonmzhu** [comment]
Let's return back to my question since you didn't answer it yet. It's important to understand my question because if you don't, it means you don't understand how `this` works.

Again, when you execute runTheDebugger(toDoList.addTodo, 'new item'), what case (from the this cheatsheet) applies inside of the toDoList.addTodo method?

**Comment by rmohan91** [comment]
> Again, when you execute `runTheDebugger(toDoList.addTodo, 'new item')` (using the code you had in your original question), what case (from the this cheatsheet) applies inside of the toDoList.addTodo method?

Is it the second case? Since `this` is pointing to Arguments which is an array-like object.

![image](https://user-images.githubusercontent.com/15945045/85623987-835db800-b669-11ea-87e2-7a8d1201314c.png)

**Comment by gordonmzhu** [comment]
The rule for case 2 is very straightforward. It's case 2 if the function is called as a method. In this example, where is the function called? Is it being called as a method or not?

**Comment by rmohan91** [comment]
> The rule for case 2 is very straightforward. It's case 2 if the function is called as a method. In this example, where is the function called? Is it being called as a method or not? Your screenshot shows the debugger in the body of the function; it does not show where/how the function is being called.

The function is being called inside the higher order function runTheDebugger so its not being called as a method. 
This is obviously case 5 but as I mentioned in my first question, looking at the various cases in this video, I really do not understand which case (inside of case 5) my example applies to. 

As a sidenote, while trying to figure out a solution, I managed to find an alternative implementation where I created a method called `returnthis` inside `toDoList`, `handler` and `view` that explicity return the object in question: 'returnthis: function(){return this;}'
Then I created three higher order functions for each object using `call()`. So for toDoList it would look as follows: 
```
function runTheDebuggerToDoList(){ //Call functions are at the mercy of whichever higher order function they are passed into
  debugger;
  arguments[0].call(toDoList.returnthis(), arguments[1], arguments[2]);
}
```
Now when I execute `runTheDebuggerToDoList(toDoList.addTodo, 'new item')` or any other method inside `toDoList` it works but obviously if I add new objects, this solution doesn't really scale. Is there a more general way to do this? Hope i'm not bothering you too much but I really want to understand how `this` works for my case.

**Comment by gordonmzhu** [comment]
You said "The function is being called inside the higher order function runTheDebugger so its not being called as a method." 

Are you sure about that? Can you point to where it's being called?

**Comment by rmohan91** [comment]
Oh sorry, I misunderstood the question. toDoList.addTodo('new item') is being called as a method in the third line of this code:
```
function runTheDebugger(){
  debugger;
  arguments[0](arguments[1], arguments[2]);
}
```
To be sure I used console.trace() inside the addTodoList method which pointed to this same line. 

![image](https://user-images.githubusercontent.com/15945045/86103470-1b6dfe00-babd-11ea-8fff-7fa873ae4f9a.png)
