### ISSUE TITLE
Not a problem but a clarification

### ISSUE THREAD

**Issue by PatrickColleton** [gordonmzhu/questions#457]
In Version 7 of the Watchandcode app, you add an event listener as follows: 
displayTodosButton.addEventListener('click', function() {
        todoList.displayTodos();
      });

Do you have to add the anonymous function syntax "function() {}"? Could you instead just add the displayTodos() function as an argument directly like this:

displayTodosButton.addEventListener('click', todoList.displayTodos() );

### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You should try it and see what happens.

And you should do that generally. Whenever you have the thought, "could I do x instead?". Just run an experiment and see if it works.
