### ISSUE TITLE
Video isn't playing properly, I am trying to play the videos for 2 days. But it isn't playing after "Version 1 - Array". Before this section everything was okay. My user ID: mukul.cse2010@gmail.com

### ISSUE THREAD

**Issue by mukulsustcse** [gordonmzhu/questions#460]
<img width="1280" alt="Screenshot 2020-07-03 at 6 48 52 PM" src="https://user-images.githubusercontent.com/66126532/86470816-0237ac80-bd5e-11ea-9699-75d8030758cd.png">
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Are you still having this problem? I'm not able to recreate the problem. The videos are working fine for me.

**Comment by mukulsustcse** [comment]
Yeah,
it is working now, thanks :)
