### ISSUE TITLE
Should I be coding along with you?

### ISSUE THREAD

**Issue by nielua** [gordonmzhu/questions#461]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

Hello, I'm a beginner and in the process of doing your practical javascript course. I was wondering if I am to be doing the "coding" as you're doing it? So far I'm a little confused and I've tried the "todos" in the inspect and I've had *errors in red text show up. I've followed your videos line by line to make sure it's not human error. I'm not sure what the issue is but I just want to make sure I'm doing what's necessary. Looking forward to hearing from you. Thank you!

**Comment by gordonmzhu** [comment]
You should code along as replicate everything that happens in the videos. Coding is not a passive exercise.
