### ISSUE TITLE
https://watchandcode.com/courses/60264/lectures/928388

### ISSUE THREAD

**Issue by ObiWanBenobi** [gordonmzhu/questions#463]
### What is the associated Watch and Code lesson? 

'It should have a function to change a todo' at 2:46

### Include a link to your code so I can run it on my computer. 

https://watchandcode.com/courses/60264/lectures/928388

### Explain the exact steps I need to take to replicate the problem. 

I'm following along in console on a new tab. When I hit enter to show what I have done, it just shows as undefined.

### What did you expect to happen? 
I expected it to show me my new change todo function.

### What actually happened? 

it just showed as undefined

### Describe what you've done so far to troubleshoot the problem. 

I reviewed all spelling and punctuation. I am human, but I thought I reviewed it well. Done this several times.
![Annotation 2020-07-14 080452](https://user-images.githubusercontent.com/60205012/87428985-c34cf680-c5a8-11ea-9870-708634d49af3.png)

**Comment by gordonmzhu** [comment]
Closing (answered in morning meeting).
