### ISSUE TITLE
I'd like to ask why the this keyword wasn't necessary to access an object. (this.todoList.todos[i].todoText)

### ISSUE THREAD

**Issue by eddiemae** [gordonmzhu/questions#464]
### What is the associated Watch and Code lesson? 

Write your response here (required).
In the lesson https://watchandcode.com/courses/60264/lectures/1056226,  timestamp 1:01.  I'd like to ask why you didn't use the this keyword for accessing the todoList.todos[i].todoText.

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Why don't you try using `this` and see if your approach works.
