### ISSUE TITLE
Version 6: toggle all

### ISSUE THREAD

**Issue by Roman4u** [gordonmzhu/questions#465]
Hi Gordon, 
I have a question regarding the following code; specifically the equal signs (i.e. one takes 3 and the other takes 1). Why does 
                                     - this.todos[i].completed === true 
take 3 equal signs, yet 
                                    - this.todos[i].completed = false 
only takes 1 equal sign? I tried using 3 equal signs in the latter, but the toggleAll method would not work as intended, so I'm curious as to why I cannot use 3 equal signs here. What's the difference between them? Below is the entire code for reference.

          for (var i = 0; i < totalTodos; i++) {
              if (this.todos[i].completed === true) {
                completedTodos++;
              }
            }
            
            if (completedTodos === totalTodos) {
              for (var i = 0; i < totalTodos; i++) {
                this.todos[i].completed = false;
              }
            }
thanks, 
Roman

**Comment by gordonmzhu** [comment]
You should go back and review earlier lessons where I explain this in detail.
