### ISSUE TITLE
Using handlers vs direct method access in the todoList object

### ISSUE THREAD

**Issue by ttorrisi** [gordonmzhu/questions#466]
### What is the associated Watch and Code lesson? 

8.1 (Our first refactoring)

### Include a link to your code so I can run it on my computer. 

var handlers = {
      displayTodos: function() {
        todoList.displayTodos();
      },
      toggleAll: function() {
        todoList.toggleAll();
      }
    };

### Explain the exact steps I need to take to replicate the problem. 

There is no problem, I am just looking for a clarification regarding event handlers vs direct access to the methods within the todoList object.

Is the reason that we are using event handlers just so that we are abiding by the OOP principal of encapsulation? Javascript appears to allow direct access to the todoList.displayTodos() (and other) methods through the onclick event on each button.

**Comment by gordonmzhu** [comment]
see https://github.com/gordonmzhu/questions/issues/97
