### ISSUE TITLE
Question on Version 8 - Our First Refactoring Lesson

### ISSUE THREAD

**Issue by chrisarrow90** [gordonmzhu/questions#467]
### What is the associated Watch and Code lesson? Version 8 - 'Our First Refactoring' lesson
Write your response here (required).

Hi Gordon.
Quick question regarding this lesson. Maybe you explain this in a later video but why did you create a new handlers object to access the functions that are already defined in the todoList object. Why couldn't we just refer directly to the todoList.displayTodos() in the HTML <button> element instead?
It seems to go against the DRY principle.

Also, many thanks for making this intro course free for us to learn JavaScript. It is very helpful.

Thanks,

Chris

**Comment by gordonmzhu** [comment]
see https://github.com/gordonmzhu/questions/issues/97
