### ISSUE TITLE
Uncaught TypeError: Cannot read property 'valueAsNumber' of null

### ISSUE THREAD

**Issue by MasonwabeJoka** [gordonmzhu/questions#469]
### What is the associated Watch and Code lesson? 

Version 8 - Getting data from inputs: There should be a button for changing todos. 
https://watchandcode.com/courses/60264/lectures/1027557

### Include a link to your code so I can run it on my computer. 

https://gist.github.com/MasonwabeJoka/331955ac70c2ec07f8a87b833249c789

### Explain the exact steps I need to take to replicate the problem. 

You will replicate the problem if you fill in the three input fields on the browser and press their corresponding buttons in this order: 1. Add Todo text input.  2. Press "Add" button.  3. Enter the number 0 on the number input field.  4. Enter text on the text field for "Change Todo".

### What did you expect to happen? 

I expected to change the text of my todos when I enter the number 0 and input alternative text.

### What actually happened? 

This is the error message I got: 

toList.html:111 Uncaught TypeError: Cannot read property 'valueAsNumber' of null
    at Object.changeTodo (toList.html:111)
    at HTMLButtonElement.onclick (toList.html:21)
changeTodo @ toList.html:111
onclick @ toList.html:21

### Describe what you've done so far to troubleshoot the problem. 

I tried to run the debug but I just end up with the error message and I can't seem to find what causes the error. I've also tried to google the problem and so far the answers  were not that helpful. Some people say the element I am referencing with the Id doesn't exist. Some say my DOM loads after the code that is trying to run, while it is referencing it. I can't seem to find a solution to any of the possible causes that are suggested. 

Please help this South African guy and thanks for a great course.

**Comment by gordonmzhu** [comment]
Closing as I saw that you caught your typo https://gist.github.com/MasonwabeJoka/331955ac70c2ec07f8a87b833249c789#gistcomment-3406607

**Comment by MasonwabeJoka** [comment]
> Closing as I saw that you caught your typo https://gist.github.com/MasonwabeJoka/331955ac70c2ec07f8a87b833249c789#gistcomment-3406607

Thanks.
