### ISSUE TITLE
Version 6- toggleAll function doesn't work (no error message)

### ISSUE THREAD

**Issue by manieshablakey** [gordonmzhu/questions#47]
### What is the associated Watch and Code lesson? 
Hi Gordon: I'm having trouble with Version 6 (toggle All function). I've defined totalTodos and completed Todos (those seem fine). The trouble seems to be with my if/else statement which doesn't make the Toggle All function work. I've checked the code multiple times & believe the curly brackets are all in place, etc. and can't seem to figure out why the toggleAll function is not working for me. All other code I've written runs fine. I'm attaching both link & code below for some advice please. There is no error message I get when I run the toggleAll function- it just doesn't seem to toggle all the items I've added to the list. Thanks!
https://plnkr.co/edit/ckq5XE9KovQCkUYHyTv5?p=preview
 toggleAll: function() {
  var totalTodos = this.todos.length;
  var completedTodos = 0;
  for (var i = 0; i < totalTodos; i++) {
    if (this.todos[i].completed === true) {
      completedTodos++;
    }
  }
  // Case 1: If everything's true, make everything false.
  if (completedTodos === totalTodos) {
    for (var i = 0; i < totalTodos; i++) {
      this.todos[i].completed === false;
        } 
  // Case 2: If everything's false, make everything true.
      } else {
    for (var i = 0; i < totalTodos; i++) {
      this.todos[i].completed === true;
        }
      }
      this.displayTodos();
    }
  };

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by hydroweaver** [comment]
Hi @manieshablakey, you haven't written the entire toggleAll function correctly. There are two conditions, and your function has one, try checking the lesson once again. 
Right now it doesn't work because, your function is only checking if they are not toggled currently.

**Comment by manieshablakey** [comment]
Hi @hydroweaver, thanks for your reply. I've gone over all the 4 sections in Version 6 and still confused. My thinking is as follows:
- I've defined total no of todos using the first variable
- I've defined the complete todos and set it to '0' initially.
- I've created a for variable that states if a todo list item has been completed, it increases the no of completed todos by 1.
- this is followed by the if/else statement to make everything false if everything's true and then to make everything true if everything's false.
Confused by what condition I'm missing... Any further advice would be much appreciated. Thanks.



 toggleAll: function() {
  var totalTodos = this.todos.length;
  var completedTodos = 0;
  for (var i = 0; i < totalTodos; i++) {
    if (this.todos[i].completed === true) {
      completedTodos++;
    }
  }
  // Case 1: If everything's true, make everything false.
  if (completedTodos === totalTodos) {
    for (var i = 0; i < totalTodos; i++) {
      this.todos[i].completed === false;
        } 
  // Case 2: If everything's false, make everything true.
      } else {
    for (var i = 0; i < totalTodos; i++) {
      this.todos[i].completed === true;
        }
      }
      this.displayTodos();
    }
  };

**Comment by hydroweaver** [comment]
Hi @manieshablakey , You've confused assignment with comparison, see lines 53 and 58.

=== is used for comparison, while = is used for assignation, in these lines you need to assign the values to the complete flag of the todo under question.

**Comment by manieshablakey** [comment]
Hi @hydroweaver- Many thanks! I've modified and tested my code and it all works now. I'll have another look at the differences between assignment & comparison operators so this doesn't happen again. Thanks for your time and assistance.
