### ISSUE TITLE
whats happening, I follow lwsson step by step and got error

### ISSUE THREAD

**Issue by haclion** [gordonmzhu/questions#470]
Hi Goredon
As always is frustrating trying to follow lessons step by step and met errors so I try again and same sht happens is there trouble with the browser, why things dont show exactly as you do?
lesson Function change todos.

function changeTodo(position, newValue) {
    todos(position) = newValue;
}
displayTodos()
VM103:2 My todos:  (6) ["item 1, item 2, item 3", "new todo", "new todo", undefined, undefined, "some stuff"]
undefined
changeTodo(0, 'changed')
VM1139:2 Uncaught TypeError: todos is not a function
    at changeTodo (<anonymous>:2:5)
    at <anonymous>:1:1

**Comment by gordonmzhu** [comment]
I'd need more information to understand the issue. If you fill out all the fields in the Github issues form, I'd be glad to help.

For example, here's a well-formed question from another student that: https://github.com/gordonmzhu/questions/issues/469. All questions should be of this form.
