### ISSUE TITLE
Not sure why you used a for loop here 

### ISSUE THREAD

**Issue by SianaT** [gordonmzhu/questions#471]
### What is the associated Watch and Code lesson? 

lesson url: https://watchandcode.com/courses/60264/lectures/936343 
timestamp: 3:27

### Include a link to your code so I can run it on my computer. 

I don't have an issue with my code. I have a question about your code and why you used a for loop here:

//If everything's true, make everything false.
   if (completedTodos === totalTodos) {
   for (var i = 0; i < totalTodos; i++) {
      this.todos[i].completed = false;   
      }
  }

**I'd like to know why you had to use a for loop to make everything false instead of simply writing this in the if statement:
 this.todos.length.completed === false;**

I've tried to use my suggestion and it doesn't work but if you could tell me _why_ it doesn't work, I'd be extremely grateful.

### Explain the exact steps I need to take to replicate the problem. 

N/A

### What did you expect to happen? 

N/A

### What actually happened? 

N/A

### Describe what you've done so far to troubleshoot the problem. 

N/A

**Comment by gordonmzhu** [comment]
@SianaT 

1) To answer this question, you first need to be very clear about what my code does. 

2) Next, you need to carefully consider what your code does.

The answer lies in the difference between the two approaches. Can you take a shot at describing 1 and 2?

**Comment by SianaT** [comment]
Ok yeahhhh thanks. It made sense when I explained it to myself out loud. Got it. Thanks again. 👌🏽
