### ISSUE TITLE
Trouble encounters

### ISSUE THREAD

**Issue by haclion** [gordonmzhu/questions#472]
Hi Gordon, let me tell you, your turorials are great, the aproach you take is the right for many of us that want to learn to code but miss the practice and machine logic to understand what you are doing, thank Gos I find you, now I start to understand much better the concepts that other tutoials missed, thanks for the time and efort to develop this type of teaching, I look forward to advance my learnig process but have encounter some troubles to learn quicker, hope you can help me. By the way, do you have time to help me to develop aproyect that Im syuck in the middle? If so you can write me to my inbox in deddumo@gmail.com thanks regards, ED

### What is the associated Watch and Code lesson? 

The first troubles I encounter in using the Dom console to write and try code to follow your lessons,
In Version 2 in " it shoul have a function to change todos", I encounter an "Uncaught TypeError todos is not a function" 
function changeTodo(position, newValue) {
    todos(position) = newValue;
}
displayTodos()
VM103:2 My todos:  (6) ["item 1, item 2, item 3", "new todo", "new todo", undefined, undefined, "some stuff"]
undefined
changeTodo(0, 'changed')
VM1139:2 Uncaught TypeError: todos is not a function
    at changeTodo (<anonymous>:2:5)
    at <anonymous>:1:1
=============================================
I couldn't identify the error so I move forward and in lesson " it shoul have a function to delete todos" other error here it didnt delete anything; since more errors came when moving forward, I see that instead of vscode, you use plunker, I try it but the plunker I download is not same as yours, doesn't have run  and other buttons, so I try to follow with vscode, cause you mentioned it, shortly , but keep using plunker. here  I try follow in lesson Version 3     " Objects and Functions " and again error console is not defined ( console¿?¿? of console.log?¿??) I move forward and now Im in: "It should store the todos array on an object" :
here is is the code with vs code and again encounter new error, this make the learning process a bit nightmare, hope you understand whats happening because I dont. Is getting harder to avance and learn. I prepare a paint file where you can check what I was doing and what lesson you were showing, cause I dont know how to do the URL's, links, or use of debugger,  you asked so you can try in your computer, hope this might help, thanks for your time and help.
### Include a link to your code so I can run it on my computer. 

I dont know how to do this

### Explain the exact steps I need to take to replicate the problem. 

I better show it in the paint file I send.

### What did you expect to happen? 

I expect to happen what it should but the Dom is driving me crazy ;)

### What actually happened? 

you can see it perfectly in the paint file

### Describe what you've done so far to troubleshoot the problem. 

I try several times but keep the same hapenings. Same with my codes, I have one that works fine and the other bring out Uncaught TypeErrors and they are exactly written.

![Captura de pantalla (1880)](https://user-images.githubusercontent.com/40932211/89952115-ed87e780-dc2c-11ea-93b0-96ac21d130d9.png)
![errorProblems2](https://user-images.githubusercontent.com/40932211/89952156-01cbe480-dc2d-11ea-8def-653c4b3e0568.png)

https://drive.google.com/file/d/1_xouz-Lk38vCFaE6K9-7zwiBPfdNlDCN/view?usp=sharing

**Comment by gordonmzhu** [comment]
### Include a link to your code so I can run it on my computer. 

The form tells you exactly how to do this. Direct quote: "For Practical JavaScript, just paste the contents of your todoList.html to gist.github.com and share the link."

**Comment by gordonmzhu** [comment]
I can't read your screenshots. Please open a new issue and include a link to your code as described in the issue template and reiterated in my previous comment.
