### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by yoanongly** [gordonmzhu/questions#475]
### What is the associated Watch and Code lesson? 

Hello, thank you for helping out. I'm a zero level beginner and I appreciate you taking your time. 
https://watchandcode.com/courses/60264/lectures/946810 . timestamp: 1:34 and 1:44
Why did we use todos[position].todoText instead of addTodos[position] since todoText is a property of addTodos (I did try this and still resulted in error though)

### Include a link to your code so I can run it on my computer. 

      var todoList =
      {
        todos:[],
        displayTodo: function() {
          console.log(this.todos);
        },
        addTodo: function(todoText) {
          this.todos.push({
            todoText: todoText,
            completed: false
          });
          this.displayTodo();
        },
        changeTodo: function(position, todoText) {
          this.todos[position].todoText = todoText;
          this.displayTodo();
        }

### Explain the exact steps I need to take to replicate the problem. 

The words I typed in console are:
todoList.changeTodo(0, 'n');

### What did you expect to happen? 

I expected to have the same result as in your tutorial

### What actually happened? 

newtodos.html:19 Uncaught TypeError: Cannot set property 'todoText' of undefined
    at Object.changeTodo (newtodos.html:19)
    at <anonymous>:1:10

### Describe what you've done so far to troubleshoot the problem. 

I have proofread for typos and they are exactly the same as your code but did not have the same result. 
I tried to delete the problematic part which is todoText. I ran: 

        changeTodo: function(position, todoText) {
          this.todos[position] = todoText;
          this.displayTodo();
        }

and it worked out fine. It printed 'n' as a text but did not come out as an object. I am stuck at this part and I would appreciate your help. Thank you for your time.

![Screenshot (219)](https://user-images.githubusercontent.com/70634635/91967100-530b5780-ed45-11ea-9e07-080ffac61ca2.png)

**Comment by gordonmzhu** [comment]
You said "since todoText is a property of addTodos". What do you mean by that?

**Comment by yoanongly** [comment]
I understood now that although these properties are placed inside addTodo function, these objects would also be part of todos array. And I had been able to make the code work by adding a space in between the property and the : . Thank you so much for your time to answer me.

**Comment by gordonmzhu** [comment]
👍
