### ISSUE TITLE
Question about object

### ISSUE THREAD

**Issue by Sayed94h** [gordonmzhu/questions#477]
## My Question:
When you get access to an object property using dot, how does it work?
example:
```js

let obj = {
  Name: "Sayed",
  LastName: "Kazimi"
 }
// I want to access to 'Name' inside the object
obj.Name; // Sayed . I want to know how this works

```
You said in your [video](https://watchandcode.com/courses/60264/lectures/3954982) that object stores the memory address and when you want to access to the properties then you travel to properties. How does this travel work?.
obj = address; obj.Name = ----> travel ---> `Name: "Sayed"` 

I mean how does computer do that?

**Comment by gordonmzhu** [comment]
The details of how this works are a bit too complicated to get into now and I think would be a distraction. But if you browse https://en.wikipedia.org/wiki/Hash_table you can get a rough idea.
