### ISSUE TITLE
Version 3 Suddenly Using Plunker?

### ISSUE THREAD

**Issue by LovelyAndy** [gordonmzhu/questions#479]
### What is the associated Watch and Code lesson?  Version 3 - It should have a displayTodos method

This version suddenly starts using Plunker. I've looked up what Plunker is and that's all well and fine, but when did we and why did we start using that application? I'm a bit lost here. Did I miss something in a previous lesson (I've referenced old sections, but haven't found where we begin using it. )?

I have no problem using the Plunker app, but it's a bit jarring to be now using a third thing to write out code. This section perhaps use a quick update introducing the application if it is indeed missing.

Loving the course so far though! 

Thank you!

**Comment by gordonmzhu** [comment]
Carefully rewatch "Interlude - editor setup"
