### ISSUE TITLE
JQuery removal from bindEvents()

### ISSUE THREAD

**Issue by PabloVent** [gordonmzhu/questions#48]
### What is the associated Watch and Code lesson? 

6. Digestion techniques. section 4. Remove jQuery.

### Include a live demo link so that I can run your code. 

https://glitch.com/edit/#!/chip-beast?path=public/js/app.js:65:53

### Explain the exact steps I need to take to replicate the problem. 

To replicate the problem: 
-run the app
-enter 3 or 4 values 
-toggle 1 or 2 values (any one in no particular order).
-click on filter `'completed'`, `'active'` or `'all'`

[-](url)

### What did you expect to happen? 

I expected for the filters to do their job, showing only completed, active or all the todos depending on the filter you clicked on.
I was expecting this behavior based on the fact that the above bound events (`create()` and `toggleAll()`) are behaving as expected.  Their source code is almost identical to that of `destroyCompleted`'s, as shown in the screenshot.

![image](https://user-images.githubusercontent.com/17232181/44935066-30fe2980-ad67-11e8-9d75-726c3ccce2eb.png)

### What actually happened? 

The toggled todo(s) get(s) expunged when you click on any of the filters.  This error happens in both Chrome and Safari.
If you keep on clicking, you keep getting the same error.
Error:
<img width="1376" alt="error" src="https://user-images.githubusercontent.com/17232181/44934521-0ad78a00-ad65-11e8-8540-b9aa3b47cea9.png">
Problem code line.
![image](https://user-images.githubusercontent.com/17232181/44935362-4b84d280-ad68-11e8-8d0d-3493838c1c3c.png)

### Describe what you've done so far to troubleshoot the problem. 

I've tried to modify the line from:
1)
```var footer = document.getElementById("footer");```
 ```footer.addEventListener('click', this.destroyCompleted.bind(this));```

to:
2)
```var footer = document.getElementById("footer");```
```var footer = document.getElementById("clear-completed");```
 ```footer.addEventListener('click', this.destroyCompleted.bind(this));```
 ```footer.addEventListener('click', this.destroyCompleted.bind(this));```

to:
3)
```var footer = document.getElementById("footer", "clear-completed");```
 ```footer.addEventListener('click', this.destroyCompleted.bind(this));```
 
to:
4)
```var footer = document.getElementById("footer");```
```var input = footer.document.getElementById("clear-completed");```
 ```input.addEventListener('click', this.destroyCompleted.bind(this));```

to: 5)

```var footer = document.getElementById("footer");```
```var input = footer.querySelector("clear-completed");```
 ```input.addEventListener('click', this.destroyCompleted.bind(this));```

Number 1) yields the best output, namely, the following:

<img width="1376" alt="error" src="https://user-images.githubusercontent.com/17232181/44934521-0ad78a00-ad65-11e8-8540-b9aa3b47cea9.png">
No clear completed button in the footer.

Number 2) yields:

![image](https://user-images.githubusercontent.com/17232181/44936103-4d9c6080-ad6b-11e8-8703-e8d63a1fca42.png)
This errors appears as soon as the code autosaves in glitch.  If you refresh the website you get the same error with no todos on display in the UI. If you type a new todo in, then all the others reappear.

Number 3) yields:

![image](https://user-images.githubusercontent.com/17232181/44936319-14182500-ad6c-11e8-99cb-beede29f064f.png)
No clear completed button in the footer and error is the same as in case 1).

Number 4) yields:

![image](https://user-images.githubusercontent.com/17232181/44936510-eed7e680-ad6c-11e8-8940-bcf885efba40.png)
As incase 2), as soon as glitch autosaves, this error shows up with no todos on display in the UI.  If you type a new one in, then all the others reappear.

Finally, number 5) yields:

![image](https://user-images.githubusercontent.com/17232181/44936748-dcaa7800-ad6d-11e8-8d86-133f3b2d00ac.png)
With no todos on display in the UI when glitch autosaves the new code.

I need help **_understanding_** what I'm missing if  I am to fix lines 66 and 67 so `bindEvent()` does its thing and doesn't interfere with `getCompletedTodos()`, `getActiveTodos()` or `getFilteredTodos()` along the way.
I've read in the docs at: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById about `getElementById()` to try and figure out if it can take 2 arguments, which it can't by the looks of it.
I've also tried to insert `"clear-complete"` inside of `input.addEventListener('click', "clear-complete", this.destroyCompleted.bind(this));` but to  no avail.
Any pointers/online resources will be greatly appreciated.

**Comment by gordonmzhu** [comment]
1) Add a todo.
2) Mark it as complete.
3) Hit "All". What function runs after this step?

**Comment by PabloVent** [comment]
Good morning Gordon. Bear with me. It's another day in England.

**Comment by PabloVent** [comment]
Clearly, by saying:

```var footer = document.getElementById("footer");```     
```footer.addEventListener('click', this.destroyCompleted.bind(this));```

I'm giving the power to delete a `todo` to all the filters within `<#footer>`.  
I need to somehow filter out `<ul #filters>:` `active`, `completed` and `all`, (functions `getActiveTodos()`,`getCompletedTodos()`, `getFilteredTodos()`respectively), and single out button `<#clear-completed>` as the only element with deleting 'privileges'  within `<#footer>` if you will.

**Comment by PabloVent** [comment]
-I now understand well how the JQuery version works segment by segment.  It's the translating I'm finding a bit involved.
-PJS version 10, penultimate video was very useful in helping me filter out `All`, `complete` and `active`.  However, the improved version I came up with blocked out `clear completed`'s functionality completely.

For this version:

<img width="959" alt="nofixjs" src="https://user-images.githubusercontent.com/17232181/44997987-005a0200-afaa-11e8-8c0a-ec81b0abcac4.png">


I still get error messages stemming, this time, from clicking on `clear completed`.
<img width="1412" alt="nofix" src="https://user-images.githubusercontent.com/17232181/44997835-11564380-afa9-11e8-85e4-cf1e8ae94164.png">

So I tried swapping the first `this` (line 71) for `App` and then removed the `.bind(this)` part and it did the trick.   

<img width="478" alt="fixjs" src="https://user-images.githubusercontent.com/17232181/44997633-b708b300-afa7-11e8-9d69-768a9d1b5e57.png">

It was a fluke to be honest though; I need to reason out why it worked, since the other bound functions from lines 61 to 64 work just fine with `.bind(this)`. 

I guess it has to do with the fact that line 71 lies inside a callback and, therefore, it needs an "open door" to communicate with `App`.  I tried sticking a `,this` in line 74, just before the `;` but it didn't seem to work.
That's the state of affairs thus far.  I'll keep on keeping on....

**Comment by gordonmzhu** [comment]
Yes you've solved one issue but now have a different one, which is understanding `this`. I recommend using the cheatsheet and debugger to figure out what case applies in this situation.

**Comment by PabloVent** [comment]
Thanks Gordon.  Will do.

**Comment by PabloVent** [comment]
Problem fixed with the help of fellow students @godescalc Jonathan and Adil @Adil.
The code now looks like this:
```var footer = document.getElementById("footer");// footer is the ul   
      footer.addEventListener('click', function(event) {//this.destroyCompleted(elementClicked.parentNode).bind(this);     
      var elementClicked = event.target;
        if(elementClicked.id === "clear-completed"){
             this.destroyCompleted();
           }
    }.bind(this));```

**Comment by gordonmzhu** [comment]
Nice! Thanks for helping out Jonathan and Adil.
