### ISSUE TITLE
Further Learning

### ISSUE THREAD

**Issue by maxi-amodei** [gordonmzhu/questions#480]
Hi Gordon, I just finished the introductory course and it was great, so I'm thinking to continue with the course.
One question that I have is about complementary learning materials.
I started studying eith Head First series by O'Reilly, and I continued with your course.
I was wondering If you could recommend some more advanced learning material, as I find helpful reading at the same time as watching tutorials? Is there any good books with intermediate/advanced Javascript?

**Comment by gordonmzhu** [comment]
No
