### ISSUE TITLE
The call stack: Quiz 2 

### ISSUE THREAD

**Issue by LennartSakowsky** [gordonmzhu/questions#481]
### What is the associated Watch and Code lesson? 

Hi Gordon, I don't know if you read my question in Slack yesterday, in short I wanted to know if my answers for Quiz 2 are correct now – I failed because I thought statements 1–8 are supposed to be incorrect due to the missing call of function1() in the provided screenshot which is needed to start it all. Arielle was „95% sure“ they are correct – for the missing 5% I wanted to ask you to really know where I stand. 

https://watchandcode.com/courses/premium/lectures/24190546

### Include a link to your code so I can run it on my computer. 

I put my screenshot here (deleted it from Slack) – at statement 2 it should say „2 is incorrect“.
<img width="1211" alt="Bildschirmfoto 2020-09-15 um 20 36 05" src="https://user-images.githubusercontent.com/68876538/93388492-196d3d00-f86b-11ea-9113-5b6ec1d8a1d5.png">

To get to these answers I put „function1();“ at the end in line 17 or 18 actually because I wrote „debugger;“ in line 1. I ran it through the debugger twice to be sure I got everything right and double-checked my answers in the screenshot above each time.

This being a quiz, not a code problem, I think the rest of the template here is not important. 

I would really appreciate your help. 

Have a nice evening!
Lennart

**Comment by gordonmzhu** [comment]
Hey Lennart. Arielle was correct in the thread. The answer choices assume that you will be paused at a specific line so you have to call the functions.

**Comment by LennartSakowsky** [comment]
Thanks Gordon!
