### ISSUE TITLE
toggleAll() Method

### ISSUE THREAD

**Issue by greenpepper38** [gordonmzhu/questions#483]
Hey Gordon,

I am getting an error message when trying to use the toggleAll() method to switch all todos to false when all todos are true.

Video link: https://watchandcode.com/courses/60264/lectures/936343 
5min 42seconds (unsure how to provide timestamp)

Photos attached - code is identical to yours. tried to debug but after sometime still unclear what the issue could be. Any tips? 
 
<img width="473" alt="Screen Shot 2020-09-24 at 10 08 56 am" src="https://user-images.githubusercontent.com/69625434/94086477-70b47400-fe4e-11ea-9189-41aec63056a9.png">
<img width="409" alt="Screen Shot 2020-09-24 at 10 09 42 am" src="https://user-images.githubusercontent.com/69625434/94086483-727e3780-fe4e-11ea-8490-4a73ef50affb.png">

**Comment by gordonmzhu** [comment]
If you'd like a response, you must carefully fill out all the fields in the issue template. For example, you failed to provide your code as requested. Relevant portion from prompt below. If you resubmit and thoughtfully fill out the form I'll take a look then.

"Include a link to your code so I can run it on my computer. For Practical JavaScript, just paste the contents of your todoList.html to gist.github.com and share the link."
