### ISSUE TITLE
Question about the course

### ISSUE THREAD

**Issue by iklaitz** [gordonmzhu/questions#484]
Hi there, I wanna do the course, I've taken a preovious JS course but some things didn't "click".. I found your course and also the premium content, My main concerns are:

1.- Is the whole course ES5? Is there any new ES6 course from you elsewhere?
2.- It seems your Zoom hours are not being done anymore, because I've seen your youtube channel and the last one is from 2019
3.- How many active users the slack community is on September 2020? Are there many active users daily?

Thank you

**Comment by gordonmzhu** [comment]
See the language considerations section: https://watchandcode.com/courses/350615/lectures/17413273

There are no longer Zoom meetings for free users. Paid users have access to daily calls.
