### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iklaitz** [gordonmzhu/questions#485]
Hello, two days ago you told me that the zoom meeting calls were for pro users, and I know that, I wanna buy the premium subscription, but the question I had was if the course was updated to the current versions of JS, also, you gave me an URL to a chapter on your free course but It's blocked, Tried to do mark as read te previous chapter so I could watch that video first to see what you meant.. but I got blocked because of a wrong quiz question... 

I wanna buy your course, I just want some answers first to know what I'm buying. Thanks.

**Comment by gordonmzhu** [comment]
"but the question I had was if the course was updated to the current versions of JS, also, you gave me an URL to a chapter on your free course but It's blocked,"

You can register for that course to see those lessons. Those lessons answer your question about different versions of JavaScript.

To get unblocked, you'll need to follow the directions here: https://watchandcode.com/courses/350615/lectures/22857829.
