### ISSUE TITLE
Running JS in VS Code

### ISSUE THREAD

**Issue by TylerWilson-student** [gordonmzhu/questions#486]
Greetings! 
I wanted to reach out to you for some assistance on VS Code. I am following practical JS and I am in the object portion in version 3. I am understanding the material but I am running into an issue where I am not able to compile in VS Code. I have nothing but a semester of Python under my belt and searching the web has not found me any easier answers. I know this is probably a silly question and I must be doing something wrong. Any help would be appreciated. Cheers
![JS snip](https://user-images.githubusercontent.com/72350813/95020448-2fd01280-0639-11eb-8b77-01ea044ab127.PNG)

**Comment by gordonmzhu** [comment]
I explain this step-by-step in "Interlude - editor setup"

**Comment by TylerWilson-student** [comment]
I figured out what I was doing wrong! I was not saving my file before refreshing chrome. Thank you again. Looking for to subscribing.
