### ISSUE TITLE
When I run the displayTodosButton element in the console I get a "null" feedback instead of getting access to the displayTodos button

### ISSUE THREAD

**Issue by moloak** [gordonmzhu/questions#488]
### What is the associated Watch and Code lesson? 

URL: https://watchandcode.com/courses/60264/lectures/987943
Timestamp: 3:14 - 4:53

### Include a link to your code so I can run it on my computer. 

codelink :https://plnkr.co/edit/r9a9eYDFmceeobbL?preview

### Explain the exact steps I need to take to replicate the problem. 

1. Create button tags for your toggleAllButton and displayTodosButton in your HTML file.

2. Give each an ID

3. Create a variable to reference the ID, console the displayTodosButton variable that now holds the HTML element (Link the variable with the HTML button tag with the ID):
var displayTodosButton = document.getElementById('displayTodosButton');
console.log(displayTodosButton);

4. addEventListeners to the respective variables :
displayTodosButton.addEventListener('click', function() {
  todoList.displayTodos();
})

5.Getting the displayTodosButton to console as in the code should return the HTML element but it did return 'null' as seen in the screenshot.

6.Click the 'Display Todos' button and the 'Toggle all' button in the plunker preview pane should run respective function contained therein. but I got no response in the console.

7. I tried the refactoring method but console 'could not read property of undefined ' when  I clicked the buttons . I believe if the above issue is solved this will be also.

Note: The rest of the code is in my plunk

Thank you very much.

### What did you expect to happen? 

I expect to see the content of the displayTodosButton which was equal to an HTML button tag

### What actually happened? 

I got null response from the console.

### Describe what you've done so far to troubleshoot the problem. 

I checked my syntax for errors over and again. I found a suspected issue which was my <! DOCTYPE html> was in lower case but this turned out not to be the issue.

**Comment by moloak** [comment]
![Screenshot (347)](https://user-images.githubusercontent.com/72478460/95277741-6af36100-0846-11eb-853b-49c7dbc3c95b.png)

**Comment by moloak** [comment]
Thank you for this privilege

**Comment by gordonmzhu** [comment]
Can you provide an answer for: "Explain the exact steps I need to take to replicate the problem."

**Comment by moloak** [comment]
I have done that, thanks

**Comment by gordonmzhu** [comment]
Your HTML file is not structured the same way that I ask you to in the course. See the "Interlude - editor setup" section.

**Comment by moloak** [comment]
Thank you very much. It have done that. It works
