### ISSUE TITLE
I lost track on how to recreate the lessons with Chrome console

### ISSUE THREAD

**Issue by RecklessXII** [gordonmzhu/questions#489]
I lost track on how to recreate the lessons with Chrome console, since version 8 - 'Getting data from inputs', specifically since lesson 'There should be a button for adding todos'. [](- https://watchandcode.com/courses/60264/lectures/1027554)
we start using the console at **5:25**

Could you add or give me some more information? 
Because I still don't understand it after the 'How to debug any site in Google Chrome' video.

- I don't understand where to play or pause the console in Chrome, it stays paused seems like, 
- I don't understand how to add '( ) new item' just how you do it, but then in Chrome.
Because when I click 'add' with text written, nothing get's added. The code is exactly the same as yours I checked for that.

Hope you can help

**Comment by RecklessXII** [comment]
to add more info to this:
When I click the Display Todos button, I get this error in Chrome console: 

index.html:12 Uncaught ReferenceError: handlers is not defined
    at HTMLButtonElement.onclick (index.html:12)
onclick @ index.html:12

this is how, exactly like the course,  I wrote it: 

<h1>Todo List</h1>
    <div>
      <button onclick="handlers.displayTodos()">Display Todos</button>
      <button onclick="handers.toggleAll()">Toggle All</button>
    </div>

**Comment by gordonmzhu** [comment]
If you fill out all the required fields in the issue I'll be happy to help out then.
