### ISSUE TITLE
Version 9: There should be an <li> element for every todo

### ISSUE THREAD

**Issue by Roman4u** [gordonmzhu/questions#492]
### What is the associated Watch and Code lesson? 

Nothing with the code exactly, just the logic behind it.

### Include a link to your code so I can run it on my computer. 

Var view = {
        DisplayTodos: function ( ) {
               For (var i = 0; i < todoList.todos.length; i++) {
                    Var todosUl = document.querySelector(‘ul’);
                    Var todoLi = document.createElement(‘li’);
                    TodoUl.appendChild(todoLi);
                            }
                     }

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

I think I understand why the method causes problems, but I want to verify my understanding is correct and thorough:
 1. The <ul> element inside of the for loop is telling the DOM to make an entirely new <ul> element, along with the <li> element contained inside, each time the method is called, regardless if an item has actually been added to the todo array. It’s continuously creating a new <ul> element and subsequently adding an extra <li> element. Therefore, the var todosUl needs to be taken out of the for loop.
2. Currently, the view.displayTodos method is not set to zero (i.e. the previous <ul> when it’s called, so it’s attaching previous items to the new ones added whenever the method is called. So, it needs to be set to zero each time the method is called before running the for loop. Hence why we added todoUl.innerHTML = “”;

Does that all make sense? Is my understanding correct?

**Comment by gordonmzhu** [comment]
I'm not able to follow what you're saying. To make it easier, write out your code and then write what you think is happening right above it. The way you've written it, I can't match things up.

For example:

```
// This line will log 'blah blah blah' to the console.
console.log('blah blah blah');
```

**Comment by Roman4u** [comment]
Thanks for the prompt reply! Apologies for the strange layout of my first message. I don't know why it appears that way. Hopefully, the following makes more sense. 

So, as mentioned, I think I understand why the following code causes problems:

_displayTodos: function() {
            for (var i = 0; i<todoList.todos.length; i++) {
              var todosUl = document.querySelector('ul');
              var todoLi = document.createElement('li');
              todosUl.appendChild(todoLi);
            }
          }_

The code itself is fairly straightforward, but the logic behind what's causing the issues and how to fix them was a bit more complex and is taking some time for me to fully grasp. So, I want to verify my understanding with you before heading into the following tutorials.

A key point I took away from this tutorial is that by having **var todosUl = document.querySelector('ul)** inside of the for loop, it's causing the following issues to happen: (a) it's telling the DOM to make an entirely new _ul_ element_ (along with the _li element_ contained within it) each time the method is called, which is giving us an extra bullet point regardless if an actual item has been added to the todos array - demonstrated at 4:30; and (b) after a second item is added, and the method is called again, it's attaching the previous item(s) to the new item(s) - demonstrated at 4:48. And because of these two issues, what we see on the DOM (i.e. the amount of bullet points) is not a true reflection of the actual amount of items in the todos array.

So to address these two issues: (1) the _todosUl variable_ needs to be placed outside of the for loop; and (2) the value of the _li element_ needs to be set to zero (i.e. clear the unordered list) each time the method is called. Hence, why we placed the following code outside of the for loop:

            _var todosUl = document.querySelector('ul');
            todosUl.innerHTML = "";_

The logic behind these two solutions is : (1) we don't need to create an entirely new _ul element_ each time the for loop runs, which was causing issue (a) to happen; and (2) by using todosUl.innerHTML = "", it is telling the displayTodos method to begin from 0 (i.e. clear any previous item(s)) before it runs the for loop and adds an _li element_ to any items in the todos array. So, the final method becomes:

displayTodos: function() {
            var todosUl = document.querySelector('ul');
            todosUl.innerHTML = "";
            for (var i = 0; i<todoList.todos.length; i++) {
              var todoLi = document.createElement('li');
              todosUl.appendChild(todoLi);
            }
          } 

Does that all make sense?

**Comment by gordonmzhu** [comment]
"A key point I took away from this tutorial is that by having var todosUl = document.querySelector('ul) inside of the for loop, it's causing the following issues to happen: (a) it's telling the DOM to make an entirely new ul element"

What you said here is not true. I suggest reviewing the previous videos in this section so that you are clear on what this line does. Review the videos carefully, step through the code using the debugger, and also experiment with the line yourself to see how it works.

**Comment by Roman4u** [comment]
Followed your suggestions and finally figured out the logic! Thank you!

**Comment by gordonmzhu** [comment]
👍
