### ISSUE TITLE
opening up an untitled doc? in chrome to learn JS

### ISSUE THREAD

**Issue by isababe626** [gordonmzhu/questions#493]
###https://watchandcode.com/courses/60264/lectures/929349 

Write your response here (required). please help me. how do i open an untitled doc like you do in this video? i have node.js but want to be able to follow along exactly how you do things so i dont get lost.

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by isababe626** [comment]
so ive went and downloaded the text editor "Atom".

**Comment by gordonmzhu** [comment]
You can use any text editor. Those are just notes. I'm not writing code in this video.
