### ISSUE TITLE
is the WatchAndCode program still going strong? Is the Slack channel still active?

### ISSUE THREAD

**Issue by beezy12** [gordonmzhu/questions#494]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by beezy12** [comment]
I don't have a coding question....just want to know if the paid course is still going strong. Im working through the PJS part right now

**Comment by gordonmzhu** [comment]
Yes. Hey Brian.
