### ISSUE TITLE
New Version of the Foundations course?

### ISSUE THREAD

**Issue by Roman4u** [gordonmzhu/questions#495]
### What is the associated Watch and Code lesson? 

nothing with the code, just a question regarding the newest version of the foundations course

### Describe what you've done so far to troubleshoot the problem. 

So, I only had two versions left in the original foundations course, which was going very well, but when I logged in today I saw that the entire course had been completely redone. I'm wondering if it's possible to somehow have access to the original course so I can finish it? I understand this is a free course so if this is not possible I completely understand

**Comment by gordonmzhu** [comment]
Hey Roman. The new course teaches a lot of important skills that weren't in the old course, so we're requiring everyone to start anew.
