### ISSUE TITLE
Keep getting undefined

### ISSUE THREAD

**Issue by timmparsons** [gordonmzhu/questions#5]
### What is the associated Watch and Code lesson? 

Write your response here (required).

V8 - There should be a button for changing todos

### Include a live demo link so that I can run your code. 

Write your response here (required).
https://plnkr.co/edit/DiZQkhlkGxJVV38zyEy4?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
Add a todo and it will show. Try and change it and it says undefined

### What did you expect to happen? 

Write your response here (required).
Followed the tutorial and it worked for you. Tried debugging and it changes in the changeTodo function but gets lost somewhere in the handler.changeTodo

### What actually happened? 

Write your response here (required).
Shows undefined but still gives the parenthesis so it's looping through the condition correctly, it's just the showing of the new value.

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
Ran debugger, rewrote the code and am still baffled.

**Comment by gordonmzhu** [comment]
You have a typo in line 29. You have `this.todos[position] = todoText;`, which is not what I have in the videos. Carefully go back and find the lessons where I wrote this code and make sure yours matches up.
