### ISSUE TITLE
Version 4 . Video 3.What happened to the display method in changetodo .. in addtodo it wasn't in the scope but this time it was in the method . still didnt have any difference.

### ISSUE THREAD

**Issue by sandeepvvn** [gordonmzhu/questions#50]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
I don't understand your question. Please elaborate with specific code examples so I can follow your  thinking.
