### ISSUE TITLE
Gordon, I  am enjoying your lesson. I am actually feeling like I am learning how to program in Javascript.  Let me know if you are open to Community College Training programs as a business venture. I am on linkedin --Gerald Ringer

### ISSUE THREAD

**Issue by gringer44** [gordonmzhu/questions#51]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
No sorry, but thanks for asking.
