### ISSUE TITLE
I'm 51 Does age hinder your ability to find a job, if your skills are good?

### ISSUE THREAD

**Issue by rockncodejedi** [gordonmzhu/questions#52]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
If you are good, things will work out. All else equal, it is better to be younger (because discrimination exists unfortunately), but if you're good, this will be more of an inconvenience than a roadblock.

So, focus on being good at programming and everything will work out.
