### ISSUE TITLE
Explanation of a concept

### ISSUE THREAD

**Issue by gacevicaleksandra** [gordonmzhu/questions#53]
### What is the associated Watch and Code lesson? 
https://watchandcode.com/courses/60264/lectures/946811

Write your response here (required).
Hi Gordon, I was watching previous video, and if I change this:

    var pozicijamarke = this.marka[pozicija];
    pozicijamarke.odabrana = !pozicijamarke.odabrana;

to this:

    var pozicijamarke = this.marka[pozicija].odabrana ;
    pozicijamarke= !pozicijamarke;
It doesn't work. I watched a video again but could not understand why. Can you help me :)

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/pQbJdAx82nVYKrX9n1fp?p=info

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 
Theoretical question

Write your response here (required).

### What did you expect to happen? 

I expected for both to work the same

Write your response here (required).

### What actually happened? 

It does not make todo completed if done in the other way

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Did it again, watched video again

Write your response here (required).

Same output. so I wanted to check if it may be something else in the program or some concept other connected to this which I need to go back and check. I'm actually clueless of the cause

**Comment by gordonmzhu** [comment]
Hey @gacevicaleksandra. Sorry but I can't understand your code because it's not in English. If you post the code with the original English variables then I can take a look. Thanks.

**Comment by logictom** [comment]
I had this same question as I also tried this.
The code section is:
```
var todo = this.todos[position];
todo.completed = !todo.completed;
```
and why you cannot do something like this:
```
var todoCompleted = this.todos[position].completed;
todoCompleted = !todoCompleted;
```
My understanding is that the first gives a pointer to the object, and therefore modify the ordinal value, but the second creates a local variable, and therefore updates the local variable but not the original.
Am I correct in assuming that if you assign a variable to a object you get a pointer but if it is a primitive then you get a copy?
