### ISSUE TITLE
Caution Exclamation Marks in my code.  Dont see it in your examples.  Probably not important, but my OCD perfectionist side is throwing flags!!!

### ISSUE THREAD

**Issue by OlDaagNewTricks** [gordonmzhu/questions#55]
### What is the associated Watch and Code lesson? 

This was during V6.  Not necessarily a place I got stuck because code ran as expected after checking all work in console.  But I noticed that my code throws the yellow exclamation caution signs in plunker when writing the preceding for loops and defining 'i' within those loops.  I noticed that in your plunker screen those caution signs are not to be seen.

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/2rI4j8vDVwgCB77taRC3

Lines 47 and 51

### Explain the exact steps I need to take to replicate the problem. 

No steps necessary other than analyzing my plunker screen at lines 47 and 51. =)

### What did you expect to happen? 

Although I pretty sure the caution signs are just that, cautions.  I am a bit uneasy whenever I see them.

### What actually happened? 

Caution signs were thrown.  But code worked as expected.

### Describe what you've done so far to troubleshoot the problem. 

I tried to look into the menus in Plunker to see if there was a way to toggle those specific cautions.  Went into the code linting tab on left-hand side of the web app to see if there was a way to turn of those notifications but did not see any option to do so.

**Comment by gordonmzhu** [comment]
Hey @OlDaagNewTricks. Yep you can safely ignore those warnings. If they're really bothering you, you can use another variable name in each loop. For example, you could use `i` in one loop, and then `j`, and then `k` like so:

```
    for (var i = 0; i < totalTodos; i++) {
      if (this.todos[i].completed === true) {
        completedTodos++;
      }
    }
    //If everythings is true, make everything false.    
    if (completedTodos === totalTodos) {
      for (var j = 0; j < totalTodos; j++) {
        this.todos[j].completed = false;
      }
    } else {
      for (var k = 0; k < totalTodos; k++) {
        this.todos[k].completed = true;
      }
    }
```
