### ISSUE TITLE
[] vs ()

### ISSUE THREAD

**Issue by ntmanning** [gordonmzhu/questions#56]
Gordon, really enjoying your course. First time I have ever done anything programming. I'm working on the objects lessons and just have a quick question.

When do you use () vs []? My question relates to the changeTodo vs deleteTodo

    changeTodo: function(position, newValue) {
      this.todos[position] = newValue;
      this.displayTodos();
    },
    deleteTodo: function(position) {
      this.todos.splice(position, 1);
      this.displayTodos();

Why a [] bracket on change, but then a () on delete?

Thanks so much!
Tyler

**Comment by gordonmzhu** [comment]
This is more fundamental to arrays and functions. I suggest (1) reflecting on what's happening each time you use () versus [] and (2), reviewing the lessons on arrays and functions because they go over these topics.
