### ISSUE TITLE
Console won't print out an object

### ISSUE THREAD

**Issue by mjuros** [gordonmzhu/questions#57]
### What is the associated Watch and Code lesson? 

Version 3 - objects
It should store todos array on an object

https://watchandcode.com/courses/60264/lectures/900211

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/RPIi5rDmkSBFKiGT0ZkA?p=info

### Explain the exact steps I need to take to replicate the problem. 

I can't acces the todoList object in the console, it throws back an error

### What did you expect to happen? 

I expected that the console would print our the object, but it din't

### What actually happened? 

When I entered "todoList" in the console, it returned the following error:

"Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) @ VM386:1"

### Describe what you've done so far to troubleshoot the problem. 

I don't know what I need to do to troubleshoot the problem. I tried restarting both browser tab and browser window, bu it doesn't solve the problem.

![plnkr](https://user-images.githubusercontent.com/35665043/45362502-4aa83800-b5d5-11e8-9c37-568c8eb71a79.PNG)

**Comment by gordonmzhu** [comment]
You have several typos in your code, which is preventing the code from running at all. Go back and start from scratch again, paying close attention to make sure your code is *exactly* the same, down to the character, and formatting as well. Right now, everything is off.
