### ISSUE TITLE
Remembering volume level troughout videos - Practical Javascript

### ISSUE THREAD

**Issue by Adrian-Swifter** [gordonmzhu/questions#59]
It's frustrating to adjust volume level on every single video, as it is always defaulted to max. I think it would be more convinient to  remember my change of volume troughout videos.
Also, i think it is better to put "complete and continue" button on the bottom of page, not on top, as it is somethimes really hard to navigate trough platform's monochromatic color scheme.

**Comment by gordonmzhu** [comment]
Hey Adrian. Is it possible to just lower the volume on your machine? Currently I don't have the ability to do what you're suggesting, but I'll keep this in mind in the future if things change.
