### ISSUE TITLE
Toggle All button Uncaught error

### ISSUE THREAD

**Issue by KFarrington** [gordonmzhu/questions#6]
### What is the associated Watch and Code lesson? 

Toggling Todo: https://watchandcode.com/courses/60264/lectures/1027559

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/vfpMgU?p=streamer

### Explain the exact steps I need to take to replicate the problem. 

Copied code from video. 

script.js:34 Uncaught TypeError: Cannot read property 'completed' of undefined
at Object.toggleCompleted (VM6785 script.js:34)
at Object.toggleCompleted (VM6785 script.js:87)
at HTMLButtonElement.onclick ((index):33)

So I checked for spelling issues, I confirmed I used same variables across both HTML and JS and went through and my code matches yours exactly.

### What did you expect to happen? 

That if I had a list of items it would toggle them all done or not done

### What actually happened? 

script.js:34 Uncaught TypeError: Cannot read property 'completed' of undefined
at Object.toggleCompleted (VM6785 script.js:34)
at Object.toggleCompleted (VM6785 script.js:87)
at HTMLButtonElement.onclick ((index):33)

### Describe what you've done so far to troubleshoot the problem. 

Confirmed code matches yours.
confirmed no spelling errors
Confirmed code syntax matches all the other buttons (it does)

**Comment by gordonmzhu** [comment]
Your code does not match mine. You have a typo in your `toggleCompleted` method. Rewatch the associated lessons and pay close attention to **every single character**.
