### ISSUE TITLE
Problem with Console in Chrome developer tools

### ISSUE THREAD

**Issue by deni404** [gordonmzhu/questions#60]
Hi Gordon 
I am having some problems with the console in the Chrome Developer Tools.
Tried making some changes like adding Todos and other stuff but I get the Reference error in the console in Chrome.
Ar the moment I am at Loops of Logic, lesson display Todos should show completed.
![reference_error](https://user-images.githubusercontent.com/22860901/45555165-547da580-b838-11e8-8ce7-913c28bf89ce.png)
 The link to my Plunker : 
https://plnkr.co/edit/AeeOk9UeZcgvEHPE5QwR

Tried checking the code if I missed or misspelled something but I couldn't find anything.
What could it be? 
I would really appreciate if you could help me with this.

Thank you.

Regards
Deni

**Comment by hydroweaver** [comment]
In the drop down where it says TOP on your screenshot, change it to plunkr preview.

**Comment by deni404** [comment]
> In the drop down where it says TOP on your screenshot, change it to plunkr preview.

I tried it shows the same error.

**Comment by hydroweaver** [comment]
Line 8 and 12 show error ...fix them...for example you've written var = 1

**Comment by deni404** [comment]
@hydroweaver Thank you. It's fixed. How I didn't see that I don't know.

**Comment by hydroweaver** [comment]
On the left side of the js editor you'll see small X in red they are the error or ! In case of warnings cheers !

**Comment by deni404** [comment]
Thanks again, hopefully I'll get better after completing the course.
