### ISSUE TITLE
Version 3 - Objects 

### ISSUE THREAD

**Issue by dkdeleo** [gordonmzhu/questions#61]
The first thing we are instructed to do after right clicking in plunker and going to console is to dropdown the top menu next to the filter icon and select PlunkerPreviewTarget(run.plunkr.co/). 
Unfortunately the PlunkerPreviewTarget option is not available to me in the dropdown menu no matter what type of browser I use( I tried google chrome and chromium).

**Comment by hydroweaver** [comment]
Can you share a screenshot? Hope you're not inspecting the wrong area.

**Comment by dkdeleo** [comment]
Just sent one. Let me know if you have trouble seeing it.

**Comment by hydroweaver** [comment]
You need to paste it here for us to see

**Comment by dkdeleo** [comment]
/Users/dakotadeleonardis/Desktop/Screen Shot 2018-09-14 at 12.38.10 PM.png

**Comment by gordonmzhu** [comment]
Once you post a screenshot we'll take a look. See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/.
