### ISSUE TITLE
Having trouble running the code in the inspect window

### ISSUE THREAD

**Issue by SonyaKap** [gordonmzhu/questions#64]
### What is the associated Watch and Code lesson? 

Write your response here (required).

https://watchandcode.com/courses/60264/lectures/900211

2:42 minute mark

### Include a live demo link so that I can run your code. 

Write your response here (required).  http://plnkr.co/edit/IVQ0ylBcgYpXcLn3xobj?p=info

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required). I run my project, write click, hit inspect, go to the console, change from top to PlunkerPreviewTarget, and then type a command (ex. todoList), and it will return with the error "UncaughtReferenceError: todoList is not defined"
### What did you expect to happen? 
Write your response here (required).  

I expected it to output the object in its entirety, because that's what happens when you do the same thing in version 3 in the video

### What actually happened? 

Write your response here (required). 
 This is the error
VM1550:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1
(anonymous) @ VM1550:1

### Describe what you've done so far to troubleshoot the problem. 

I googled it, and everyone's problem seemed to be a typo, but I couldn't find any typos in mine.
Write your response here (required).

**Comment by hydroweaver** [comment]
Are you in Plunkr preview target? Also it would be better that you name the same JS file on the html file as the one you work on.

**Comment by gordonmzhu** [comment]
Thanks for finding the issue @hydroweaver.

Yep a reminder to follow everything as closely as possible, including filenames to avoid similar issues in the future.
