### ISSUE TITLE
can't get plnkr to work

### ISSUE THREAD

**Issue by lindsjg8** [gordonmzhu/questions#65]
Hello,
Here is the lesson I'm currently doing (but I have had problems with plnkr on every lesson):
https://watchandcode.com/courses/60264/lectures/942296

Here is link to my plunk: 
https://embed.plnkr.co/dgkOCXCLXFy4FUZmMimw/

I enter the lesson's code,  hit run, set up the console with the plunkr.preview.Target and then type this into the console:
todoList.changeTodo(0, 'green');

I receive this error message:
VM516:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1

I'm also attaching a screenshot of my plnkr

However, when I paste that exact code and run it in JS Bin, and then type (below) into the console, it works perfectly:
todoList.changeTodo(0, 'green')
 
Here is a link to my JS Bin:
https://jsbin.com/sijozaleqa/edit?js,console,output

I"m also attaching a screenshot of JS Bin.

What am I doing wrong with Plnkr?

Thanks,
Lindsey
<img width="1280" alt="screen shot 2018-09-18 at 12 43 50 pm" src="https://user-images.githubusercontent.com/9922578/45702741-99f3e880-bb40-11e8-9df8-178bbf4b6efa.png">
<img width="1019" alt="screen shot 2018-09-18 at 12 34 44 pm" src="https://user-images.githubusercontent.com/9922578/45702765-a37d5080-bb40-11e8-86a7-425ec48f70b8.png">

**Comment by hydroweaver** [comment]
Don't change to preview target and run with top:

![image](https://user-images.githubusercontent.com/6553008/45704033-92a9fa80-bb93-11e8-9303-f19bad029527.png)

**Comment by gordonmzhu** [comment]
Your index.html is blank. Go back to the beginning of this version and make sure it has the same content as mine. Once you do that, it'll work as expected.
