### ISSUE TITLE
Error in Console Chrome

### ISSUE THREAD

**Issue by deni404** [gordonmzhu/questions#67]
Having a small issue when adding items in the console in Chrome.
At the moment I am in Version 9, lesson -There should be an li element for every todo -, somewhere around the 6:40 mark from the video when adding items in the console I get an error. 
I tried in Plunkr preview I got the same result.
![error](https://user-images.githubusercontent.com/22860901/45831446-affbd780-bcff-11e8-9c78-02a2e0638f06.png)

The link to my plunkr is 
https://plnkr.co/edit/AeeOk9UeZcgvEHPE5QwR

**Comment by gordonmzhu** [comment]
You have many typos in your code that is preventing the code from even running at all.

You should backtrack to a point in the course where your code works and work from there, paying careful attention to detail and making sure your code is the same as in the videos and is free of typos.
