### ISSUE TITLE
Understanding how we are able to access the todoText

### ISSUE THREAD

**Issue by bbuckner2092** [gordonmzhu/questions#68]
### What is the associated Watch and Code lesson? 

Write your response here (required).

In Version 4 video 3, you ended up changing the todos[position] to this.todos[position].todoText = todoText;

I completely understand every piece of code besides HOW ARE WE ABLE TO ACCESS THE todoText property.  The reason is because with the beginning code (this.todos[position]) I know that we are accessing the todos array... As I processed what was going on I wanted to ask this, "since we have used 'this' within our code does it allows us the opportunity to use the entire todoList object?  If this holds true then we are able to use the dot notation for **ANY** piece of code that we may have within that object, right?"

The reason I am asking is because I feel like we are "overstepping" our boundaries by going from the todos array then heading straight into the addTodos function to access its property (todoText).  

**Re-looking at the code I guess the more direct question is this, " Why would we NOT use the following code to access the todoText property, this.todos[position].addTodos.todoText"?**

From previous videos, we have been able to do todoList.addTodos, todoList.changeTodos, and todoList.deleteTodos yet when it comes to changingTodos we are using the following code: this.todos[position].todoText

To me it almost feels like we are "missing a piece of code"... I hope you can understand my logic behind this question.

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
Can you provide an exact timestamp and line number so I know where this code is?

**Comment by gordonmzhu** [comment]
Closing since there hasn't been a response for 2 days.

**Comment by bbuckner2092** [comment]
Sorry for the late reply.  It has been a hectic week for me and my internet
at home was not functioning properly.

I can honestly say that I did figure it out.  I stepped away from the
videos and allowed myself time to just relax.  Once I re-watched the video
the concept finally sunk in.

I do thank you for at least reaching out to me.

**Comment by gordonmzhu** [comment]
Thanks for updating the thread @bbuckner2092 . Glad you figured it out.
