### ISSUE TITLE
How do we start building apps?

### ISSUE THREAD

**Issue by deni404** [gordonmzhu/questions#69]
Hello

Wanted to ask when we build an app or website do we usually start with something like Version 1 and we make changes along the way or we start with something like Version 9 let's say.Is it about experience or there is a process when developing these kinds of apps?

Also, one more question, am 36 and am starting to learn web development. Am I too late?

Thank you

**Comment by gordonmzhu** [comment]
Yes, you start bit by bit. There is a process that comes from experience. I talk a little bit about the journey in this video. 

https://watchandcode.com/courses/experiments/lectures/6209981

You're not too late. It's never too late.
