### ISSUE TITLE
Why no };

### ISSUE THREAD

**Issue by lindsjg8** [gordonmzhu/questions#71]
Hi, I am on the below lesson, time stamp: 2:37
https://watchandcode.com/courses/60264/lectures/946809

I am including a screenshot of the code at this point in the lesson. I am wondering why line line 10 ends like });

Since we are pushing an object onto the todos array, shouldn't the object close like this };

which would make like 10, look like this:
 };);

I don't understand why the object being pushed just closes with }   

Thanks,
Lindsey
<img width="710" alt="screen shot 2018-09-25 at 8 25 20 am" src="https://user-images.githubusercontent.com/9922578/46014454-4e3fc280-c09d-11e8-9b43-d824a4e384cc.png">

**Comment by gordonmzhu** [comment]
Semicolons come at the end of a line of code (there are a few rules to this, but this is the overall idea).

What you have here is an arguments list for a function. Function arguments never end with semicolons, they're comma separated, similar to object properties or array elements.

For example, if I have a function called `myFunction` and I call it with 3 arguments, none of them are followed by semicolons, but there is one at the *end* of the function call.

`myFunction('some text', {}, {});`
