### ISSUE TITLE
Cannot read property 'addEventListener' of null; Possible idiocy but seriously stuck

### ISSUE THREAD

**Issue by weefunker** [gordonmzhu/questions#73]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027554

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/GkGZJJnnVrhPmO6kGygu?p=preview

### Explain the exact steps I need to take to replicate the problem. 

Clicking the buttons keep saying that add todos is undefined. I've went over the code for an hour and nothing is working

### What did you expect to happen? 

For a todo to be added to the todolist

### What actually happened? 

Cannot read property 'addEventListener' of null

### Describe what you've done so far to troubleshoot the problem. 

I tried to use the debugger but for whatever reason its not working when trying to use plnker

**Comment by weefunker** [comment]
Fixed issue 

## removed previous button onclick code before refactoring

**Comment by gordonmzhu** [comment]
Thanks for updating the issue @weefunker. Glad you were able to figure it out.
