### ISSUE TITLE
DOM

### ISSUE THREAD

**Issue by anirusn** [gordonmzhu/questions#74]
Hi
First of all thank you so much for providing such a great course free of cost.
Actually, I don't understand the structure of DOM. If you can make me understand it using the diagram like in Data type and comparison that would be great.
Thank you Again

**Comment by gordonmzhu** [comment]
Hey @anirusn. This question is a bit too general to address here in text. If you have a specific question I can help answer it here. Otherwise, your best bet would be to ask in office hours (Mondays at 6PM PST, see the Facebook group).

Thanks!
Gordon
