### ISSUE TITLE
Hallo https://watchandcode.com/courses/60264/lectures/1126299 why was it here in the addEventListener 'click' and not 'onclick' as we learned in previous lessons

### ISSUE THREAD

**Issue by nidhaloff** [gordonmzhu/questions#75]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
It was just to show you a different way of doing things so that you're aware there are multiple ways to get this done. You can use either, they do the same thing.
