### ISSUE TITLE
My code does not automatically indent

### ISSUE THREAD

**Issue by nathancoady** [gordonmzhu/questions#76]
### What is the associated Watch and Code lesson? 

"It should have a function to display Todos"

### Explain the exact steps I need to take to replicate the problem. 

There really is no exact step. On the last lesson, it automatically indented. On this one, whenever I shift + enter to add new lines, it just doesn't indent, making the code say undefined. 

### What did you expect to happen? 

The code to be indented automatically. Or to be able to indent it myself, which also doesn't work

### What actually happened? 

Undefinted

### Describe what you've done so far to troubleshoot the problem. 

checked online, put the code into plkr, asked friends that know how to code

**Comment by gordonmzhu** [comment]
Please fill out all the required fields and I can take a look. You skipped several.
