### ISSUE TITLE
Plunker error: Reference error

### ISSUE THREAD

**Issue by yudataguy** [gordonmzhu/questions#77]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/900211

### Include a live demo link so that I can run your code. 

http://embed.plnkr.co/iHgkTQlgP86Cqo3aTw5Q/

### Explain the exact steps I need to take to replicate the problem. 

The code is already there, but on Chrome console, various errors showed up. I couldn't get plunkr running correctly in Firefox, so couldn't test it there. 

### What did you expect to happen? 

As video indicated, the todoList should show up in console, but mine didn't. 

### What actually happened? 

Please see photo for detailed error.
https://imgur.com/SyvOZBV

### Describe what you've done so far to troubleshoot the problem. 

I've tried disable some extension, since I expect it should be the cause. But none worked so far. I'll continue the course but hope this issue can be resolved.

**Comment by hydroweaver** [comment]
@yudataguy you need to change to Plunkr Preview Target

**Comment by yudataguy** [comment]
You're right. I was on the wrong target.
