### ISSUE TITLE
Version 6: ToggleAll

### ISSUE THREAD

**Issue by ButteryPotato** [gordonmzhu/questions#78]
### What is the associated Watch and Code lesson?  

https://watchandcode.com/courses/60264/lectures/936343  at 4:15
I have checked, double checked, and triple checked, and checked again and again and my code matches yours correctly. The problem is that I cannot execute the toggleAll function. 

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/p9WYhjCy1Q23S3GsZrAi?p=preview

### Explain the exact steps I need to take to replicate the problem. 

The only problem is that my current code does not execute toggleALL function. There is an exclamation mark on line 50 that says 'i' is already defined? 

### What did you expect to happen? 

I expect toggleAll to run.

### What actually happened? 

It does not run and says the following:
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.toggleAll (VM2789 script.js:43)
    at <anonymous>:1:10

### Describe what you've done so far to troubleshoot the problem. 

I deleted code for the ToggleAll lesson and restarted twice. I have checked for syntax errors. Spelling errors. I tried deleting the "var" from line 50 to get rid of the exclamation mark but it still doesn't work. Everything works fine until this lesson.

**Comment by ButteryPotato** [comment]
Nvm figured it out after an hour of cursing.

**Comment by hydroweaver** [comment]
It seems to be working correctly !
