### ISSUE TITLE
Practical JS Video Player won't allow me to skip to other parts of video

### ISSUE THREAD

**Issue by zaynrahn** [gordonmzhu/questions#79]
### What is the associated Watch and Code lesson? 

Practical Javascript course videos.

### Include a live demo link so that I can run your code. 

N/A

### Explain the exact steps I need to take to replicate the problem. 

I am watching the Practical JS videos in Chrome and whenever I try to go skip to an earlier point in a video to replay a section, it won't let me. If I try to drag the bar to an earlier point, it still won't let me.

### What did you expect to happen? 

I expect to be able to go back in a video to replay or reference something I might have missed. 

### What actually happened? 

No error.

### Describe what you've done so far to troubleshoot the problem. 

N/A

**Comment by gordonmzhu** [comment]
Are you still having this issue? I just tried this in Chrome on MacOS and was not able to replicate it.

**Comment by zaynrahn** [comment]
Hi Gordon,

Thanks for getting back. It actually started working for me again shortly after I posted the Git issue . Not sure if it took a while for the media player’s full functionality to load.

Zayn

**Comment by gordonmzhu** [comment]
Awesome. Thanks for the update.
