### ISSUE TITLE
"Uncaught ReferenceError: todoList is not defined at <anonymous>:1:1"

### ISSUE THREAD

**Issue by DBNoisemaker** [gordonmzhu/questions#8]
### What is the associated Watch and Code lesson? 

Anywhere from V6 & 7  no exact timestamp, more just a problem with the code not seeing.  Probably syntax error on my part but I just can't figure it out.

### Include a live demo link so that I can run your code. 

https://embed.plnkr.co/cdWs92NYPCZVAKHlRFTv/  
hope this ^ works

### Explain the exact steps I need to take to replicate the problem. 

All I did was try to follow the examples and I got this error message.

### What did you expect to happen? 

It was working and then it stopped working somewhere along the way.  I kept on going with the lessons as I didn't want to get delayed but it'd be nice to be back on track. 

### What actually happened? 

Inspetor returned:
"Uncaught ReferenceError: todoList is not defined at <anonymous>:1:1"

### Describe what you've done so far to troubleshoot the problem. 

Tried making sure all my semicolons were in the right place... that's all I can do man.  I don't want to re-type the whole thing.

**Comment by gordonmzhu** [comment]
You have typos littered throughout your toggleAll method.

Go back to the videos methodically and find the typos. The issue here is one of precision. You need to approach programming with character-by-character precision. If you don't, you will continue to have experiences like this.
