### ISSUE TITLE
Can't access the right console features through Plunker

### ISSUE THREAD

**Issue by sleepydadATX** [gordonmzhu/questions#80]
### What is the associated Watch and Code lesson? 

Version 3 - Objects > It Should Have a displayTodos method (starting at 2:07)

### Include a live demo link so that I can run your code. 

I'm not sure how to do this but here is the code:
var todoList = {
  todos: ['item 1', 'item 2', 'item 3'], 
  displayTodos: function() {
    console.log('My Todos', this.todos);
  }
};

### Explain the exact steps I need to take to replicate the problem. 

I cannot seem to (i) access the console via right click/inspect in the Plunker coding pane, and (ii) when I access the console from a different area on the same page, I do not see a dropdown for "plunkerPreviewTarget."

### What did you expect to happen? 

I expected to be able to run the displayTodos method in the console, but was not able to (per the video instruction). 

### What actually happened? 

VM38:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1

### Describe what you've done so far to troubleshoot the problem. 

I'm not sure that any of the above apply. Is it a different version of Plunker or Chrome that I am using that is the reason I don't have access to the same console features, at least via those same steps?

**Comment by gordonmzhu** [comment]
For `Include a live demo link so that I can run your code`, include the link to your Plunker project.

**Comment by gordonmzhu** [comment]
Closing since I haven't heard back for 3 days.
