### ISSUE TITLE
Can't rewind videos

### ISSUE THREAD

**Issue by markdreed512** [gordonmzhu/questions#81]
Why can't I rewind any videos the first time I watch them?  I tried multiple browsers.

**Comment by gordonmzhu** [comment]
I wasn't able to replicate the issue and haven't heard any similar complaints. Can you provide more detail and some screenshots that illustrate the problem?

**Comment by markdreed512** [comment]
Solved it! I realized that the issue was only when I was playing a video, then trying to click earlier in the video progress bar, like with the youTube interface.  With this video player you can only click earlier in the progress bar if the video is paused, not when it is currently playing (weird design choice).


Mark Reed
Murchison Middle School
Web Design, Computer Science
http://www.murchisonmatadors.org/reed


________________________________
