### ISSUE TITLE
array.slice() not working on my chrome console

### ISSUE THREAD

**Issue by Sal99** [gordonmzhu/questions#82]
Hi Gordon,

I was going through you array.slice()  in your array lessons here https://watchandcode.com/courses/practical-javascript/lectures/900207

And I took the liberty to learn a bit morn about this array.slice() from MDN and in there I learnt and understood it and the code worked therre. However, when I tried it on my own chrome console it didn't work. I tried both with var and let and I kinda like let.  I've attached a file of my chrome console. Can you please tell me why it's not working?

Thanks,
Sal

**Comment by gordonmzhu** [comment]
Hey Sal. If you fill out the required fields in the issue form, I can take a look. I can't help without being able to see what you were doing.
