### ISSUE TITLE
GET https://run.plnkr.co/jfZexlpvg33fFa00/jsconfig.json 404

### ISSUE THREAD

**Issue by crkubiak** [gordonmzhu/questions#83]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/900211

### Include a live demo link so that I can run your code. 

https://www.youtube.com/watch?v=1LvQvesXCMM&feature=youtu.be

### Explain the exact steps I need to take to replicate the problem. 

Followed the instructions starting at 2:32 in the video

### What did you expect to happen? 

That the console would load the object. 

### What actually happened? 

I get a 404 error for JSON and then a second error when I run todoList

### Describe what you've done so far to troubleshoot the problem. 

I disabled my ublock and reloaded the site.

**Comment by gordonmzhu** [comment]
@crkubiak Can you provide the URL to your Plunker project?

**Comment by crkubiak** [comment]
Gordon,

I moved forward using repl.it.  I don't think it was anything to do with the code I was inputting.  For whatever reason I the laptop I was using it would give me a file not found error for the JSON file. I have circled back around and looked at it from a different laptop and it worked fine.  I believe it was a system issue on my end.  Thanks.

**Comment by gordonmzhu** [comment]
@crkubiak Sounds good. Thanks for the update and glad you were able to keep going.
