### ISSUE TITLE
for loop undefined

### ISSUE THREAD

**Issue by imlastrebor** [gordonmzhu/questions#86]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/956106

### Include a live demo link so that I can run your code. 

https://embed.plnkr.co/e2kT5rdk2ToRxomVMMcg/

### Explain the exact steps I need to take to replicate the problem. 

I tried to follow your video but when I type todoList.displayTodos(); to the console it only gives undefined. 
### What did you expect to happen? 

In video you get to the console todos that you've added there when you type todoList.displayTodos(); .

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

I watched videos again again, searched for the typos and tried to play with the code only clue I get is that this might relate to todoText. I managed to get 
this error "Uncaught TypeError: Cannot read property 'todoText' of undefined" when I changed for loop condition from i < this.todos.lenght  to i < 3 .

**Comment by gordonmzhu** [comment]
You need to select `plunkerPreviewTarget` in the console. Rewatch the videos in V3 to see how I do this.

**Comment by imlastrebor** [comment]
Hi, I have selected plunkerPreviewTarget. [Screenshot from console](https://imgur.com/a/jcwOXhI) .

**Comment by imlastrebor** [comment]
Hi, I think I have always keep that plunkerPreviewTarget selected. I can't find any solution to this problem. Here is [screenshot from console](https://imgur.com/a/AuFdmpq)

**Comment by imlastrebor** [comment]
Hi, I think I have always keep that plunkerPreviewTarget selected. I can't find any solution to this problem. Here is [screenshot from console](https://imgur.com/a/AuFdmpq)

**Comment by imlastrebor** [comment]
Hi, I think I have always keep that plunkerPreviewTarget selected. I can't find any solution to this problem. Here is [screenshot from console](https://imgur.com/a/AuFdmpq)

**Comment by imlastrebor** [comment]
Hi, I think I have always keep that plunkerPreviewTarget selected. I can't find any solution to this problem. Here is [screenshot from console](https://imgur.com/a/AuFdmpq)

**Comment by imlastrebor** [comment]
Hi, I think I have always keep that plunkerPreviewTarget selected. I can't find any solution to this problem. Here is [screenshot from console](https://imgur.com/a/AuFdmpq)

**Comment by Madakin** [comment]
I'm also having the same issue. I'm using repl.it instead (mostly because I find it easier than plunker personally) so I'm not sure if that has something to do with it, but it's telling me that todoText is undefined. Here's a link to my code. 

https://repl.it/@Mdking2012/UnwillingShadyArchives
