### ISSUE TITLE
todoList undefined in Plunker

### ISSUE THREAD

**Issue by wilsonrapp** [gordonmzhu/questions#87]
### What is the associated Watch and Code lesson? 

Version 3 - Objects: It should have a changeTodo method 
https://watchandcode.com/courses/60264/lectures/942296

### Include a live demo link so that I can run your code. 

http://embed.plnkr.co/iQNiOpQjOinE5lFQ/

### Explain the exact steps I need to take to replicate the problem. 

I have typed code exactly as is shown in videos, and then select "Run" in Plunker. When opening Inspect > Console and attempting to call changeTodo(), I receive an error message in my console: 
"VM4526:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1"

### What did you expect to happen? 

To be able to manipulate list through console. Following the exact steps as they are completed in the lesson video. 

### What actually happened? 

Error message: "VM4526:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1"

### Describe what you've done so far to troubleshoot the problem. 

- I have attempted to delete and start a new Plunk on multiple occasions. 
- I have logged out / in of Plunker and am still having the same issue. 
- I have cleared my cache & cookies in Chrome (running on Mac 10.14 & Chrome 69.0.3497100)
- I attempted to create the Plunk through the new Plunker editor

Despite all of these attempts, I'm still receiving the same error message.

**Comment by gordonmzhu** [comment]
Make sure you follow the way I do things exactly. For example, what may have been the issue is the way you set up your file paths, which differs from the video.

I pasted your code into a new project and it worked fine. See http://plnkr.co/edit/8acz6gV1yKSnDxRTsmnn and make sure you're in `plunkerPreviewTarget` in the console.
