### ISSUE TITLE
Can Brackets work instead of plnkr

### ISSUE THREAD

**Issue by arathichhetri** [gordonmzhu/questions#88]
Hi Gordon,
Ive just started the 'functions' part of your free intro to Javascript. You seem to switch from the google console to an editor. I've downloaded Brackets and would like to know if I can use it. If yes, how do I start with it? I tried to type in your turkey recipe and save it as a .js file but it gave me an error.

**Comment by gordonmzhu** [comment]
Those videos are not actual code. They are just there for demonstration. You'll notice I never run any of the code in the sandwich examples.

**Comment by arathichhetri** [comment]
Wow!

I'm so excited to hear from you Gordon. Your lessons are so well put. Thank you. I'll keep at it. 

You are inspiring.
