### ISSUE TITLE
Where are you writing the code?

### ISSUE THREAD

**Issue by urmikesmuted** [gordonmzhu/questions#89]
Watch and code Practical Javascript version 2. I know it's probably a stupid question but i hope you can help

**Comment by hydroweaver** [comment]
I use repl.it

**Comment by hydroweaver** [comment]
Although per Gordon you can use glitch

**Comment by urmikesmuted** [comment]
> Although per Gordon you can use glitch

Thank you so much!

**Comment by gordonmzhu** [comment]
Please follow along with the videos. All the instructions are there.
