### ISSUE TITLE
Continuation of issue 

### ISSUE THREAD

**Issue by DBNoisemaker** [gordonmzhu/questions#9]
### What is the associated Watch and Code lesson? 

Somewhere in the middle, not sure.   None of the functions run.  
"VM1249:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1"

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/cdWs92NYPCZVAKHlRFTv

### Explain the exact steps I need to take to replicate the problem. 

Try to call a function.

### What did you expect to happen? 

It would have been nice if it worked.  I'm stuck and can't continue with the lessons.  HELP!

### What actually happened? 

"VM1249:1 Uncaught ReferenceError: todoList is not defined
    at <anonymous>:1:1"
Every time.

### Describe what you've done so far to troubleshoot the problem. 

You said there were typos throughout the toggleAll method, which there weren't, yet there was one in the addTodo function was fine but there was an error in the addTodo function. 
The problem persists.  
Is there any way to see the completed code per lesson? i feel like copying off a paused moving video lesson by lesson like what I did to correct my work today is cool and all, but it still doesn't work.  Is there any way to compare to see where I'm off?

**Comment by DBNoisemaker** [comment]
i'm going to do the whole thing over, would probably be a good thing to do anyways. no need to inquire into this.

**Comment by gordonmzhu** [comment]
Sounds good @DBNoisemaker. Thanks for the update.
