### ISSUE TITLE
Why isn't it possible to substitute new variables?

### ISSUE THREAD

**Issue by moreno4211** [gordonmzhu/questions#91]
### What is the associated Watch and Code lesson?  https://watchandcode.com/courses/practical-javascript/lectures/928384

Write your response here (required).
Hi! I am currently on V2 with the video: It should have a function to display todos.
I have entered the code along with the video & the console displays properly just like your example. To practice, I have tried the change the word of todos to teas & then change the items to tea names. Everything else remains the same but the function will not display when I change the words. In your example it will display: 

My todos: (3) ["item 1", "item 2", "item 3"] 

when I try to display the tea names it comes up with:

  console.log('My teas:', teas);
}
I have attached a screenshot. What am I missing that would cause this to not run with just new terms? 

### Include a live demo link so that I can run your code. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
![screenshot 2018-10-21 12 55 43](https://user-images.githubusercontent.com/42595669/47271744-d7c5a180-d530-11e8-9c0f-53dbf58e1267.png)

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).
  
### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by gordonmzhu** [comment]
You are running the `displayTodos` function but you are not running the `displayTeas` function. Pay attention to the presence of parentheses and what their role is in functions. You should go back and review if you aren't sure.
