### ISSUE TITLE
Question about Version 11 PJS

### ISSUE THREAD

**Issue by joruchan** [gordonmzhu/questions#94]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1181252  around minute 5

### Include a live demo link so that I can run your code. 

No need because it's a theory question :)

Hi, first of all great courses, I'm loving it :)
I'm wondering about the thisArg optional parameter for the forEach function. Was it truly necessary in this situation? For example, instead of adding this as the thisArg for the todoList.todos.forEach, (fig 1) could we have not just used view.createDeleteButton (fig 2) ? What is the benefit of adding an argument and an extra step here where it essentially will always be "view." in this situation, since the objects are all in the view variable anyways?

Not sure if I make myself clear, if not don't hesitate and i'll try to formulate it another way. Thanks again for the great courses, very sure i'll go premium as soon as i'm done with PJS :)!

fig 1 : 

```
        todoLi.id = position;
        todoLi.textContent = todoTextWithCompletion;
        todoLi.appendChild(this.createDeleteButton() );
        todosUl.appendChild(todoLi);
      }, this);
```

fig 2 : 

```
        todoLi.id = position;
        todoLi.textContent = todoTextWithCompletion;
        todoLi.appendChild(view.createDeleteButton() );  // replaced with view.createDel(...)
        todosUl.appendChild(todoLi);
      };

```

**Comment by gordonmzhu** [comment]
Good observation. Your approach is fine and technically equivalent.

My intent was just to give people more practice with `this`.
