### ISSUE TITLE
TypeError in V8 video #1 - Our first refactoring

### ISSUE THREAD

**Issue by ducedo** [gordonmzhu/questions#96]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/JV0Aw0NVn6bz5qapU2Jt

### Explain the exact steps I need to take to replicate the problem. 

Click on the last "Toogle All" button, using onclick to call handlers.toogleAll()

### What did you expect to happen? 

The text "Your todo list is empty!" in the console. I tried replicating the code and expected the result I saw in the video.

### What actually happened? 

(index):15 Uncaught TypeError: handlers.toogleAll is not a function
    at HTMLButtonElement.onclick ((index):15)

If I comment out the original buttons above then I seem to get a similar error for the "Display Todos" button as well.

### Describe what you've done so far to troubleshoot the problem. 

I added "debugger;" before "var handlers" and clicked next but it just jumped past the whole object which wasn't very helpful. So I tried to add "debugger;" inside it but then it complained about "unexpected token ;". I've been learning PHP for a few years and there the most common problem is a forgotten char or a typo but I can't seem to find anything like that here. Sort of wish I had the target code so I could compare line for line.

**Comment by gordonmzhu** [comment]
You have a bunch of typos. Make sure you consistently use the same spelling for the same word. For example, 'toogle' is not a word, yet you are using it in your code. Once you fix your typos, the code will work. I suggest going back a few versions and redoing things so that you can eliminate the existing typos in your code.
