### ISSUE TITLE
Handler objects vs referencing methods directly?

### ISSUE THREAD

**Issue by cdallasanta** [gordonmzhu/questions#97]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1027547
3:20

### Include a live demo link so that I can run your code. 

http://plnkr.co/edit/33ZH3lzZGxDiFxX6Gsh5
Though this question is not so much about debugging, but why you went about this problem in a certain way. In this video, you used an objects called handlers, and referenced it with the onclick. So when you clicked, the computer went to the handler object, then the function, which called the todoList object, and it's function. Is there a reason you had that intermediary step of using the handlers object instead of just having: onclick="todoList.toggleAll()" ? Is it part of industry common practice? Or will it make better habits for when I'm dealing with larger projects? Thank you for the lessons and learning!

### Explain the exact steps I need to take to replicate the problem. 

See question above, code works as I expect, but would like to know why you went about it in a certain way.

### What did you expect to happen? 

See question above, code works as I expect, but would like to know why you went about it in a certain way.

### What actually happened? 

See question above, code works as I expect, but would like to know why you went about it in a certain way.

### Describe what you've done so far to troubleshoot the problem. 

I have tried googling about handler objects to see if that's a common practice, or why it would be handled in that way, but I can't find anything.

**Comment by cdallasanta** [comment]
I may have just figured it out, using an example I already have in my code. With the handler object, I can test or tweak things before calling the function, like testing which key was pressed for an onkeyup or to run a different function based on an element's property. If there are other important cases for using this setup, let me know! Thank you!

**Comment by gordonmzhu** [comment]
@cdallasanta Objects are ultimately just an organizational tool. So if you put some data on one object or another doesn't make any technical difference. It's a bit like packing things in a backpack. Do you put something in the main compartment, the side pocket, in the small pocket? There might be subtle pros and cons to each, but ultimately you just want to make sure that you remembered to pack the item. What pocket its in is not so important.
