### ISSUE TITLE
Code Example 4.

### ISSUE THREAD

**Issue by Geoge61** [gordonmzhu/questions#98]
I believe that I understood the video and the lesson.  I just want to test my understanding.

I don't have any code to run.  I just have a question and what I believe is the correct answer.
Write your response here (required).

If I understand the lesson in Code Example 4, (https://watchandcode.com/courses/60264/lectures/3954983), then the content of myHouse1 and myHouse2 are the same memory address, so myHouse1 === myHouse2 should be true.  Because, the two variable names are different names for the same address and the address is the value that javascript compares when comparing two objects.

**Comment by Geoge61** [comment]
I am sorry.  I realized after I posted this that I could test my theory in Plunker.  Yes, given the code stipulated, myHouse1 === myHouse2; returns true.

**Comment by gordonmzhu** [comment]
Cool. Make sure to also draw the diagrams on your own beforehand as I mention in the videos.
